### ISSUE TITLE
[subset] Have an option (default?) to use maxp version 0.5

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#130]
All the extra fields in format 1.0 are useless.

**Comment by anthrotype** [comment]
I tried setting the maxp.tableVersion to "0x00005000" for a TrueType font.

On Windows 7, it complains: 
> "The requested file... is not a valid font file"

I wouldn't risk breaking compatibility for just 26 bytes...

**Comment by anthrotype** [comment]
Also OS X Font Book finds "2 serious errors" and warns "Do not use these font":

> 'maxp' table structure
> System validatiion

Here's the TTX diff between the original font, and the one with maxp.tableVersion set to 0x00005000 (ignoring the checkSumAdjustment)

```diff
   <maxp>
-    <tableVersion value="0x5000"/>
+    <!-- Most of this table will be recalculated by the compiler -->
+    <tableVersion value="0x10000"/>
     <numGlyphs value="484"/>
+    <maxPoints value="89"/>
+    <maxContours value="7"/>
+    <maxCompositePoints value="122"/>
+    <maxCompositeContours value="6"/>
+    <maxZones value="1"/>
+    <maxTwilightPoints value="0"/>
+    <maxStorage value="0"/>
+    <maxFunctionDefs value="0"/>
+    <maxInstructionDefs value="0"/>
+    <maxStackElements value="0"/>
+    <maxSizeOfInstructions value="0"/>
+    <maxComponentElements value="3"/>
+    <maxComponentDepth value="1"/>
   </maxp>
```

**Comment by behdad** [comment]
Thanks Cosimo for investigation.  Lets close indeed.
