### ISSUE TITLE
[subset] Removing CFF hints can make font illegal

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#144]
There's a bug in the hintmask stripping that leaves residual bytes, which makes OTS reject the font.  Ouch.

**Comment by behdad** [comment]
The new --desubroutinize option works around that bug.

**Comment by behdad** [comment]
Closing as duplicate of https://github.com/behdad/fonttools/issues/343

**Comment by miguelsousa** [comment]
@anthrotype can this note be removed?
```
      XXX Note: Currently there is a known bug in 'CFF ' hint stripping that
      might make the font unusable as a webfont as they will be rejected by
      OpenType Sanitizer used in common browsers. For more information see:
      https://github.com/behdad/fonttools/issues/144
      The --desubroutinize options works around that bug.
```
https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/subset/__init__.py#L179-L183

**Comment by anthrotype** [comment]
I believe so. @behdad?

**Comment by behdad** [comment]
Yes!

**Comment by miguelsousa** [comment]
Done https://github.com/fonttools/fonttools/commit/e69960cce06aa4e23bb5c01bfebbd270928b8421
