### ISSUE TITLE
[subset] WOFF2 support? (request)

### ISSUE THREAD

**Issue by rolfnl** [behdad/fonttools#182]
Since Google Chrome is already supporting WOFF2 (and so do other browsers) and the technology is in house.. any plans to add WOFF2 support to pyftsubset?

**Comment by anthrotype** [comment]
hey @rolfnl,
a WOFF2 encoder/decoder is pending review at this pull request https://github.com/behdad/fonttools/pull/222
It requires the [Brotli Python extension](https://github.com/google/brotli), and works just like fontTools' WOFF 1.0 encoder: e.g. you can pass the `--flavor=woff2` option to pyftsubset, or more generally you can set a TTFont `flavor` attribute to "woff2" before saving (or "None" if you want to decompress a WOFF2 font to plain sfnt format).
I hope this is what you were looking for.

Cheers,

Cosimo
