### ISSUE TITLE
Moving xmlWriter to fontTools.misc breaks tools depending on previous structure

### ISSUE THREAD

**Issue by benkiel** [behdad/fonttools#190]
Robofab (and possibly other tool using XMLWriter to write UFOs) expect to be able to import xmlWriter from fontTools, not fontTools.misc, this breaks RoboFab installations which update to this version of fontTools

**Comment by typemytype** [comment]
thanks for reopening this issue 
please reconsider moving both xmlWriter.py and sstruct.py back to the top level
as this is a widely used outside fontTools see fe. roboFab and drawBot (for exporting svg data).

**Comment by behdad** [comment]
I'll add wrappers in the original location that would import * from the current location.  Would that work?

**Comment by anthrotype** [comment]
why can't roboFab or drawBot just `from fontTools.misc import xmlWriter`?

The old xmlWriter.py from the sourceforge fontTools v2.4, and the current one, have changed quite a bit.

For example, in the current xmlWriter.py the method `writeraw` is renamed `_writeraw`. I've seen old scripts around being broken by that small change (I'm not arguing for reverting the changes, but rather for updating the old scripts).

**Comment by behdad** [comment]
> why can't roboFab or drawBot just from fontTools.misc import xmlWriter?

I imagine not everyone is ready to *depend* on my fork yet.  RoboFab tries both, but if there's other code around using it, I'm fine with reducing the cost of switching to my repo.

> The old xmlWriter.py from the sourceforge fontTools v2.4, and the current one, have changed quite a bit.
> 
> For example, in the current xmlWriter.py the method writeraw is renamed _writeraw. I've seen old scripts around being broken by that small change (I'm not arguing for reverting the changes, but rather for updating the old scripts).

Sigh.  The fact there's not much of a public vs private API in Python makes it really hard to touch any code without possibly breaking other code.  I'm fine with adding back writeraw() if there's user for it.

**Comment by anthrotype** [comment]
I see you point. I just liked the fontTools package to be self-contained, that's it.
The question is: do (should) xmlWriter.py and sstruct.py belong to the fontTools library, or are they (should they be) independent from it?

**Comment by typemytype** [comment]
that would work for me
this is exactly what I did as temp solution on my local machine.

thanks

**Comment by behdad** [comment]
> I see your point. I just liked the fontTools package to be self-contained, that's it.
> The question is: do (should) xmlWriter.py and sstruct.py belong to the fontTools library, or are they (should they be) independent from it?

That was why I moved them into fontTools.  I'll keep them there and add a wrapper for backward compatibility.  In the future, if we make more drastic changes, we can make a static copy in the old location and never touch those again.

**Comment by anthrotype** [comment]
sounds good

**Comment by anthrotype** [comment]
Moving xmlWriter.py and sstruxt.py modules  back to the /Lib folder is not enough. We also need to tell the setup.py to install those standalone "py_modules".
I fixed this issue in the setuptools branch https://github.com/behdad/fonttools/pull/273
