### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by mohsinhijazee** [behdad/fonttools#211]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with fonttools. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable fonttools on @Sourcegraph by going to https://sourcegraph.com/github.com/behdad/fonttools and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by behdad** [comment]
I believe I've done that now.  But haven't been able to find anything fascinating with sourcegraph.  What are some cool things it can do?

**Comment by twardoch** [comment]
One thing that seems to be of immediate use is the build logs: 
https://sourcegraph.com/github.com/behdad/fonttools/.builds
https://sourcegraph.com/github.com/behdad/fonttools/.builds/1673513/log

**Comment by behdad** [comment]
Humm, what's useful in the "build logs"?  I see it say fail but I don't understand what that means.

**Comment by behdad** [comment]
Ok I think I see what it's trying to do.  At any rate, I'll set up Travis for fonttools such that I can monitor the build.

**Comment by behdad** [comment]
Travis is now enabled:
http://travis-ci.org/behdad/fonttools/builds
