### ISSUE TITLE
Typo for OS/2 table: "usMaxContex"

### ISSUE THREAD

**Issue by tshinnic** [behdad/fonttools#213]
Noticed on TTX dumping the AAT TTF file cited by (possibly) @olivierberten circa 12/6/14 : [entiumgay.ttf](http://entiumgay.sourceforge.net/) [download](http://downloads.sourceforge.net/project/entiumgay/Entiumgay%202010-08-26.zip?r=http%3A%2F%2Fentiumgay.sourceforge.net%2F&ts=1422661862&use_mirror=iweb)  but checking now see this in other dumps.
And now I can't find the trail (which issue?) I took from here to get there   :confused:   I think it was about 'feat' and/or 'FeatureName' ...  :disappointed: 
```
    <usDefaultChar value="0"/>
    <usBreakChar value="32"/>
    <usMaxContex value="3"/>
```
s/usMaxContex/usMaxContext/
OS/2 table doc [link](http://www.microsoft.com/typography/otspec/os2.htm)

Problem seen at ttLib [OS/2 table](https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/O_S_2f_2.py#L82)  and searching found another mention in [merge.py](https://github.com/behdad/fonttools/blob/19dadb37d6642fb73f7a32a78ce907e2475ae4cf/Lib/fontTools/merge.py#L274)

**Comment by behdad** [comment]
Yeah, we know that.  Fixing it might break people's scripts or XML.  Not sure if we should touch it or leave it.

**Comment by twardoch** [comment]
Leave it as is. It's cosmetic, stability of existing code and XML wins IMO.

**Comment by davelab6** [comment]
If leaving it, maybe add a note to the documentation to close this issue?

**Comment by behdad** [comment]
Will do, when we have documentation. ;)
