### ISSUE TITLE
cmap: unsigned short overflow in char codes

### ISSUE THREAD

**Issue by adrientetar** [behdad/fonttools#215]
@behdad: I have a crash in cmap generation at [this line](https://github.com/behdad/fonttools/blob/21af87536f23d8c4fef27e75389d5551eb9ec65c/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L784).

Backtrace:

~~~
Traceback (most recent call last):
  File "build.py", line 6, in <module>
    reports = compiler.compile(font, "/MyDirectory/MyFont.otf", checkOutlines=False, autohint=True)
  File "/usr/local/lib/python2.7/dist-packages/ufo2fdk/__init__.py", line 86, in compile
    partsCompiler.compile()
  File "/usr/local/lib/python2.7/dist-packages/ufo2fdk/makeotfParts.py", line 64, in compile
    self.setupFile_outlineSource(self.paths["outlineSource"])
  File "/usr/local/lib/python2.7/dist-packages/ufo2fdk/makeotfParts.py", line 79, in setupFile_outlineSource
    c.compile()
  File "/usr/local/lib/python2.7/dist-packages/ufo2fdk/outlineOTF.py", line 80, in compile
    self.otf.save(self.path)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 212, in save
    self._writeTable(tag, writer, done)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 627, in _writeTable
    tabledata = self.getTableData(tag)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/__init__.py", line 640, in getTableData
    return self.tables[tag].compile(self)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 68, in compile
    chunk = table.compile(ttFont)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/_c_m_a_p.py", line 782, in compile
    charCodeArray = array.array("H", endCode + [0] + startCode)
OverflowError: unsigned short is greater than maximum
~~~

So I decided to print my `startCode` and `endCode` arrays:

~~~
[126, 255, 305, 322, 339, 353, 376, 382, 402, 711, 713, 733, 7838, 8199, 8203, 8214, 8218, 8222, 8227, 8230, 8240, 8243, 8250, 8260, 8305, 8334, 8339, 8348, 8355, 8364, 8381, 8471, 8480, 8482, 8542, 8601, 8722, 8725, 8729, 8776, 8800, 8805, 9320, 9633, 9635, 9643, 9655, 9665, 9675, 9679, 9734, 9756, 9758, 9824, 9827, 9830, 10110, 10217, 11046, 11198, 129123, 65535]
[32, 160, 305, 321, 338, 352, 376, 381, 402, 710, 713, 728, 7838, 8199, 8201, 8208, 8216, 8220, 8224, 8229, 8239, 8242, 8249, 8260, 8304, 8308, 8336, 8341, 8355, 8364, 8381, 8470, 8480, 8482, 8531, 8592, 8722, 8725, 8729, 8776, 8800, 8804, 9312, 9632, 9635, 9642, 9654, 9664, 9673, 9679, 9733, 9756, 9758, 9824, 9827, 9829, 10102, 10216, 11045, 11197, 129120, 65535]
~~~

65535 is 0xFFFF and that's the max. value of an unsigned short. However I have unicode values like 0x1F860 (U+1F860) which yields values like 129120, is that what causes the overflow?

Microsoft otspec specifies startCharCode and endCharCode as unsigned long (see spec excerpt below), so is it that fontTools does not use the appropriate variable type here?

~~~
ULONG	startCharCode	First character code in this group; note that if this group is for one or more 16-bit character codes (which is determined from the is32 array), this 32-bit value will have the high 16-bits set to zero
ULONG	endCharCode	Last character code in this group; same condition as listed above for the startCharCode
~~~

EDIT: So (I do not really know the otspec but) it seems there are several cmap table formats with different storage, and apparently the ufo2fdk package I'm trying to create an OTF with [only sets up cmap format 4](https://github.com/typesupply/ufo2fdk/blob/master/Lib/ufo2fdk/outlineOTF.py#L242), is that what would be causing this problem then? That everything gets sent to format 4 which cannot hold higher unicode values?

**Comment by behdad** [comment]
You need a format 12 cmap subtable.  ufo2fdk doesn't support that.  I believe @jamesgk has a fix for that.

**Comment by adrientetar** [comment]
Thanks behdad. Is James working in this domain for Google?

**Comment by behdad** [comment]
We were using ufo2fdk for some experiments.

**Comment by miguelsousa** [comment]
ufo2fdk has been corrected, it seems https://github.com/typesupply/ufo2fdk/pull/3

**Comment by behdad** [comment]
Not sure if that's the same.

**Comment by jamesgk** [comment]
Yea, I would make sure you're using the latest version of ufo2fdk. And if you're still having this issue try making your own outline compiler class as a child of ufo2fdk's, overriding the cmap table setup to use format 12. Something like:

```python
from ufo2fdk.outlineOTF import OutlineOTFCompiler

class OutlineCompilerFormat12(OutlineOTFCompiler):
    def setupTable_cmap(self):
        from fontTools.ttLib.tables._c_m_a_p import cmap_format_12
        # setup mac-compatible table
        cmap12_0_3 = cmap_format_12(12)
        cmap12_0_3.platformID = 0
        cmap12_0_3.platEncID = 3
        cmap12_0_3.language = 0
        cmap12_0_3.cmap = dict(self.unicodeToGlyphNameMapping)
        # setup windows-compatible table
        cmap12_3_1 = cmap_format_12(12)
        cmap12_3_1.platformID = 3
        cmap12_3_1.platEncID = 1
        cmap12_3_1.language = 0
        cmap12_3_1.cmap = dict(self.unicodeToGlyphNameMapping)
        # store tables
        self.otf["cmap"] = cmap = newTable("cmap")
        cmap.tableVersion = 0
        cmap.tables = [cmap12_0_3, cmap12_3_1]
```

Then create your OTF compiler with this class:

```python
from ufo2FDK import OTFCompiler
compiler = OTFCompiler(outlineCompilerClass=OutlineCompilerFormat12)
```

**Comment by behdad** [comment]
@jamesgk should we upstream the format 12 fix?

**Comment by adrientetar** [comment]
> @jamesgk should we upstream the format 12 fix?

I assume format 12 eats up more memory... shouldn't a proper OTF font be a mix of the two?

**Comment by behdad** [comment]
It's simple: if non-BMP chars are available, format 12 should be added.  Format 4 should always be added and include all the BMP chars.

**Comment by jamesgk** [comment]
Actually, when I tried a conversion with the most recent ufo2fdk it created OTFs with format 12 cmap tables, even without this overridden class. I'm not really sure how; I'd probably have to dig into ufo2fdk (or maybe the FDK itself) to figure out exactly what's going on. But for now I don't think the library needs any more fixing.

**Comment by adrientetar** [comment]
So how come I got the trace above? And I don't see anything in the code that would produce this.

I've made this patch: https://github.com/adrientetar/ufo2fdk/commit/aed66ea4a820f6c7b4ca012b96d86efed30c7848 have yet to test it.

**Comment by behdad** [comment]
Your function with a very long name can easily be written in one line as:

nonBMP = dict((k,v) for k,v in mapping.items() if v > 65535)

**Comment by jamesgk** [comment]
Sorry, you're right, I tried again and am having the same issue. (Mysteriously, the conversion was working with an out-of-date copy of FontTools. Anyways....)

I tried your patch and it worked with some adjustments -- what Behdad said, and also arithmetic operators don't seem to work on dictionaries.
