### ISSUE TITLE
ttx fails to convert iOS 8.2 AppleSDGothicNeo.ttc

### ISSUE THREAD

**Issue by jogu** [behdad/fonttools#218]
The current master version of ttx seems to fail on a new font that is part of iOS 8.2:

$ ttx AppleSDGothicNeo.ttc 
Dumping "AppleSDGothicNeo.ttc" to "AppleSDGothicNeo.ttx"...
Error: specify a font number between 0 and 13 (inclusive)
$

fontNumber seems to be -1.

If I change the exception to a 'pass' ttx appears otherwise happy.

I've put a copy of the font here: https://www.dropbox.com/s/so9awb7ot1q5pai/AppleSDGothicNeo.ttc?dl=0

(I'm guessing it may well be that the font is incorrect, but thought it worth reporting anyhow just in case. Thanks for ttx, I use it a lot!)

**Comment by anthrotype** [comment]
hey @jogu, the font is not incorrect. In fact, that's the way ttx is supposed to work.

The font you mention is a TrueType Collection (*.ttc) font, therefore you need to pass the `-y` option to specify the index of the individual font in  the TrueType collection that you wish to dump.

Here ttx is telling you the collection contains 14 fonts -- `between 0 and 13 (inclusive)`. If you want to dump all of them, you can repeat the call to ttx incrementing the `-y` value until you have dumped all the fonts.
If you type `ttx --help`, it should display the `-y`option as well.

All best,
Cosimo

**Comment by jogu** [comment]
hi @anthrotype - that makes a lot of sense. Thanks. I'd missed that. I'm sure I've run ttx loads of times before on a .ttc without specifying -y, but the most likely explanation for that would be that my memory sucks. :-) Thanks!

**Comment by behdad** [comment]
I have some code to handle TTCs as a whole.  Have to finish that...
