### ISSUE TITLE
getMacCreatorAndType() is Mac-specific, legacy API

### ISSUE THREAD

**Issue by adrientetar** [behdad/fonttools#221]
Used in [t1lib.py](https://github.com/behdad/fonttools/blob/5ba7d98a4153fad57258fca23b0bcb238717aec3/Lib/fontTools/t1Lib.py#L106) and in ttx.py to guess filenames. Typesupply's extractor [needs this API](https://github.com/typesupply/extractor/blob/master/Lib/extractor/formats/type1.py) in order to guess Type1 kind of the input data. Two issues:

- is Mac OS-specific
- relies on Carbon APIs so not compatible with 64-bit Python (extractor uses its own AppKit API calls)

**Comment by behdad** [comment]
I have no idea how to fix this.  Patches are welcome.

**Comment by adrientetar** [comment]
> I have no idea how to fix this. Patches are welcome.

It seems the sniffing in t1lib is only to detect LWFN (MacBinary) T1 files, and these files contain "LWFN" in their binary header, so it might be possible to just read the beginning of the file as binary and find if it contains that. Sounds good? I've been trying to find a spec for these special files to see if the header can vary in length eventually but no luck, the Adobe spec sheets don't mention anything about LWFN.

**Comment by behdad** [comment]
That might work.  I don't know anything about LWFN either.  Can you raise this on the fonttools Google Group?

**Comment by readroberts** [comment]
I can't find any documentation for the LWFN file type. I can tell you that it is a Mac resource fork file, with data only in the resource fork. The file contains a standard Type1 font, chopped up into a string of POST resources. The first POST resource contains the unencrypted part, the rest contain the encrypted parts. You can find code needed to parse it in the AFDKO program 'tx', When writing and LWFN file, it first writes a temp Type1 Unix file, then calls tx.c:t1_Reformat() to re-write this as a LWFN file - but in a data fork.
Perhaps more useful is the code for sniffing and reading file formats, in tx.c:buildFontLists(). This will call 'doResMap()' if the file is Apple Resource file, or doASDFormats(), if it is an Apple Resource file which has been converted to Apple Single or Apple Double formats. You may want to copy this  code - reading and processing the POST resources is very simple, but navigating the Apple Resource fork structures to find the POST resources is complex.  

My ideal approach would be to no longer support Apple Resource fork fonts!

**Comment by behdad** [comment]
> My ideal approach would be to no longer support Apple Resource fork fonts!

That works for me.  Anyone, any objections?  Patch welcome.

**Comment by readroberts** [comment]
After all, you can always use the Apple SplitForks tool to copy the resource fork in to a regular data file,, and then use the AFDKO tool 'tx'  to convert it to a Type 1 font file :)

**Comment by adrientetar** [comment]
Or maybe we can just update to Appkit APIs for Mac users and keep skipping the detection for other OSes which are unlikely to deal with the files anyway?
