### ISSUE TITLE
V_D_M_X_ vTables 

### ISSUE THREAD

**Issue by t42-ink** [behdad/fonttools#224]
From the documentation ( https://www.microsoft.com/typography/otspec/vdmx.htm )
"This table must appear in sorted order (sorted by yPelHeight)"

line 142 of /Lib/fontTools/ttLib/tables/V_D_M_X_.py:
>>> for yPelHeight, (yMax, yMin) in group.items():

Needs to sort the list group.items() before creating the vTables.

kind regards,
Jeremie

**Comment by behdad** [comment]
Fixed by https://github.com/behdad/fonttools/pull/225.  Thanks.
