### ISSUE TITLE
bug in _g_l_y_f table while reading ttf font

### ISSUE THREAD

**Issue by typemytype** [behdad/fonttools#238]
> fonttools/Lib/fontTools/ttLib/tables/_g_l_y_f.py", line 925, in draw
    coordinates = coordinates + (offset, 0)
TypeError: unsupported operand type(s) for +: 'GlyphCoordinates' and 'tuple'

do you need more info?

could be solved with:

```Python
if offset:
    coordinates.extend([(offset, 0)])
```
thanks

**Comment by anthrotype** [comment]
that `offset` argument of Glyph's `draw` method, what is it supposed to do? Translating the coordinates (along the x axis only?) by a specified amount?

if that is the case, then line 925 could be changed from:

    coordinates = coordinates + (offset, 0)

to:

    coordinates.translate((offset, 0))

GlyphCoordinates has a `translate` method which accepts a (x,y) tuple.

**Comment by behdad** [comment]
> that offset argument of Glyph's draw method, what is it supposed to do? Translating the coordinates (along the x axis only?) by a specified amount?

Yes.  In TrueType, the lsb from hmtx table and the xmin from the glyph are subtracted to result in an offset to be applied to the outline.

> if that is the case, then line 925 could be changed from:
> 
> coordinates = coordinates + (offset, 0)
> 
> to:
> 
> coordinates.translate((offset, 0))

Right.  My bad.  Either that, or implement addition for the GlyphCoordinates object.  I think I'll take your fix since it's trivial.

**Comment by behdad** [comment]
Pushed a fix.  Please test.

**Comment by typemytype** [comment]
thanks!
