### ISSUE TITLE
raise a proper TTLibError while opening a "com.adobe.postscript-lwfn-font" type1 font

### ISSUE THREAD

**Issue by typemytype** [behdad/fonttools#239]
> fonttools/Lib/fontTools/misc/sstruct.py", line 87, in unpack
    elements = struct.unpack(formatstring, data)
error: unpack requires a string argument of length 12

raising the correct error is import for packages like Extractor

see https://github.com/typesupply/extractor/blob/master/Lib/extractor/formats/opentype.py#L12-L18

for your reference: http://sourceforge.net/p/fonttools/code/ci/master/tree/Lib/fontTools/ttLib/sfnt.py#l28

thanks!

**Comment by typemytype** [comment]
this could be solved by comparing the size of the 'data' retrieved from the file and size of the header (for each supported format) and raise a TTLibError if needed

a quick fix:
```Python
		if self.sfntVersion == b"ttcf":
			sstruct.unpack(ttcHeaderFormat, self.file.read(ttcHeaderSize), self)
			assert self.Version == 0x00010000 or self.Version == 0x00020000, "unrecognized TTC version 0x%08x" % self.Version
			if not 0 <= fontNumber < self.numFonts:
				from fontTools import ttLib
				raise ttLib.TTLibError("specify a font number between 0 and %d (inclusive)" % (self.numFonts - 1))
			offsetTable = struct.unpack(">%dL" % self.numFonts, self.file.read(self.numFonts * 4))
			if self.Version == 0x00020000:
				pass # ignoring version 2.0 signatures
			self.file.seek(offsetTable[fontNumber])
			data = self.file.read(sfntDirectorySize)
			if len(data) != sfntDirectorySize:
				from fontTools import ttLib
				raise ttLib.TTLibError("Not a ttcf font (not enough data)")	
			sstruct.unpack(sfntDirectoryFormat, data, self)
		elif self.sfntVersion == b"wOFF":
			self.flavor = "woff"
			self.DirectoryEntry = WOFFDirectoryEntry
			data = self.file.read(woffDirectorySize)
			if len(data) != woffDirectorySize:
				from fontTools import ttLib
				raise ttLib.TTLibError("Not a wOFF font (not enough data)")				
			sstruct.unpack(woffDirectoryFormat, data, self)
		else:
			data = self.file.read(sfntDirectorySize)
			if len(data) != sfntDirectorySize:
				from fontTools import ttLib
				raise ttLib.TTLibError("Not a TrueType or OpenType font (not enough data)")
			sstruct.unpack(sfntDirectoryFormat, data, self)
		self.sfntVersion = Tag(self.sfntVersion)
```

thanks

**Comment by behdad** [comment]
I can see how useful it is in this context and willing to do that, but we don't guarantee that for rest of the codebase...

@anthrotype WDYT?  Since this probably affects your woff2 branch, can we merge the two?

**Comment by anthrotype** [comment]
Ok, I see. You just want to check if there are enough bytes in the file being read before unpacking them with sstruct/struct, and raise TTLibError in case there aren't, to prevent struct from raising its own exception.
Yes, that could be done like you proposed. It'd be easy to amend the woff2 branch accordingly.

**Comment by behdad** [comment]
Yeah, either that, or we need to add a function to detect file type...

**Comment by behdad** [comment]
@anthrotype So what do you think about this?

**Comment by anthrotype** [comment]
@behdad sorry for late reply. I think we should have a proper function to detect all supported file types. We could extend the current `ttx.guessFileType` and move that to ttLib.__init__. The function would be used to pick up the compatible reader class, or to raise a TTLibError if the type is not supported.
However, while we think about that, we can already add a test for "enough data" to sfnt and woff2 modules, like the one proposed by @typemytype. I'll send a PR in a minute.

**Comment by typemytype** [comment]
thanks
