### ISSUE TITLE
xmlWriter.py: Capitalize UTF-8

### ISSUE THREAD

**Issue by frankrolf** [behdad/fonttools#246]
Historically, FontTools has written the first line of an XML file like this:
`<?xml version="1.0" encoding="UTF-8"?>`, 
(with UTF capitalized, as Unicode.org and W3C do).

In this fork, the UTF has changed to lowercase. 
Since Robofont now has moved to use this fork of FontTools, thousands of glyph files change in source control (I am sure not only on my system).

Please change UTF back to uppercase.

**Comment by benkiel** [comment]
+1

See a patch I submitted for a workaround to this.

**Comment by benkiel** [comment]
Note, python3.x isn't something I deal with, so the string formatting I did in my patch may no longer be legal, but the idea is there.

**Comment by behdad** [comment]
Hum.  The fonttools that I inherited was writing XML in latin1, not UTF-8.  I fixed that in 4b3df49b5b70b3618e91e3ab954cedca773831d6.

I can make the change you are requesting, but want to understand the issue completely first.

@benkiel which patch is that?

**Comment by frankrolf** [comment]
Does the line`parser = ParserCreate("latin1")` really specify the encoding of the resulting XML file? 
I don’t think it does. When I write a TTX file with the sourceforge fork, it comes out as UTF-8.

I think the XML encoding is passed to the function here:
http://sourceforge.net/p/fonttools/code/ci/master/tree/Lib/xmlWriter.py#l25

Thanks for considering this fix.

**Comment by behdad** [comment]
> Does the lineparser = ParserCreate("latin1") really specify the encoding of the resulting XML file?

No.  That's for the xmlReader.  I was talking about this line:

```patch
-	def __init__(self, fileOrPath, indentwhite=INDENT, idlefunc=None, encoding="ISO-8859-1"):
+	def __init__(self, fileOrPath, indentwhite=INDENT, idlefunc=None, encoding="utf-8"):
```

> I don’t think it does. When I write a TTX file with the sourceforge fork, it comes out as UTF-8.

I really 

> I think the XML encoding is passed to the function here:
> http://sourceforge.net/p/fonttools/code/ci/master/tree/Lib/xmlWriter.py#l25

Right.  And I don't see where "UTF-8" is being passed to it in the sourceforge version.

> Thanks for considering this fix.

**Comment by miguelsousa** [comment]
@behdad This difference:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/misc/xmlWriter.py#L44
http://sourceforge.net/p/fonttools/code/ci/master/tree/Lib/xmlWriter.py#l25

used by https://github.com/robofab-developers/robofab/blob/master/Lib/robofab/glifLib.py#L355

What's happening is that RoboFont switched from using the fontTools version hosted on SourceForge to using the version hosted here, and now all the glyphs in a UFO are written with this change,
```diff
- <?xml version="1.0" encoding="UTF-8"?>
+ <?xml version="1.0" encoding="utf-8"?>
```

**Comment by behdad** [comment]
Ok.  That solves the mystery.  My point was that the fontforge fonttools was never writing XMLs in UTF-8 in TTX, but if other libraries used xmlWriter, indeed, it could make a difference.

I'll fix this up to retain whatever user passed in.  That would fix the robofab issue.

Question is, should I change the default encoding for ttx files from "utf-8" to "UTF-8"?  That will break font files stored in ttx.  Searching around, I see "UTF-8" is preferred, but not sure I want to break people's files now.  What do people think?

**Comment by behdad** [comment]
Ok.  Fixed the robofab part.

Should I switch to "UTF-8" in ttx output as well?

cc @davelab6 @typemytype

**Comment by twardoch** [comment]
I'd prefer to ultimately have one casing. The "UTF-8" variant is older, and I think your "utf-8" is a much more rectent. I think those who store .ttx might find it annoying once shen upgrading but my preference would be that fontTools and ttx are able to READ both "UTF-8" and "utf-8" but always only write "UTF-8".

**Comment by behdad** [comment]
The reading part is ok.  I'll switch to always writing "UTF-8" tomorrow.

**Comment by frankrolf** [comment]
Thanks!

**Comment by benkiel** [comment]
Thank you!
