### ISSUE TITLE
Control characters in name table entries

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#249]
XML disallows characters < U+0020 except for U+0009, U+000A, and U+000D.  Currently we print those out to XML either raw or as XML entities.  Either way, expat fails to read them back in.

There are two categories of this: 1. when the character is truly a Unicode character we write out (ie unicode="True"), and 2. when it's simply a byte of a non-Unicode encoding.  Now, the byte usecase is serious in multibyte encodings that are not ASCII-safe...  But I'm not sure how common they are.  It will happen if a sequence fails to decode as Unicode, eg if a UTF-16 sequence has broken bytes in it or something.

We can approach fixing this a few separate ways:

  - For control characters, and for byte output of non-Unicode entries, introduce a <bytes>xx xx</bytes> syntax, or better, a <byte v="xx"> syntax.  That's very verbose, but semantically correct whereas current way we do this is incorrect XML,

  - Drop control characters.  That's rather safe for Unicode names, but again, may have bad consequences for non-ASCII compatible byte encodings,

Looking at failures, looks like many cases are where UTF-16BE is written out under Apple encodings.  In all cases I see, those are ASCII names.  We can detect this as every even byte is 0, and convert appropriately (with a warning).

**Comment by anthrotype** [comment]
is "DELETE" (0x007F) one of those "control characters" disallowed by XML as well?
We are using `"\x7f"` in the subset.py name obfuscation.
I haven't tested yet, but I wonder if that could create any problems with the XML parser.

**Comment by behdad** [comment]
No.  Delete is fine:
http://www.w3.org/TR/REC-xml/#charsets

I'm developing a few heuristics to recover badly marked and badly-endianed UTF-16.  All the cases I have at hand can be fixed that way.

**Comment by anthrotype** [comment]
ok, thanks!

**Comment by behdad** [comment]
Looks like there's more junk.  Like this one:

```
    <namerecord nameID="7" platformID="3" platEncID="1" langID="0x356" unicode="False"> 
      &#0;Adobe Caslon is a trademark of Adobe Systems Incorporated. 
    </namerecord> 
```

So someone took the ASCII string, prepended one nul byte and wrote it as UTF-16BE!  Fun times...

**Comment by anthrotype** [comment]
good luck!

**Comment by behdad** [comment]
Another commit: https://github.com/behdad/fonttools/commit/c4fb6459b0b6979139f180c37ffb7b5c464dacfd

**Comment by behdad** [comment]
Ok, all the other ones I had got fixed by handling double-encoded UTF-16BE.

Lets close this and reopen as more bad stuff comes in.  We need to handle the control-chars-are-invalid-XML at some point, but lets wait for actual data that can't be decoded before doing that.
