### ISSUE TITLE
[subset] (locl) dotless i + layout features == no layout features in output file

### ISSUE THREAD

**Issue by rolfnl** [behdad/fonttools#257]
(Please correct me if this is no issue at all, or if I describe it wrong)

If I have a font with a locl feature for dotlessi (or i.TRK, whatever you would name it) and I do a subset keeping all the glyphs and all the features for example then for the resulting file (WOFF) no features work anymore.

For example the feature is:
```
feature locl {
	script latn;
	language TRK exclude_dflt;
	sub [I i.smcp] by [Idotaccent idotaccent.smcp];
} locl;
```

If I drop the locl feature (`--layout-features-=locl`) there's no problem.
BTW @twardoch this also happens with TransType4.

Is the feature implemented wrong in the font, is this a WOFF problem or is this a subset problem?

It took me a couple of hours to figure out it was the "i" that was causing the problem when testing, first with a full glyph subset and features, then just 1 feature (like smcp) and a few glyphs at a time etc. jeeez, what a pain ;)

**Comment by behdad** [comment]
Sounds like a font issue to me.  Isn't that what your exclude_dflt mean?!

**Comment by twardoch** [comment]
I'd need to take a look at the font files (before and after). 

Also, your “locl” feature code looks alarmingly wrong. If I type in the name Yazıcıgil in all-caps (YAZICIGİL) then your font will display it as YAZİCİGİL, which of course is wrong (completely changes the pronunciation, making “yah-zee-jee-gheel” from “yah-zeh-jeh-geel”, or so). 

You shouldn't replace all “I”s by “İ”s — that actually does more harm than it helps. Turkish has both I (which is a short I like in the English word “bit”) and İ (which is a long I like in “beat”).

**Comment by twardoch** [comment]
FYI, more descussion on the Turkish "i" is at: http://typedrawers.com/discussion/932/what-is-i-latntrk
