### ISSUE TITLE
[ttx] Pad tags with space at the end

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#265]
Right now if one wants to extract the CFF table using ttx, they have to request -t"CFF ".  The space at the end is implied and we shouldn't require it explicitly.

**Comment by behdad** [comment]
I'm not sure at which level to fix it.  Maybe just the TTX level.

**Comment by anthrotype** [comment]
and `"cvt "` too

**Comment by anthrotype** [comment]
Yes, I think we should fix that from TTX end, and leave the unambiguous four byte tag in the TTFont keys.

**Comment by behdad** [comment]
Sure, I wasn't implying that we special-case 'CFF' ;)

**Comment by behdad** [comment]
This might be opening a can of worms.  pyftsubset also has commandline args that take tags, etc...

**Comment by anthrotype** [comment]
I see...
Well, the specs allow one to specify arbitrary hew table tags, the only requirement being 4-byte long. So even if one wished to create a table tagged 'CFF' with three bytes, it wouldn't be possible.
I guess we can put a check in the TTFont __setitem__: pad the "key" to 4 bytes if len(key) <= 4, and raise an exception of > 4. Similarly, the __getitem__ would first pad the key with spaces up length 4 before attempting to get the table.

**Comment by behdad** [comment]
That's what I had in mind initially.  But it opens door to a case where font[tag1] == font[tag2] when tag1 != tag2...

**Comment by behdad** [comment]
That sounds like recipe for headache.  I'll take a look inside and see if we can have a normalize tag or something.

**Comment by behdad** [comment]
Yeah, I think that's what we want.

**Comment by anthrotype** [comment]
that's weird I know, but despite the appearance it is actually "True" that 

    font['CFF'] == font['CFF ']

it could not be otherwise given the 4-byte requirement for table tags in the OT spec.

**Comment by behdad** [comment]
Ok, if there's water under the bridge already we might as well go full in. :)

**Comment by anthrotype** [comment]
maybe it's easier to not open the can of worms -- e.g. `font['CFF'] == font['CFF ']` -- and simply fix this at the TTX or simlar tools' level.
