### ISSUE TITLE
Include examples?

### ISSUE THREAD

**Issue by davelab6** [behdad/fonttools#282]
@typemytype posted [this fontTools script](https://gist.github.com/typemytype/487d24ede79bc0ec2e36):

```py
from fontTools.agl import UV2AGL
 
 
myText = "héllø"
 
myText = myText.decode("utf-8")
 
 
glyphNames = []
 
for char in myText:
    
    uni = ord(char)
    
    glyphName = UV2AGL.get(uni)
    if glyphName:
        glyphNames.append(glyphName)
        
print glyphNames
 
print "/" + "/".join(glyphNames)
```

I wonder if such scripts could be included in this repo - perhaps in an `examples` directory?

**Comment by anthrotype** [comment]
For things like that there's the ["Snippets"](https://github.com/behdad/fonttools/tree/master/Snippets) folder.

**Comment by davelab6** [comment]
:+1:
