### ISSUE TITLE
Port to logging module

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#284]
Subsetter has its own logger object, and most of the rest of the code doesn't.  We should come up with a unified logging machinery and port everything to that.

**Comment by anthrotype** [comment]
We could use the built-in `logging` module, or subclass it if we need to adapt it to our needs.
https://docs.python.org/2/howto/logging.html

**Comment by behdad** [comment]
Yeah, sorry I meant logging module.

**Comment by anthrotype** [comment]
Fixed in #488.
