### ISSUE TITLE
Conversion fixed → float → fixed changes 5% of input values

### ISSUE THREAD

**Issue by brawer** [behdad/fonttools#286]
For about 5% of all 2.14 fixed-point values, floatToFixed(fixedToFloat(value, 14), 14) changes the value. This is a problem when TTX code invokes fixedToFloat() to decompile input data.

I had noticed that in my ‘gvar’ branch, fonts would not produce the exact same outlines after a round-trip through TTX. The root cause was the following: In order to parse coordinates of ‘gvar’ tuples, my code was calling fixedToFloat(value, 14) at decompilation time. In the opposite direction, when compiling a binary ‘gvar’ table, my code would call floatToFixed(value, 14). In the current implementation of fontTools.misc.fixedTools, this fixed → float → fixed conversion sometimes changed the value by 0.000061, which is 1 unit in 2.14 fixed-point space.

Test code for finding what values are affected:

from fontTools.misc.fixedTools import fixedToFloat, floatToFixed
for value in range(-32768, 32768):
        if value != floatToFixed(fixedToFloat(i, 14), 14):
                print(value, fixedToFloat(value, 14), floatToFixed(fixedToFloat(value, 14), 14))

-32756 -1.9993 -32757
-32738 -1.9982 -32739
-32715 -1.9968 -32716
-32697 -1.9957 -32698
-32679 -1.9946 -32680
[…]
32679 1.9946 32680
32697 1.9957 32698
32715 1.9968 32716
32738 1.9982 32739
32756 1.9993 32757

In total, 3266 out of 65536 possible values are affected.

**Comment by anthrotype** [comment]
hmm, this is worrying.
I'm sure it has to do with the fact that `fixedToFloat` function rounds the returned float number to its "shortest decimal representation" (that's what the docstring says).
If I return the value without the rounding, then roundtripping works.
Could we maybe add a parameter to disable the rounding?

**Comment by anthrotype** [comment]
ah, so it was the division operator!

**Comment by brawer** [comment]
I'm quite sure this is the wrong fix (with this change, eps is always 0); but I'm not sure what a better fix would be...

**Comment by anthrotype** [comment]
mayeb here there may be some clues: https://github.com/behdad/fonttools/issues/205

**Comment by anthrotype** [comment]
maybe fixedToFloat should siimply round the float value to the number of decimal digits needed to encode all the fractional bits:

```python
def fixedToFloat(value, precisionBits):
    if not value:
        return 0.0
    scale = 1 << precisionBits
    value /= scale
    digits = (precisionBits + 2) // 3
    return round(value, 5)
```

why does it need to do more than this?

**Comment by anthrotype** [comment]
(there was a typo in the code block above, I fixed it now)

**Comment by anthrotype** [comment]
thanks for fixing this.
I noticed that the roundtripping works for 'precisionBits' up to 16; from 17 it starts accumulating rounding errors again. But that's fine, since the fractional part of fixed-point numbers in TrueType never goes beyond 16 bits. Should we make this explicit in the docstring, or set a maximum supported 'precisionBits' value (i.e. 16)?

**Comment by behdad** [comment]
We can document it so.

Note that many places in OpenType that use a 16.16 representation have a different meaning.  Eg, they encode 1.5 as 0x00010005
