### ISSUE TITLE
"make all" / "make check" don't fail upon syntax error

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#290]
I added the make all / make check to make sure all sources parse correctly.  But looks like they don't do that.  Just introduce a syntax error in subset.py and see how make all happily passes, even though it sees the syntax error.  I haven't found how to make them fail.

**Comment by anthrotype** [comment]
This is the way distutils was designed, and setuptools didn't change this.
The `distutils.util.byte_compile` function calls the standard `py_compile` module; the latter only warns of SyntaxErrors during compilation unless it is passed a `doraise` option -- which neither distutils nor setuptools do.

There's an old open issue in the Python bug tracker: https://bugs.python.org/msg226287
> this behaviour was a deliberate decision, not a bug.  Developers should use tests to detect syntax errors in their code, not rely on distutils byte compilation.

One solution could be to monkeypatch the `py_compile.compile` function and change its default `doraise` argument to True, as one suggests in the above mentioned issue, though I'm not sure it's the cleanest solution...
