### ISSUE TITLE
big unicodes --> OverflowError

### ISSUE THREAD

**Issue by typemytype** [behdad/fonttools#292]
when creating a cmap table from scratch with big unicodes (bigger then 0xFFFF) fontTools somehow fails to compile, this wasn't an issue with the sourceForge version. I narrowed this problem down to the usage of array instead of numpy. 

```
File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 214, in save
File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 629, in _writeTable
File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 642, in getTableData
File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_c_m_a_p.py", line 66, in compile
File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/_c_m_a_p.py", line 796, in compile
OverflowError: unsigned short is greater than maximum
```

It seems like numpy is topping off big unicodes, see this small test case and potential patch:

```Python
import array
# reconstruct the actual code
endCode = startCode = [65846]
# a working patch
t = endCode + [0] + startCode
# by topping of big values so they fit into 2 bytes
t = [i % 0x10000 for i in t]
charCodeArray = array.array("H", t)

# same test with numpy
import numpy

numpycharCodeArray = numpy.array( endCode + [0] + startCode, numpy.uint16)

# compare output
print [ord(i) for i in charCodeArray.tostring()], "array"
print [ord(i) for i in numpycharCodeArray.tostring()], "numpy"

# this will fail
charCodeArray = array.array("H", endCode + [0] + startCode)
```

thanks

**Comment by behdad** [comment]
So, a wrong value used to be silently truncated with numpy, but results in an error now.  I see that as an improvement.  Why do you expect otherwise?

**Comment by typemytype** [comment]
well, it failing now, while adding big unicodes to the map...
and I see you already fixed some issues by trimming some values, see https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/_c_m_a_p.py#L781

**Comment by typemytype** [comment]
oke, this seems to be solved in https://github.com/typesupply/ufo2fdk/commit/79d3430420bcb053c73db7ee14a60e2e7452f2d4 and https://github.com/typesupply/ufo2fdk/commit/69dce9ab85c2ab7ad4f38842db6c4f6db6c97bec

thanks

**Comment by anthrotype** [comment]
you can't have character codes bigger than 0xFFFF in a cmap table format 4. The array which is raising the OverflowError is an array of unsigned shorts.
