### ISSUE TITLE
_f_p_g_m.__len___ calls len on ttProgram.Program

### ISSUE THREAD

**Issue by dougfelt** [behdad/fonttools#301]
This raises a TypeError.

The call that triggers this is:

if font.get('fpgm') or font.get('prep') ...

[...]
File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/ttLib/tables/_f_p_g_m.py", line 26, in __len__
TypeError: object of type 'Program' has no len()

**Comment by behdad** [comment]
cc @anthrotype

**Comment by behdad** [comment]
@dougfelt Just making sure, you called this directly, right?  Or was it called by any process (XML, compile, etc)?

**Comment by dougfelt** [comment]
I'm calling this directly from python code.  I'm using python 2.7.  The if statement is trying to see if the resulting object is 'empty' when it converts to a bool.

For now I'm working around this by comparing the result explicitly to None: "if font.get('fpgm') is not None: ..."

**Comment by anthrotype** [comment]
the code in _f_p_g_m.py that calls len(self.program) is very old. In fact the same issue occurs in the upstream fonttools as well.
I guess we can fix this by simply adding the missing `__len__` method to the ttProgram.Program class.
I'll do that.

**Comment by anthrotype** [comment]
sorry, I closed this inadvertently. @dougfelt we thought it was better to actually remove the `__len__` method completely from fpgm (and prep). We added a `__bool__` and `__nonzero__` methods so you can test the table program is not empty. Please let us know if this solves the issue.
Thanks

**Comment by dougfelt** [comment]
@anthrotype the new code works for me.
