### ISSUE TITLE
font.save() fails when trying to overwrite a loaded font

### ISSUE THREAD

**Issue by miguelsousa** [behdad/fonttools#302]
Take a look at this simple script:
```python
from fontTools import ttLib

fontFilePath = 'MyFont.otf'
font = ttLib.TTFont(fontFilePath)

font.save(fontFilePath[:-4] + '-New.otf') # this works
font.save(fontFilePath) # XXX this produces the traceback below
```
```python
Traceback (most recent call last):
  File "save.py", line 8, in <module>
    font.save(fontFilePath)
  File "/fonttools/Lib/fontTools/ttLib/__init__.py", line 214, in save
    self._writeTable(tag, writer, done)
  File "/fonttools/Lib/fontTools/ttLib/__init__.py", line 626, in _writeTable
    self._writeTable(masterTable, writer, done)
  File "/fonttools/Lib/fontTools/ttLib/__init__.py", line 629, in _writeTable
    tabledata = self.getTableData(tag)
  File "/fonttools/Lib/fontTools/ttLib/__init__.py", line 646, in getTableData
    return self.reader[tag]
  File "/fonttools/Lib/fontTools/ttLib/sfnt.py", line 92, in __getitem__
    data = entry.loadData (self.file)
  File "/fonttools/Lib/fontTools/ttLib/sfnt.py", line 373, in loadData
    assert len(data) == self.length
AssertionError
```
Am I doing something wrong?

**Comment by anthrotype** [comment]
currently it's not possible to overwrite a TTFont, because the reader's file is already open for reading, and can't be also written from the writer at the same time.
You can work around this by first making a temporary copy of the input file and then using the latter when initializing a TTFont object.
This way you can save to the original input file, since now the reader's file is different from the writer's.
There are many ways to do that. Here's one:

```python
import tempfile
import shutil

tf = tempfile.TemporaryFile()
with open(path, 'rb') as f:
    shutil.copyfileobj(f, tf)
tf.seek(0)

font = TTFont(tf)
```

**Comment by miguelsousa** [comment]
Alright, thanks for confirming and for providing a workaround.

**Comment by anthrotype** [comment]
if there's demand for it, maybe we could do something like this by default upon loading a TTFont? /cc @behdad

**Comment by behdad** [comment]
This is definitely in the right direction.  Alternatively we can just right the font into memory and wrap a stream around it.  I think I like that even better.

Note that the lazy parameter to TTFont() helps a bit with this, but I never got to implement non-lazy in sfnt.py.

**Comment by anthrotype** [comment]
I did that in PR #308.
I read the input file's content into a StringIO stream, which is then passed to the SFNTReader instead of the original file. I also keep a reference to the file's `name` attribute, in case one wants to know the name of the original file.

**Comment by behdad** [comment]
Thanks.  The name is indeed used by the bitmaps/ code that you fixed recently.

**Comment by behdad** [comment]
Right now we do a lot of conversions between file-like object and actual data.  Over time we can change all to keep reference to byte() only.

**Comment by behdad** [comment]
Another nice thing about this change is that we can now load font from unseekable streams.

**Comment by anthrotype** [comment]
Cool!
I'm leaving the input file open in case it's already a file object instead of a path string.

**Comment by miguelsousa** [comment]
Nice! Thanks guys.

**Comment by twardoch** [comment]
This is great.
