### ISSUE TITLE
[GX] GlyphVariation() expects values in normalized space

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#313]
I was expecting in user space.  Here, for example:

```
thinVar = GlyphVariation({"wght": (-1.0, -1.0, 0.0)}, thinDelta)
```

**Comment by brawer** [comment]
It’s intentional: GlyphVariation represents ‘gvar’ tuples, whose coordinates are between -1.0 and +1.0. We could change this, making the API a tad more convenient for tools that want to construct the tables. But then, the data structure wouldn't directly reflect the contents of a ‘gvar’ table anymore. (XML from Apple’s ftxdumperfuxer tool also shows what’s in the table, although that's not a very strong argument).

**Comment by brawer** [comment]
Closing for now; please re-open if you disagree.

**Comment by behdad** [comment]
So, I'm reopening because I think the current scheme is cumbersome to use.  For example, here's code I had to write to normalize the values:

```python
        # Normalize locations
        # https://github.com/behdad/fonttools/issues/313
        axis_mins = {tag:min(loc[tag] for loc in locations) for tag in axis_tags}
        axis_maxs = {tag:max(loc[tag] for loc in locations) for tag in axis_tags}
        axis_defaults = locations[0]
        for tag in axis_tags:
                minval,maxval,defaultval = axis_mins[tag],axis_maxs[tag],axis_defaults[tag]
                for l in locations:
                        v = l[tag]
                        if v == defaultval:
                                v = 0
                        elif v < defaultval:
                                v = (v - defaultval) / (defaultval - minval)
                        else:
                                v = (v - defaultval) / (maxval - defaultval)
                        l[tag] = v
        del axis_mins, axis_maxs, axis_defaults
        # Locations are normalized now
```

This should belong into fonttools IMO.

**Comment by brawer** [comment]
Yes, agree, this is indeed terrible. How about we add a method for converting user-space coordinates to the form stored in the font? Then, callers wouldn’t have to do this computation themselves, but we could still keep the data in the original form. (Preserving the original form might also help with numeric stability when round-tripping through TTX, although I haven’t thought deeply about this).

**Comment by behdad** [comment]
I don't think numerical stability is going to be an issue.  I'm not convinced that we need to provide both through the API.

**Comment by behdad** [comment]
Closing.  I'll add the converter function somewhere.
