### ISSUE TITLE
Newlines in `namerecord` do not roundtrip

### ISSUE THREAD

**Issue by mashabow** [behdad/fonttools#318]
[Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro) has DOS-style newlines (CR+LF) in its `namerecord` (`nameID`=13), but they do not roundtrip properly. It may related to #54.

1. Original: `SourceSansPro-Regular.otf`, with CR+LF
2. `$ ttx SourceSansPro-Regular.otf`: dumps to `SourceSansPro-Regular.ttx`, with CR+LF
3. `$ ttx SourceSansPro-Regular.ttx`: compiles to `SourceSansPro-Regular#1.otf`, with **LF**
4. `$ ttx SourceSansPro-Regular#1.otf`: dumps to `SourceSansPro-Regular#1.ttx`, with LF

My environment is as follows: 

- OS X 10.10.3
- Python 2.7.9
- FontTools HEAD (a54b98f445)
- Source Sans Pro 2.010

**Comment by anthrotype** [comment]
Hmm. I suspect it's the `fontTools.misc.xmlReader` which normalises the line endings while parsing the TTX file...
Thanks for reporting this. I'll investigate.

**Comment by anthrotype** [comment]
the culprit seems to be the `xml.parsers.expat module`, which reads universal newlines and translates all other line endings to Unix (`\n`) newlines. I couldn't find any option to disable this feature...

```python
>>> from xml.parsers.expat import ParserCreate
>>> parser = ParserCreate()
>>> parser.StartElementHandler = lambda name, attrs: print('Start element:', name, attrs)
>>> parser.EndElementHandler = lambda name: print('End element:', name)
>>> parser.CharacterDataHandler = lambda data: print('Character data:', repr(data))
>>> data = '<?xml version="1.0" encoding="UTF-8"?>\n<ttFont sfntVersion="\\x00\\x01\\x00\\x00" ttLibVersion="2.5">\n<test>\nhello\r\nworld\r\n</test>\n</ttFont>\n'
>>> parser.Parse(data)
Start element: ttFont {'sfntVersion': '\\x00\\x01\\x00\\x00', 'ttLibVersion': '2.5'}
Character data: '\n'
Start element: test {}
Character data: '\n'
Character data: 'hello'
Character data: '\n'
Character data: 'world'
Character data: '\n'
End element: test
Character data: '\n'
End element: ttFont
1
```

**Comment by anthrotype** [comment]
one way to fix could be converting `\r` (CR)  and `\n` (LF) to XML character entities: respectively, `&#13;` and `&#10;`. Then, the expat XML parser should keep the `\r\n` instead of automatically converting them to `\n`.
I'll try to see if I can do that.

**Comment by anthrotype** [comment]
@mashabow I submitted a patch (#327) that fixes the carriage return roundtrip issue. Please confirm this solves it for you. Thanks

**Comment by mashabow** [comment]
Thanks! Now it works well for me :+1:
