### ISSUE TITLE
Stale references to fondLib

### ISSUE THREAD

**Issue by miguelsousa** [behdad/fonttools#319]
ea1d11be18d6dace7fc5bb54e9218729f623044d removed `fondLib`, but there are still [references to it in the code and in the documentation](https://github.com/behdad/fonttools/search?utf8=%E2%9C%93&q=fondLib).

**Comment by anthrotype** [comment]
I felt a bit nostalgic deleting this... :_(

**Comment by miguelsousa** [comment]
Yeah, there was a lot of good ancient knowledge in there. I've stumbled on it because I'm actually trying to write something that has to deal with Mac Type 1 fonts.
