### ISSUE TITLE
documentation.html still points to sourceforge

### ISSUE THREAD

**Issue by Pomax** [behdad/fonttools#331]
The README.md points to https://rawgit.com/behdad/fonttools/master/Doc/documentation.html for the TTX documentation, but this still says to file issues over on http://sourceforge.net/projects/fonttools, or to email just@letterror.com

**Comment by behdad** [comment]
PR anyone?

**Comment by Pomax** [comment]
not from me, just pointing it out while working on other things atm =)

**Comment by behdad** [comment]
I was hinting at @anthrotype  ;)

**Comment by anthrotype** [comment]
I'm not sure how to phrase this. I believe it entails more than simply changing the URL to point to Github.
Maybe @davelab6 could help.

**Comment by anthrotype** [comment]
Fixed in https://github.com/behdad/fonttools/pull/359
