### ISSUE TITLE
I find the font's line height is bigger than original font.

### ISSUE THREAD

**Issue by bihicheng** [behdad/fonttools#336]
I have tried pyftsubset  with command line option --no-recalc-bounds ,
but the generated subfont's line height is still bigger than original font.

I used html font-face render font.
@font-face {
            font-family: 'freetype';
            src: url('font.ttf') format('truetype');
 }

the font file is microsoft chinese liti.ttf.

**Comment by anthrotype** [comment]
@bihicheng you were actually right about the fact that the `recalcBBoxes` parameter was ignored in the `vhea` table. I assumed it would work the same as for the `hhea` table.
Could you please try again and see if that fixes your issue?

I'm curious to know, in which browser and OS you encountered this issue with bigger line-height after recompiling the font in fonttools?

**Comment by bihicheng** [comment]
Not work. the problem is still exists. 
Maybe the vmtx table changed something.

Google Chrome	44.0.2403.130 (正式版本) m （32 位）
windows10

**Comment by anthrotype** [comment]
I'm afraid I don't have access to a windows 10 machine at the moment, so I can't replicate your bug.
When I roundtrip the "liti.ttf" with the commands:
```
$ ttx -o liti.ttx liti.ttf
$ ttx -b -o liti_new.ttf liti.ttx
$ ttx -o liti_new.ttx liti_new.ttf
```
(i.e. `-b` turns off the bounds recalculation), the difference between "liti.ttx" and "liti_new.ttx" are just the ones below.
All the reported differences are irrelevant to determining the line height, so I don't know...

```diff
8171c8171
<     <checkSumAdjustment value="0x7c3cd284"/>
---
>     <checkSumAdjustment value="0x80bb98be"/>
8176c8176
<     <modified value="Wed Oct 30 08:27:48 2002"/>
---
>     <modified value="Mon Aug 17 08:47:33 2015"/>
8205c8205
<     <numberOfHMetrics value="8159"/>
---
>     <numberOfHMetrics value="546"/>
1669350c1669350
<       Ｃｏｐｙｒｉｇｈｔ（ｃ）１９９１－１９９８，Ｃｈａｎｇｚｈｏｕ　ＳｉｎｏＴｙｐｅ　Ｔｅｃｈｎｏｌｏｇｙ　Ｃｏ．，Ｌｔｄ．　Ａｌｌ　ｒｉｇｈｔｓ　ｒｅｓｅｒｖｅｄ．　常州华文印刷新技术有限公司　版权所有　
---
>       Ｃｏｐｙｒｉｇｈｔ（ｃ）１９９１－１９９８，Ｃｈａｎｇｚｈｏｕ　ＳｉｎｏＴｙｐｅ　Ｔｅｃｈｎｏｌｏｇｙ　Ｃｏ．，Ｌｔｄ．　Ａｌｌ　ｒｉｇｈｔｓ　ｒｅｓｅｒｖｅｄ．　常州华文印刷新技术有限公司　版权所有
1669371c1669371
<       ＳｉｎｏＴｙｐｅ及华文字库是常州华文印刷新技术有限公司之商标。　
---
>       ＳｉｎｏＴｙｐｅ及华文字库是常州华文印刷新技术有限公司之商标。
1669501c1669501
<     <numberOfVMetrics value="8159"/>
---
>     <numberOfVMetrics value="1"/>

```

**Comment by anthrotype** [comment]
@bihicheng just to make sure the obvious: you are using the latest fontTools version from this Github repository, and have pulled the latest commit, right?

**Comment by bihicheng** [comment]
yes, i have pull the latest master, it's the lastest code.

I use the liti_new.ttf to render page, the result is the same as using liti.ttf.

but when i use pyftsubset command ,the subfont's render page have line-height is bigger than original font.

I use this command to generate subfont.
pyftsubset liti.ttf --no-recalc-bounds --output-file="liti_sub.ttf" --unicodes="\u592b\u4eba\u795e\u597d\u6e05\uff0c\u800c\u5fc3\u6270\u4e4b\uff1b\u6211\u4eba\u5fc3\u597d\u9759\uff0c\u800c\u6b32\u7275\u4e4b\u3002\u5e38\u80fd\u9063\u5176\u6b32\uff0c\u800c\u5fc3\u81ea\u9759\uff0c\u6f84\u5176\u5fc3\u800c\u795e\u81ea\u6e05\u3002\u81ea\u7136\u516d\u6b32\u4e0d\u751f\uff0c\u4e09\u6bd2\u6d88\u706d\u3002\u6240\u4ee5\u4e0d\u80fd\u8005\uff0c\u4e3a\u5fc3\u672a\u6f84\uff0c\u6b32\u672a\u9063\u4e5f\u3002\u4f17\u751f\u6240\u4ee5\u4e0d\u5f97\u771f\u9053\u8005\uff0c\u4e3a\u6709\u5984\u5fc3\u3002\u65e2\u6709\u5984\u5fc3\uff0c\u5373\u60ca\u5176\u795e\uff1b\u65e2\u60ca\u5176\u795e\uff0c\u5373\u8457\u4e07\u7269\uff1b\u65e2\u8457\u4e07\u7269\uff0c\u5373\u751f\u8d2a\u6c42\uff1b\u65e2\u751f\u8d2a\u6c42\uff0c\u5373\u662f\u70e6\u607c\uff1b\u70e6\u607c\u5984\u60f3\uff0c\u5fe7\u82e6\u8eab\u5fc3\uff1b\u4fbf\u906d\u6d4a\u8fb1\uff0c\u6d41\u6d6a\u751f\u6b7b\uff1b" --timing

**Comment by campbellgraphics** [comment]
Reaching here, but does the font have a vdmx table?

On Monday, August 17, 2015, bihicheng <notifications@github.com> wrote:

> yes, i have pull the latest master, it's the lastest code.
>
> I use the liti_new.ttf to render page, the result is the same as using
> liti.ttf.
>
> but when i use pyftsubset command ,the subfont's render page have
> line-height is bigger than original font.
>
> I use this command to generate subfont.
> pyftsubset liti.ttf --no-recalc-bounds --output-file="liti_sub.ttf"
> --unicodes="\u592b\u4eba\u795e\u597d\u6e05\uff0c\u800c\u5fc3\u6270\u4e4b\uff1b\u6211\u4eba\u5fc3\u597d\u9759\uff0c\u800c\u6b32\u7275\u4e4b\u3002\u5e38\u80fd\u9063\u5176\u6b32\uff0c\u800c\u5fc3\u81ea\u9759\uff0c\u6f84\u5176\u5fc3\u800c\u795e\u81ea\u6e05\u3002\u81ea\u7136\u516d\u6b32\u4e0d\u751f\uff0c\u4e09\u6bd2\u6d88\u706d\u3002\u6240\u4ee5\u4e0d\u80fd\u8005\uff0c\u4e3a\u5fc3\u672a\u6f84\uff0c\u6b32\u672a\u9063\u4e5f\u3002\u4f17\u751f\u6240\u4ee5\u4e0d\u5f97\u771f\u9053\u8005\uff0c\u4e3a\u6709\u5984\u5fc3\u3002\u65e2\u6709\u5984\u5fc3\uff0c\u5373\u60ca\u5176\u795e\uff1b\u65e2\u60ca\u5176\u795e\uff0c\u5373\u8457\u4e07\u7269\uff1b\u65e2\u8457\u4e07\u7269\uff0c\u5373\u751f\u8d2a\u6c42\uff1b\u65e2\u751f\u8d2a\u6c42\uff0c\u5373\u662f\u70e6\u607c\uff1b\u70e6\u607c\u5984\u60f3\uff0c\u5fe7\u82e6\u8eab\u5fc3\uff1b\u4fbf\u906d\u6d4a\u8fb1\uff0c\u6d41\u6d6a\u751f\u6b7b\uff1b"
> --timing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/behdad/fonttools/issues/336#issuecomment-132047236>.
>


-- 
--
Jason Campbell
jason@campbellgraphics.com
www.campbellgraphics.com
www.campbellcomics.com
Join me on Facebook: facebook.com/CampbellComics
<http://facebook.com/CampbellComics>Follow me on Twitter:
twitter.com/campbellgraphic
781-799-0457

**Comment by anthrotype** [comment]
So, I tried subsetting using the unicode string you provided and indeed I'm got the line height issue.
Then I tried to dump the UTF-8 text you attached to a file, and load that in the subsetter via `--text-file=subset.txt` option. The font subsetted using the text file (which contains all the characters you wish to display on the page) no longer shows a different line height.
So the problem appears to be the fact that the font you subsetted does not contain some of the glyph you are trying to display and therefore the fallback font kicks in, but the latter happens to have a different line height.
Please retry using a text file (or make sure you are providing all the unicode characters on the commandline) and let me know if it works.
Thanks.

```
    夫人神好清，而心扰之；
人心好静，而欲牵之。
常能遣其欲，而心自静，
澄其心而神自清。
自然六欲不生，三毒消灭。
所以不能者，为心未澄，欲未遣也。

众生所以不得真道者，为有妄心。
既有妄心，即惊其神；
既惊其神，即著万物；
既著万物，即生贪求；
既生贪求，即是烦恼；
烦恼妄想，忧苦身心；
便遭浊辱，流浪生死；
```

**Comment by bihicheng** [comment]
It works, use the --text-file option.

but --unicodes option not work. the unicodes characters is generate from python script.
<blockquote>
s=u"夫人神好清，而心扰之；我人心好静，而欲牵之。常能遣其欲，而心自静，澄其心而神自清。自然六欲不生，三毒消灭。所以不能者，为心未澄，欲未遣也。众生所以不得真道者，为有妄心。既有妄心，即惊其神；既惊其神，即著万物；既著万物，即生贪求；既生贪求，即是烦恼；烦恼妄想，忧苦身心；便遭浊辱，流浪生死；"

print s.encode('unicode_escape')
<blockquote>

**Comment by moyogo** [comment]
@bihicheng The strings are different, '我' is not in test.html and ' ' is not in the command you give. Can you try adding the space character to the command?

@campbellgraphics Nope, liti.ttf does not have a VDMX.

**Comment by anthrotype** [comment]
maybe also check that the carriage return (0x000D) character is there if you are on windows

**Comment by bihicheng** [comment]
It works, with the command option --text="  " . 
maybe the --unicodes option removed all space character.

<blockquote>pyftsubset liti.ttf --no-recalc-bounds --output-file="liti_sub.ttf" --unicodes='\u592b\u4eba\u795e\u597d\u6e05\uff0c\u800c\u5fc3\u6270\u4e4b\uff1b\u4eba\u5fc3\u597d\u9759\uff0c\u800c\u6b32\u7275\u4e4b\u3002\u5e38\u80fd\u9063\u5176\u6b32\uff0c\u800c\u5fc3\u81ea\u9759\uff0c\u6f84\u5176\u5fc3\u800c\u795e\u81ea\u6e05\u3002\u81ea\u7136\u516d\u6b32\u4e0d\u751f\uff0c\u4e09\u6bd2\u6d88\u706d\u3002\u6240\u4ee5\u4e0d\u80fd\u8005\uff0c\u4e3a\u5fc3\u672a\u6f84\uff0c\u6b32\u672a\u9063\u4e5f\u3002\u4f17\u751f\u6240\u4ee5\u4e0d\u5f97\u771f\u9053\u8005\uff0c\u4e3a\u6709\u5984\u5fc3\u3002\u65e2\u6709\u5984\u5fc3\uff0c\u5373\u60ca\u5176\u795e\uff1b\u65e2\u60ca\u5176\u795e\uff0c\u5373\u8457\u4e07\u7269\uff1b\u65e2\u8457\u4e07\u7269\uff0c\u5373\u751f\u8d2a\u6c42\uff1b\u65e2\u751f\u8d2a\u6c42\uff0c\u5373\u662f\u70e6\u607c\uff1b\u70e6\u607c\u5984\u60f3\uff0c\u5fe7\u82e6\u8eab\u5fc3\uff1b\u4fbf\u906d\u6d4a\u8fb1\uff0c\u6d41\u6d6a\u751f\u6b7b\uff1b' --text=" " --verbose 
</blockquote>

**Comment by bihicheng** [comment]
why the subfont's  line height is bigger when without the space character ? why it is so important? :)

**Comment by moyogo** [comment]
The subsetted font’s line height does not change.

Because a character shown is not in the font, your browser is getting it from a fallback font and uses the line height of the fallback font.

**Comment by anthrotype** [comment]
thank you all. I guess now we can close the issue.

**Comment by bihicheng** [comment]
'我‘ is not in the subfont, but the line height is correct.

**Comment by moyogo** [comment]
The line height is correct because 我 is in the subsetted font and it is not in your test.html.
Do the subsetting correctly and no fallback font will be used. Do it incorrectly and fallback fonts might give poor results.

**Comment by bihicheng** [comment]
I tried to remove 我 in  subfont. only 我 character is not rendered correct. the others's character is rendered correct.

**Comment by bihicheng** [comment]
thank you.
