### ISSUE TITLE
[travis] woff2_test is skipped on pypy3-2.4.0

### ISSUE THREAD

**Issue by anthrotype** [behdad/fonttools#339]
I don't know why, but the woff2_test module is being skipped on the Travis pypy3 build.
It's weird because on my mac (same pypy3-2.4.0 version) it runs the test just fine.
Somehow it fails to import brotli, hence triggering the `unittest.SkipTest` exception.
By looking at the log, pip reports it has completed the installation of the brotli module successfully...
I have no idea what's going on. Any help is appreciated.
Thanks!

https://travis-ci.org/behdad/fonttools/jobs/76367227#L1045
```
Running tests in fontTools/ttLib/woff2_test.py
skipped 'No module named brotli'
```

**Comment by khaledhosny** [comment]
You probably need to run `pip3 install -vr requirements.txt` as well to install the Python 3 version of the module.

**Comment by anthrotype** [comment]
hmm, I can try.
I thought each Travis python build would run in its own virtual environment where the meaning of `python` or `pip` commands in not ambiguous..

**Comment by anthrotype** [comment]
see https://travis-ci.org/behdad/fonttools/jobs/76367227#L205
it seems pip is indeed using the correct python interpreter

**Comment by khaledhosny** [comment]
Right, no idea then. Try something like `python -v -c "import brotli"` to see why it is failing to import it.

**Comment by anthrotype** [comment]
thanks for your help Khaled..
No idea why it says that.

https://travis-ci.org/behdad/fonttools/jobs/76375103#L262
```
$ python -v -c "import brotli"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: unable to load extension module '/home/travis/virtualenv/pypy3-2.4.0/site-packages/brotli.pypy3-24.so': /home/travis/virtualenv/pypy3-2.4.0/site-packages/brotli.pypy3-24.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
The command "python -v -c "import brotli"" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by anthrotype** [comment]
I wonder if it might be related to this issue:
https://bitbucket.org/pypy/pypy/issues/1099/distutils-not-correctly-using-g-cplusplus

**Comment by anthrotype** [comment]
on pypy (Python 2), the command `c++` is used for the linking stage: 
https://travis-ci.org/behdad/fonttools/jobs/76375102#L242

on pypy3, it is `cc`:
https://travis-ci.org/behdad/fonttools/jobs/76375103#L242

I wonder if there's a way to override this from distutils.

**Comment by anthrotype** [comment]
I believe this is the issue:
https://bitbucket.org/pypy/pypy/issues/1763/not-using-proper-c-compilers-linker-while

I don't know what to do. I don't want spend time fixing distutils for pypy3. I think we should live with woff2_test being skipped on pypy3, at least until pypy devs sort this out.

**Comment by anthrotype** [comment]
Since we dropped support for Python 3.2, why don't we also drop it for PyPy3-2.4.0 (which implements Python 3.2.5)?
Just saying.

**Comment by anthrotype** [comment]
This seems to fix the C++ linking issue:
https://bitbucket.org/pypy/pypy/commits/c6e45dfbda905fa9e626782c8d2dd313ff3f54cf

I verified on my local Ubuntu virtual machine and it works. However, the patch hasn't been applied to pypy3 yet.

I couldn't find a way to override this compiler_cxx variable by means of environment variables (neither CXX nor CC seem to work).

I'll probably send a PR to google/brotli to have the setup.py monkey-patch distutils so that IT uses "c++" as compiler_cxx to when running on pypy3.

**Comment by anthrotype** [comment]
I found that if I explicitly link libstc++, then brotli can be imported in pypy3

```
python setup.py build_ext --libraries=stdc++
```

Maybe this could be a better temporary solution than monkeypatching distutils (which should really be fixed in pypy3 lib-python).
