### ISSUE TITLE
how to convert cmap format2 to cmap format4 or add format4 cmap table ?

### ISSUE THREAD

**Issue by bihicheng** [behdad/fonttools#340]
any suggestions ?

**Comment by behdad** [comment]
See snippet.

**Comment by bihicheng** [comment]
thanks.

**Comment by bihicheng** [comment]
It's very good, I have convert an legacy font file to a unicode font file and it's rendered correctly  in chrome browser just now

**Comment by behdad** [comment]
Did you have to modify the script to do character set conversion?  If yes, can you contribute your modifications back?  Thanks.

**Comment by bihicheng** [comment]
@behdad  Yes, I convert gbk codepoint to utf8 codepoint.
I will commit the codes in a few days.

**Comment by behdad** [comment]
https://github.com/behdad/fonttools/pull/346
