### ISSUE TITLE
ttf2svg, ttf2eot feature request

### ISSUE THREAD

**Issue by bihicheng** [behdad/fonttools#345]

**Comment by anthrotype** [comment]
it's on our to-do list.
For EOT, you can use [sfntly](https://github.com/googlei18n/sfntly), a library for editing sfnt-based fonts written in Java. It comes with a command-line tool `sfnttool.jar` which can convert TTF fonts to EOT, using Monotype-patented "MicroType Express" (MTX) compression technology.

Sample usage:
```
$ java -jar sfnttool.jar -e -x input-font.ttf output-font.eot
```

**Comment by bihicheng** [comment]
thank you @anthrotype
