### ISSUE TITLE
kochi gothic fails to decode

### ISSUE THREAD

**Issue by cary-clark** [behdad/fonttools#347]
Tools/ttx kochi-gothic.ttf    fails.

Ubuntu 14.04  x86_64

details:

$./Tools/ttx -o kochi-gothic.xml /usr/share/fonts/truetype/kochi/kochi-gothic.ttf 
Dumping "/usr/share/fonts/truetype/kochi/kochi-gothic.ttf" to "kochi-gothic.xml"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Traceback (most recent call last):
  File "./Tools/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "./Tools/fontTools/ttx.py", line 350, in main
    process(jobs, options)
  File "./Tools/fontTools/ttx.py", line 333, in process
    action(input, output, options)
  File "./Tools/fontTools/ttx.py", line 231, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "./Tools/fontTools/ttLib/__init__.py", line 304, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "./Tools/fontTools/ttLib/__init__.py", line 342, in _tableToXML
    table.toXML(writer, self, progress)
  File ",/Tools/fontTools/ttLib/tables/_g_l_y_f.py", line 124, in toXML
    glyph.toXML(writer, ttFont)
  File "./Tools/fontTools/ttLib/tables/_g_l_y_f.py", line 357, in toXML
    self.program.toXML(writer, ttFont)
  File "./Tools/fontTools/ttLib/tables/ttProgram.py", line 228, in toXML
    assembly = self.getAssembly()
  File "./Tools/fontTools/ttLib/tables/ttProgram.py", line 223, in getAssembly
    self._disassemble(preserve=preserve)
  File "./Tools/fontTools/ttLib/tables/ttProgram.py", line 418, in _disassemble
    value = bytecode[i]
IndexError: array index out of range

$fc-query /usr/share/fonts/truetype/kochi/kochi-gothic.ttf 
Pattern has 22 elts (size 32)
	family: "Kochi Gothic"(s) "東風ゴシック"(s)
	familylang: "en"(s) "ja"(s)
	style: "Regular"(s) "標準"(s)
	stylelang: "en"(s) "ja"(s)
	fullname: "Kochi Gothic"(s) "東風ゴシック"(s)
	fullnamelang: "en"(s) "ja"(s)
	slant: 0(i)(s)
	weight: 80(i)(s)
	width: 100(i)(s)
	foundry: "unknown"(s)
	file: "/usr/share/fonts/truetype/kochi/kochi-gothic.ttf"(s)
	index: 0(i)(s)
	outline: True(s)
	scalable: True(s)
	charset: 
	0000: 00000000 ffffffff ffffffff 7fffffff 00000000 ffffffff ffffffff ffffffff
	0001: ffffffff ffffffff ffffffff ffffffff 00040000 00000000 1fffe000 fc200000
	0002: 00000000 00000000 ffff0000 ffffffff ffffffff 000001ff 3f0002c0 00000000
	0003: 00000000 00000000 00000000 00000000 fffe0000 fffffffb 00007fff 00000000
	0004: ffffdffe ffffffff 0002ffff 00000000 00000000 00000000 00000000 00000000
	001e: 00000000 00000000 00000000 00000000 0000003f 00000000 00000000 000c0000
	0020: ffffffff ffff7fff 0000007f fff10000 00007fff 000007ff 00000000 00000000
	0021: ffffffff 01ffffff fff80000 ffffffff ffff0007 ffffffff ffffffff 000007ff
	0022: ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff ffffffff 0003ffff
	0023: 00050004 00000003 00000000 00000000 00000000 00000000 00000000 00000000
	0024: 00000000 00000000 00000000 ffffffff ffffffff ffffffff ffffffff 000007ff
	0025: ffffffff ffffffff ffffffff ffffffff 003fffff ffffffff ffffffff 0000ffff
	0026: fc0fffff ffffffff ffffffff 0000ffff 00000000 00000000 00000000 00000000
	0027: fffff3de fffffeff 7f47afff ffc000fe ff1fffff 7ffeffff 00000000 00000000
	0030: ffffffff 00ff0001 fffffffe ffffffff 781fffff fffffffe ffffffff 7fffffff
	0032: 00000000 ffffffff 0000000f 00000000 ffffffff 0001ffff ffff0fff 7fffffff
	0033: ffffffff ffffffff ffffffff f87fffff ffffffff ffffffff 3fffffff 7fffffff
	004e: c3f77fbf 9b67ed5a f7e2e8bf c23a030c fbf67f65 0649f977 eff1ecdf e8efe13f
	004f: 36e7ff0f 7ffbc000 fffffbcd ffebd609 efdfff7e fae4e803 bd97ff7f f56dc03f
	0050: ffdffef3 0a6d7ffe 96efd7ef 217734ed df5fe47b 66bdb407 f57bf6bd 4e66e3fc
	0051: fff57bdf 9fbeb58a 95bdffff 51e27f74 23effe7d f5ff3f7f 796ebb74 67ff66e7
	0052: 21fe4dff 1fef47b4 ddf0beb8 a3bfc67b 9dfe37ad 7ff3bef9 fbf6b3fb c7ff17ff
	0053: ffebbd6f ff2fbfab 5f9e3fef cbbff26b a758419c 2dfdef73 eefcff2d 05efffff
	0054: ac0bff1e 7b72ffc3 c002e7dd b8fb6fd4 9067fb7b ff8efff6 010067d7 f444f767
	0055: 0071f3f3 7b6ecc00 7dcbb6f3 d800005b f79ecfdf 80457f98 dd9e5afa e2c0021c
	0056: 0bd7e760 bbff9200 4811fa5f 0536bf5f e6309df1 50da7be5 ff8bff2f a6cf69fb
	0057: bd6ebf9f e999f7fd 0007f4e5 debbeff6 f6b81b0e 2109179f f07cd9c9 f7f122db
	0058: ea203f7d a637a4d3 c7b7be03 d3250b96 b0d9b7ab 5f0e4b47 f7ff75b6 3e8fda36
	0059: 3f7d9e64 c1efffbe efbfc3d8 3b7cffaf aaec7c1e 5e8df1b8 f61f2f5a 88d6cdf8
	005a: d50e721b 1061a7b9 442113f3 cc8034ec de4d0800 fd2e1085 14c19b56 2c60466b
	005b: 2ac01b03 41553426 fdf7182b f52bcb78 bffbfffb 97fff37c efddb2ff e57bcbf7
	005c: c4cafff6 ff677b5d 562bed63 3e73f3bf a0179580 5dfe1f4f 22840aa0 2c57e703
	005d: 8ff668c2 a2120adc 92275d4c c649b617 aa3d1d9e 37955885 6b4d7a88 6bbe4bfb
	005e: af7638cd 61ede921 d9f35ab9 ff7d7d1e 14e0cc9b e1ea3df5 fc7fdf4e dddb1b2f
	005f: bbfbffde f9f3fbfe 3bdb75b3 f7bfbedf 73cfbfbf 331bff97 73df3bb8 bd6fff17
	0060: bffde480 042aaff3 a6f73fcf c0a3bfbf edfe7f5e 79ff07fd ff3acff4 3fff01af
	0061: defff7cf f2f31d86 e7287ff6 d9ffd9ad b7df6c9f 57447fb1 f021ffcf f5d4b2ee
	0062: fc7f779b ab1dcecf 5d7f7bdf f64ae119 59ffe61d feea1940 3ffff7f4 f0fef403
	0063: 834b3f9e f660af80 19bdfe5e bdf67be0 cf75d79d 6834ffff 1c7fc37b 077c562b
	0064: 51dda640 e471b775 bd1ec804 2d58a28b ef2f81a8 fa0d7b7a 05b77eb6 ecf7b6ff
	0065: fb588733 fff2de5c e3f7a3a8 25b518cd bba757ae b29df8fb 8bd5db7e ce3733e7
	0066: f07ef7dd 92fbffff fb86de7f dff9dfd7 bfc77b9b db366855 be50d39f ffbd5b41
	0067: faf8eba9 e5da7dc5 f27bd3e2 d8fff47f 3febdab2 3bff8247 779fc77f caffd2d6
	0068: e2d8001c bb1fbf86 bbbf757f def7c888 bdd8a17e 1e6fe7ef b7ffbf70 3e67fdab
	0069: 1ecfff73 ab7b056e 7eb84624 ffbfff7f 19766407 dd96e9e3 63cb7daa ea2ee9a4
	006a: eebe9c2f eff54f1f 8b674ff0 c10e04d6 f8836adb e91bdc2d fc7b134e 3c071590
	006b: e8c786fc efe4999b ab5d76c8 eb39cedf c9e02e7d ffbfff1d 8d5c7a79 828ad8ca
	006c: 8a9fe334 cdf851d8 feb5ec07 6f5dad85 9ffd33ee ff1f4806 3effb676 001fdfaf
	006d: ce8edc90 fb6ecfe0 d6800032 1391d6fa 1bfe51a4 b3b49400 eb66ddf1 1efbdf77
	006e: ee280fb1 5f44faff f9deef38 e84cc98c b349b005 accee4a5 603affbf eb94f800
	006f: 0d7ab756 d94fbe4d ff9e8022 7511f156 84df79df 126bc5fb cd3005ef 766bdb13
	0070: eda2aae3 529590c9 61325f18 7161d838 0bf44662 079bf810 b37a8d00 26020010
	0071: 56109af8 1143a843 56e55ee2 220053f5 8e3495b1 c60f9105 96fd5b1b db2070e1
	0072: ac8923c1 ff75bd10 ff6dd9ef fb96cb8f 084c6297 4256f185 8be552de 7f983227
	0073: fbcc2cb4 ecf6dfb4 e1c5e038 1fa7dfc9 d1e94afb baac2e65 624cff65 efb266eb
	0074: 0c0206fb 867fff74 fea628db 404fefdd d7078aeb aa27cfcf dd199700 9dd7cfdd
	0075: d5ee7078 ffcf9ffb fe97ffd9 ffdbaef7 363fcee6 f73e083c dbb4f4ff d61fd29f
	0076: fa6cbf9f 1f3d22ff 93641fff 7d57f7b6 be6979fb a79165fd dad47f6e 5b5755fb
	0077: deb45fd3 77f0e375 dcc4e4e5 e61d1dff c4727811 fa6bf4a5 dea62288 191bf6fd
	0078: 20367264 84b560ef 700451b8 5414dd1b e5baf4c2 fc2fb79a 8c7f5fe2 acdc95d3
	0079: d60750c3 fc323ee1 fdfb8ff3 de842ba5 397afc33 ef1bcfc2 e5768f97 19033eff
	007a: dfb27f8d ffb7e883 b2e1f3fd e7712eaf c1ff0d7f 9e69d609 be2efff8 ef53bf6f
	007b: cb128dd4 a27bffe9 2077fbe3 04bff6f1 fff7ead0 3d77b423 2ed09ff7 57fc2771
	007c: 8a9efadf e7da1deb ff7fb449 722d72bb c9b5aace fecf69f7 f7fce7b5 4d748ac5
	007d: 7fffaffd f62ffc4f 7ecbf9ff af6f45ee fecabb6e effffccc 77a6fcfc 0e76bf77
	007e: f8a70f33 eeeef9cf e7756cfa fb09eee6 7d7ff7ce 00000000 00000000 00000000
	007f: 00000000 fd400000 b93ff0b8 e3a76ffb 74d3fded b354e75e 8834d56b fe0ddb6b
	0080: f3fffdfb fef95153 c5440451 e2ffa157 7d485bf2 0716bee6 6ff4f158 775fe033
	0081: 5dc00fec 562b9299 80bf5ce0 8793ebe3 7d69cd7f ed3d431d efaaef6d ff7f3dbb
	0082: ffddf7af 07fc5f06 b742c8f9 e9d6eddd af566e9b ff9ffffb debf0060 6edaadff
	0083: f9c04fff 37fff90e 01ffe6bd b9a90000 ff7c66f5 e0223fc5 b15bd6a3 3bd78f01
	0084: 022afcda 33229605 1fc6e7e0 37fbfeff d23d0836 ff16a742 164bbfd7 bc97d480
	0085: d5bb50cd a07cbcfe f7efcf4b ee80af1f bb9b9ff3 f7d0fff5 b521ee86 dec82771
	0086: 4fcf6cf5 b541a286 f7fd6047 0ee29a9f 156a3d00 83fbafda deb66afb 7f00f2b9
	0087: d71feffd fe96c32a a3a87a29 8956c57b c3a93bfc ec2af88d 96654fd3 cfceac1d
	0088: df7fee6a 1e67618e ffee7f7f eaa70b1f dfc42907 e4b34d15 fb3efc3f 73bf8182
	0089: 776df4d6 4f670de1 dcc4b27f fcbdec5f 9df9afca b4fd96e3 35f40001 a35a2ae8
	008a: e9ffd5bd 7cfabc7d 79ff63eb deef7aef c7efbafd dacdf3fb fcfebfdc d5fb78d7
	008b: fed35cf7 52893943 df5cf37e 73d7b848 d67dfc3b 00000000 00000000 00000000
	008c: 00000000 e7800000 2fbbdfe2 5f683f5e 7b1d7ee4 bfddff97 7e6aefff fda5b55f
	008d: 08ddafba 00000000 00000000 809b7af0 c2232536 5eac9949 aef2dde5 b03f9dba
	008e: e0538f72 23fb04cf fa31ff97 1e57b21f 6e3f2ebe 4c2bfe86 9816bdfb 7f83690c
	008f: fbfd97ad cff8f7eb f1bef2ff 0000003e f8000000 dde7e1fb 043f6c77 6ff3ef7d
	0090: effbf97f d3fef78f 7b7ffebe b7f5f3ef 0ba3dfbf 617f856f bba455ba e0f1a936
	0091: 57d52175 36d7e2ad 0fdcff88 0fbc36be 51bf6eee bd7ffd56 ffdbfbef bae3f6fa
	0092: 717f76f3 d7f9d378 7f83effd fbe3c3f7 9fee6729 bfc4a9b1 b3adf9ef 9f0d77bb
	0093: f733a145 0cfcdfff 5df72b90 f47bf6b1 4df4bd07 06717bda f3cb3ffa 2f8001f6
	0094: 87f9e39e ad7ec802 de2e153a f0a7ed0f 0000001a 00000000 00000000 00000000
	0095: 00000000 00000000 00000000 43800000 e35aff9d fe543bff f77f3fc8 00000077
	0096: 70000000 bf8ed576 f9d5b817 fdfd547e bff2ef7e 1fdfc7f9 ff667ef3 0ec78f0c
	0097: 7e4ae7fd 630f059e 5fe4c75e bfda6fdf d7e1aa73 d77e794d 7b9b7ffa 8dfee013
	0098: 57dff5ee 79bdf87b 4ffefcd0 001b9cec 00000000 8dd3ed00 9800117c 705ceeee
	0099: fdff17ac 7e3e59d7 dbb77be7 00000001 abc00000 b63f7160 ff3f037a eb377c84
	009a: 424fd83e 41e9699d acf27cbf 00000e34 00000000 db75f500 d9ffc15b aebefefd
	009b: 9f457b7f 3ebeefed 4df2f93e 83b8fd6a e4dfeef9 db977fc1 a9d7c7c3 a7af8dbe
	009c: 5f7fbf55 6ee7e7fe fdddc7fa 09e54f89 00000000 00000000 00000000 02dd1ae0
	009d: f9a64bcc fc1d9d48 f21b05fe 5cc59e3f 05ece6d8 9f36de12 c6f886de 671deae1
	009e: 7e674484 00000000 00000000 bf200000 e9eed9bf df39f770 fb35f950 bbf7f1b1
	009f: 8effc38c fe969c47 e5fcccfa 24eff7cf 70f7a000 0000002f 00000000 00000000
	00f9: 00000000 00000200 00000000 00000000 00000000 00000000 10000000 00000000
	00fa: ffffc000 00003fff 00000000 00000000 00000000 00000000 00000000 00000000
	00fb: 00000006 00000000 00000000 00000000 00000000 00000000 00000000 00000000
	00ff: fffffffe ffffffff 7fffffff fffffffe ffffffff 00000000 00000000 00007f3f
(s)
	lang: aa|af|av|ay|bg|bi|br|bs|ca|ce|ch|co|cs|cy|da|de|en|eo|es|et|eu|fi|fj|fo|fr|fur|fy|gd|gl|gv|ho|hr|hu|ia|id|ie|io|is|it|ja|ki|kl|kum|la|lb|lez|lt|lv|mg|mh|mt|nb|nds|nl|nn|no|nr|nso|ny|oc|om|os|pl|pt|rm|ru|se|sel|sk|sl|sma|smj|smn|so|sq|ss|st|sv|sw|tk|tl|tn|tr|ts|uz|vo|vot|wa|wen|wo|xh|yap|zu|an|crh|csb|fil|hsb|ht|jv|kj|ku-tr|kwm|lg|li|ms|na|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za(s)
	fontversion: 0(i)(s)
	capability: "otlayout:kana"(s)
	fontformat: "TrueType"(s)
	decorative: False(s)
	hash: "sha256:892e1ea6c0be6852c64fa4665f8d80bc9a9ca20136c94009026bd7ca23f25d95"(s)
	postscriptname: "Kochi-Gothic"(s)

**Comment by cary-clark** [comment]
Using the -i option succeeds. That may be a good enough workaround for my use case.

**Comment by anthrotype** [comment]
this appears to be an issue with the font's hinting rather than in fontTools' bytecode disassembler.

**Comment by anthrotype** [comment]
Yes, it's a font bug.
Also Microsoft VTT cannot decompile the same glyph 492 ('sigma1'):
```
Glyph ID 492
Critical Error: Inst: SHP[rp1,zp0] Stack Underflow.
```

**Comment by cary-clark** [comment]
Please reconsider before closing this bug. 

The tool could be permitted to read and write erroneous font tables in the case where there is no modification to the table in question. It makes sense that the tool is unable to represent erroneous table data in a meaningful way, and that it warrants returning an error if the user requires font validation.

When the use case is only to edit valid font tables, the remaining tables should be written exactly as they were read, errors and all.

**Comment by anthrotype** [comment]
ok so, in this case, you would like the entire glyf table to not be decompiled (i.e. dumped as raw hex) when the TT program in one of its glyph is invalid. Correct?

**Comment by cary-clark** [comment]
Yes, that sounds fine -- as long as fontTools can read the raw hex back in
again.

**Comment by anthrotype** [comment]
Actually we can simply skip decompilation of the specific glyph program which is failing, and dump that as bytecode while also printing a warning, without needing to skip decompiling the rest of valid glyph programs. Maybe it's a good idea to also write the error message as an XML comment in the dumped TTX file. I'll send a patch soon.
I'd be curious to know why exactly that specific glyph 492 instructions are faulty..
Anyway, thanks for reporting this bug!
