### ISSUE TITLE
wqy-microhei.ttc part 1 fails round trip

### ISSUE THREAD

**Issue by cary-clark** [behdad/fonttools#348]
Converting wqy-microhei.ttc to xml and back fails.

Ubuntu 14.04 x86_64

Details:

$./Tools/ttx -y 1 -i -o test.xml /usr/share/fonts/truetype/wqy/wqy-microhei.ttc 
Dumping "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc" to "test.xml"...
Dumping 'GlyphOrder' table...
Dumping 'head' table...
Dumping 'hhea' table...
Dumping 'maxp' table...
Dumping 'OS/2' table...
Dumping 'hmtx' table...
Dumping 'cmap' table...
Dumping 'fpgm' table...
Dumping 'prep' table...
Dumping 'cvt ' table...
Dumping 'loca' table...
Dumping 'glyf' table...
Dumping 'name' table...
Dumping 'post' table...
Dumping 'gasp' table...
Dumping 'FFTM' table...
Dumping 'GDEF' table...
Dumping 'GPOS' table...
Dumping 'GSUB' table...
Dumping 'vhea' table...
Dumping 'vmtx' table...

$./Tools/ttx -o test.ttf test.xml
Compiling "test.xml" to "test.ttf"...
Parsing 'GlyphOrder' table...
Parsing 'head' table...
Parsing 'hhea' table...
Parsing 'maxp' table...
Parsing 'OS/2' table...
Parsing 'hmtx' table...
Parsing 'cmap' table...
Parsing 'fpgm' table...
Parsing 'prep' table...
Parsing 'cvt ' table...
Parsing 'loca' table...
Parsing 'glyf' table...
Parsing 'name' table...
Parsing 'post' table...
Parsing 'gasp' table...
Parsing 'FFTM' table...
Parsing 'GDEF' table...
Parsing 'GPOS' table...
Parsing 'GSUB' table...
Parsing 'vhea' table...
Parsing 'vmtx' table...
Traceback (most recent call last):
  File "./Tools/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "./Tools/fontTools/ttx.py", line 350, in main
    process(jobs, options)
  File "./Tools/fontTools/ttx.py", line 333, in process
    action(input, output, options)
  File "./Tools/fontTools/ttx.py", line 249, in ttCompile
    ttf.save(output)
  File "./Tools/fontTools/ttLib/__init__.py", line 221, in save
    self._writeTable(tag, writer, done)
  File ".tTools/ttLib/__init__.py", line 653, in _writeTable
    tabledata = self.getTableData(tag)
  File "./Tools/fontTools/ttLib/__init__.py", line 666, in getTableData
    return self.tables[tag].compile(self)
  File "./Tools/fontTools/ttLib/tables/_p_o_s_t.py", line 51, in compile
    data = data + self.encode_format_2_0(ttFont)
  File "./Tools/fontTools/ttLib/tables/_p_o_s_t.py", line 174, in encode_format_2_0
    assert index < 32768, "Too many glyph names for 'post' table format 2"
AssertionError: Too many glyph names for 'post' table format 2

**Comment by cary-clark** [comment]
Part 0, e.g.

$./Tools/ttx -y 0 -i -o test.xml /usr/share/fonts/truetype/wqy/wqy-microhei.ttc 
$./Tools/ttx -o test.ttf test.xml

fails the same way.

**Comment by cary-clark** [comment]
Next tried removing some or al of the <post> contents, but that didn't help.
Removing the entire <post> table works -- I'll see if I can live without it.

**Comment by anthrotype** [comment]
there seems to be difference between Microsoft's OpenType spec and Apple's TrueType spec as regards the `post` table format 2.0. In the latter:

> index numbers 32768 through 65535 are reserved for future use.

whereas in the OT spec, numbers up 65535 are allowed.

FontTools follows Apple in this regard and asserts that the index is not greater than 32767:
https://github.com/behdad/fonttools/commit/69ef79b5

I have raised the question in the OpenType mailing list.

**Comment by anthrotype** [comment]
There another, now closed, issue https://github.com/behdad/fonttools/issues/124 which may be related to the current one. Perhaps @behdad or @olivierberten know what should be done in this case.

**Comment by behdad** [comment]
I believe we should update to reflect OT spec.  The limit to 32k doesn't make sense to me.

**Comment by anthrotype** [comment]
So this time Microsoft has it right. We shall update the post table module to allow up to 65535.
Here's Bob Hallissy in the OpenType mailong list:

> the third (2015) edition of ISO/IEC 14496-22 "Open 
Font Format" increased the limit from 32767 to 65535 (and thus 
eliminated the reserved numbers).
> Microsoft has keep their specifications in sync with ISO/IEC, which is 
why their 1.7 spec includes this larger limit.

**Comment by anthrotype** [comment]
@cary-clark I removed the limit and verified that post table in wqy-microhei.ttc now roundtrips correctly.
thanks for reporting the issue.
