### ISSUE TITLE
Support for "trak" table?

### ISSUE THREAD

**Issue by jenskutilek** [behdad/fonttools#375]
Are there any plans to support the "trak" table?

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6trak.html

I could use it right now, and it doesn't look too complicated, but at the moment I don't find the time to implement it myself.

**Comment by anthrotype** [comment]
Yes, I'm working on it. I should have something by the end of the week hopefully.

**Comment by anthrotype** [comment]
@jenskutilek
How about something like that for the XML representation?
The data is taken from San Francisco Text Regular.

```xml
<trak>
	<version value="1.0"/>
	<format value="0"/>
	<horizData>
		<!-- nTraks=2, nSizes=20 -->
		<TrackTableEntry track="-1.0" nameIndex="291">
			<tracking size="6.0" value="82"/>
			<tracking size="9.0" value="38"/>
			<tracking size="10.0" value="24"/>
			<tracking size="11.0" value="12"/>
			<tracking size="12.0" value="0"/>
			<tracking size="13.0" value="-12"/>
			<tracking size="14.0" value="-22"/>
			<tracking size="15.0" value="-32"/>
			<tracking size="16.0" value="-40"/>
			<tracking size="17.0" value="-47"/>
			<tracking size="20.0" value="-55"/>
			<tracking size="22.0" value="-60"/>
			<tracking size="28.0" value="-66"/>
			<tracking size="32.0" value="-68"/>
			<tracking size="36.0" value="-70"/>
			<tracking size="50.0" value="-78"/>
			<tracking size="64.0" value="-86"/>
			<tracking size="80.0" value="-92"/>
			<tracking size="100.0" value="-92"/>
			<tracking size="138.0" value="-92"/>
		</TrackTableEntry>
		<TrackTableEntry track="0.0" nameIndex="290">
			<tracking size="6.0" value="54"/>
			<tracking size="9.0" value="10"/>
			<tracking size="10.0" value="-4"/>
			<tracking size="11.0" value="-16"/>
			<tracking size="12.0" value="-28"/>
			<tracking size="13.0" value="-40"/>
			<tracking size="14.0" value="-50"/>
			<tracking size="15.0" value="-60"/>
			<tracking size="16.0" value="-68"/>
			<tracking size="17.0" value="-75"/>
			<tracking size="20.0" value="-83"/>
			<tracking size="22.0" value="-88"/>
			<tracking size="28.0" value="-94"/>
			<tracking size="32.0" value="-96"/>
			<tracking size="36.0" value="-98"/>
			<tracking size="50.0" value="-106"/>
			<tracking size="64.0" value="-114"/>
			<tracking size="80.0" value="-120"/>
			<tracking size="100.0" value="-120"/>
			<tracking size="138.0" value="-120"/>
		</TrackTableEntry>
	</horizData>
</trak>
```

**Comment by moyogo** [comment]
*Fonts and Encoding*, page 843, shows the following example:
```xml
<trak>
  <Version value="1"/>
  <tracking format="0">
    <horizData>
      <!-- nTracks=3 -->
      <trackEntry index="0" value="-" nameIndex="15">
        <!-- nSizes=2 -->
          <track size="12" value="-"/>
          <track size="24" value="-"/>
      </trackEntry>
      <trackEntry index="1" value="0" nameIndex="16">
        <!-- nSizes=2 -->
          <track size="12" value="0"/>
          <track size="24" value="0"/>
      </trackEntry>
      <trackEntry index="2" value="1" nameIndex="17">
        <!-- nSizes=2 -->
          <track size="12" value="50"/>
          <track size="24" value="20"/>
      </trackEntry>
    </horizData>
    <vertData>
      <!-- nTracks=0 -->
    </vertData>
  </tracking>
</trak>
```

**Comment by anthrotype** [comment]
Thanks Denis! I forgot about that one.
I'll follow Haralambous then.

**Comment by jenskutilek** [comment]
Looks good to me!

I wondered a moment about the minus symbols in the XML code, but then remembered that it's a "bug" in Fonts and Encodings, English edition, that all negative numbers are shown just as a minus symbol ;)

Do we really need the index attribute in the trackEntry element? The index could be inferred from the order of trackEntry elements in the XML code.

**Comment by anthrotype** [comment]
yes, the "-" is indeed a typo. I also think the index can be simply inferred from the entries' order.

**Comment by moyogo** [comment]
I'll check what is in the French edition.

**Comment by jenskutilek** [comment]
```xml
      <trackEntry index="0" value="-1" nameIndex="15">
```

The first minus value has to be -1 (tight tracking).

**Comment by moyogo** [comment]
Indeed. Here’s the example in the French edition:
```xml
<trak>
  <Version value="1"/>
  <tracking format="0">
    <horizData>
      <!-- nTracks=3 -->
      <trackEntry index="0" value="-1" nameIndex="15">
        <!-- nSizes=2 -->
          <track size="12" value="-15"/>
          <track size="24" value="-7"/>
      </trackEntry>
      <trackEntry index="1" value="0" nameIndex="16">
        <!-- nSizes=2 -->
          <track size="12" value="0"/>
          <track size="24" value="0"/>
      </trackEntry>
      <trackEntry index="2" value="1" nameIndex="17">
        <!-- nSizes=2 -->
          <track size="12" value="50"/>
          <track size="24" value="20"/>
      </trackEntry>
    </horizData>
    <vertData>
      <!-- nTracks=0 -->
    </vertData>
  </tracking>
</trak>
```

**Comment by anthrotype** [comment]
I'm not sure whether to use the name `TrackTableEntry` (from the spec) or `TrackEntry` (from Haralambous). Admittedly, the latter is shorter, but conformance with the spec's names is also good. WDYT?

**Comment by anthrotype** [comment]
also, `nSizes` belongs to the `TrackData` structure (i.e. either `horizData` or `vertData`), not to the individual `TrackTableEntry` records. So the XML comment referring to `nSizes` should be put on the same line as `nTracks`.
This also means that each "track" must have the same number of sizes.
Am I correct?

**Comment by jenskutilek** [comment]
I'd go with the spec names.

Correct, each track must have the same number of size entries.

**Comment by behdad** [comment]
I wouldn't worry too much about matching Haralambous.  Also, I prefer if this can be neatly done using the otData machinery as opposed to open-coding.  But not at the expense of ugly API / output.  Thanks!

**Comment by anthrotype** [comment]
Behdad, I tried to use the otData machinery, but the trak table format does not seem to fit the model..
At least, I couldn't make it work. So I'm doing it in the traditional way.

This is how Skia, for example, looks like so far:

```xml
<!-- Skia -->
<trak>
  <version value="1.0"/>
  <format value="0"/>
  <horizData>
    <!-- nTracks="3", nSizes="5" -->
    <sizeTable>
      <size index="0" value="9.0"/>
      <size index="1" value="10.0"/>
      <size index="2" value="12.0"/>
      <size index="3" value="18.0"/>
      <size index="4" value="19.0"/>
    </sizeTable>
    <trackTable>
      <trackEntry index="0" value="-1.0" nameIndex="275">
        <track index="0" value="-10"/><!-- size="9.0" -->
        <track index="1" value="-30"/><!-- size="10.0" -->
        <track index="2" value="-60"/><!-- size="12.0" -->
        <track index="3" value="-63"/><!-- size="18.0" -->
        <track index="4" value="-63"/><!-- size="19.0" -->
      </trackEntry>
      <trackEntry index="1" value="0.0" nameIndex="303">
        <track index="0" value="15"/><!-- size="9.0" -->
        <track index="1" value="0"/><!-- size="10.0" -->
        <track index="2" value="-5"/><!-- size="12.0" -->
        <track index="3" value="-25"/><!-- size="18.0" -->
        <track index="4" value="-25"/><!-- size="19.0" -->
      </trackEntry>
      <trackEntry index="2" value="1.0" nameIndex="276">
        <track index="0" value="140"/><!-- size="9.0" -->
        <track index="1" value="130"/><!-- size="10.0" -->
        <track index="2" value="125"/><!-- size="12.0" -->
        <track index="3" value="115"/><!-- size="18.0" -->
        <track index="4" value="115"/><!-- size="19.0" -->
      </trackEntry>
    </trackTable>
  </horizData>
  <vertData>
    <!-- nTracks=0, nSizes=0 -->
  </vertData>
</trak>
```

**Comment by anthrotype** [comment]
I decided to not use dictionaries for storing tracking values keyed by size; instead, I store the sizes in a separate `sizeTable` list and map each tracking value to the respective size by index (of course, after making sure the arrays have the same length).
This is to avoid duplicating data, or having entries with different dictionary (size) keys -- which is not possible for trak.
That's why in the XML I write the sizes as comments, next to the relevant tracking value.
I hope that makes sense.

Here's how the Python objects are structured:
```python

SKIA_TRAK_TABLE = {
	'tableTag': 'trak',
	'version': 1.0,
	'format': 0,
	'horizData': TrackData(
		sizeTable=[9.0, 10.0, 12.0, 18.0, 19.0],
		trackTable=[
			TrackTableEntry(track=-1.0, nameIndex=275, values=[-10, -30, -60, -63, -63]),
			TrackTableEntry(track=0.0, nameIndex=303, values=[15, 0, -5, -25, -25]),
			TrackTableEntry(track=1.0, nameIndex=276, values=[140, 130, 125, 115, 115])
			]
		),
	'vertData': TrackData(sizeTable=[], trackTable=[])
	}
```

**Comment by behdad** [comment]
That's not the most intuitive...  Dictionary would have been more convenience.  We have similar constraints (all should have the same set of keys, etc) in other tables...

**Comment by twardoch** [comment]
A general note: I agree with Behdad that we don't need to blindly adhere to the XML syntaxes proposed by Yannis Haralambous for the AAT tables. They're a good starting point, but if you guys find for a certain table they're inconvenient for some reason, or can propose a better structure, feel free.

**Comment by anthrotype** [comment]
Ok, i'll see what I do.

**Comment by anthrotype** [comment]
is everyone happy with the implementation? If so, I'll close the issue.

**Comment by jenskutilek** [comment]
It looks good to me, thank you very much!
