### ISSUE TITLE
making automatically recompiled fields optional

### ISSUE THREAD

**Issue by Pomax** [behdad/fonttools#387]
There are a lot of fields that TTX will automatically compute during a compile run from xml to font, and it would be quite useful if one could tell TTX to put those values in if they have not been specified. For instance, the following XML will fail when trying to TTX convert:
```
  <head>
    <fontRevision value="1.0"/>
    <unitsPerEm value="2048"/>
    <created value="Mon Aug 03 12:00:00 2015"/>
  </head>
```
but there isn't really a good reason for this: the table data that needs to be encoded is formally fixed (per the spec), and TTX will recompile them already anyway, so it should be entirely possible to have TTX check for missing fields and instead of erroring out, simply create the fields with the appropriate value injected. 

Ideally, the current TTX behaviour would be preserved under a `--strict` runtime flag, so that `$> ttx font.ttx` converts the font, autoinjecting values that TTX recomputes anyway, while `$> ttx --strict font.ttx` fails on the above XML, because there are spec-required fields missing.

**Comment by Pomax** [comment]
hah, turns out I had already filed this as https://github.com/behdad/fonttools/issues/329 a while back and had completely forgotten... so I guess that just means it's a feature I wish existed time and again =)

**Comment by behdad** [comment]
I'm slowly starting to think that we should work on a new version that breaks the XML format and the API, and do all our clean-ups there.  But then again, maybe it can be done compatibly...

**Comment by Pomax** [comment]
I think using a `--strict` flag is probably still a good idea, provided the version's "semantically" bumped (so that people can reasonably expect 3.x to not always behave the same as 2.x)
