### ISSUE TITLE
Python-only Brotli?

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#388]
Just for fun, should we try integrating with Mark Adler's independent implementation of Brotli decoding that is pure Python?

https://github.com/madler/brotli

**Comment by behdad** [comment]
Err, nevermind, it's not Python anymore, he rewrote in C it seems...

**Comment by anthrotype** [comment]
yeah.. btw, it's going to be super slow.

**Comment by pothos** [comment]
I ported a Rust implementation[1] over to Python[2] and of course it was slower - But then it got even worse because of an own alloc function on a big array which was required due to being a subset without dynamic lists. Also it's not object oriented but I if you think it's interesting to have a pure Python implementation it could be a starting point.

[1] https://github.com/ende76/brotli-rs
[2] https://github.com/pothos/zpaqlpy/blob/master/test/brotli.py

**Comment by anthrotype** [comment]
That's cool as a research project, but I don't think we need a pure python implementation of brotli. The C implementation works well on all the platforms we support, and we have pre-complied wheels so users don't need compilers to build from source.
Maybe you can propose your project to the Brotli developers in the upstream google/brotli repo.

**Comment by behdad** [comment]
Impressive!

**Comment by pothos** [comment]
(here it's standalone and can be used as a module, but as I said, unpythonic and slow) https://github.com/pothos/brotlipython

**Comment by gitcnd** [comment]
Not everyone can use modules you know - for example - Fusion360 add-ins are Python, but authors have no control over the users environment - Autodesk decide what they ship and support - not us...
That's just 1 example - there's always going to me more edge cases where native is the only ting that works.

Speed isn't always important either, by the way (like, for example, background software update distribution).

**Comment by anthrotype** [comment]
@gitcnd what are you suggesting that we do?

**Comment by gitcnd** [comment]
Just educating you since you said " I don't think we need a pure python implementation of brotli. " and " it's going to be super slow " - and https://github.com/pothos/brotlipython works great (takes 30mins to decompress 325megs, which is fine for background work on big files)
