### ISSUE TITLE
[psLib] StringIO -> BytesIO fails with AttributeError: no attribute 'buf'

### ISSUE THREAD

**Issue by anthrotype** [behdad/fonttools#391]
[extractor](https://github.com/typesupply/extractor) can't load Type1 fonts any more due to a change in psLib module, which replaced `StringIO.StringIO` with `io.BytesIO`. Unlike the former, the latter does not have a 'buf' attribute.

https://github.com/behdad/fonttools/commit/bf0e336d316518115a7b47da4f721bb8a009b3e1#diff-d80be98c7272686386f0942c395e1ac3

```
Traceback (most recent call last):
  File "<untitled>", line 14, in <module>
  File "extractor/formats/type1.pyc", line 23, in extractFontFromType1
  File "extractor/formats/type1.pyc", line 186, in _extractType1GlyphOrder
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/misc/psLib.py", line 159, in interpret
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/misc/psLib.py", line 53, in getnexttoken
AttributeError: 'PSTokenizer' object has no attribute 'buf'
```

**Comment by anthrotype** [comment]
while debugging this, I also discovered that the whole `t1Lib` is not working with Python 3 because of unicode vs bytes issues...
This will take a while. :-/

**Comment by behdad** [comment]
sigh...

**Comment by anthrotype** [comment]
yeah.

```
$ python Lib/fontTools/misc/psLib_test.py 
Traceback (most recent call last):
  File "Lib/fontTools/misc/psLib_test.py", line 11, in <module>
    ttFont = T1Font(t1path)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 55, in __init__
    self.data, type = read(path)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 112, in read
    return readOther(path), 'OTHER'
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 207, in readOther
    chunks = findEncryptedChunks(data)
  File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 315, in findEncryptedChunks
    eBegin = data.find(EEXECBEGIN)
TypeError: 'str' does not support the buffer interface
```

**Comment by anthrotype** [comment]
but don't worry, I'll fix this ;)

**Comment by behdad** [comment]
> yeah.
> 
> $ python Lib/fontTools/misc/psLib_test.py 
> Traceback (most recent call last):
>   File "Lib/fontTools/misc/psLib_test.py", line 11, in <module>
>     ttFont = T1Font(t1path)
>   File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 55, in __init__
>     self.data, type = read(path)
>   File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 112, in read
>     return readOther(path), 'OTHER'
>   File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 207, in readOther
>     chunks = findEncryptedChunks(data)
>   File "/Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/t1Lib.py", line 315, in findEncryptedChunks
>     eBegin = data.find(EEXECBEGIN)
> TypeError: 'str' does not support the buffer interface

Humm.  Is `psLib_test` something you just wrote?  I don't have it.  But it looks like you are not opening the test data in binary there...

**Comment by anthrotype** [comment]
Yes, it was something I am writing for testing the issue. The data is open in binary. It's actually the constant EEXECBEGIN which is a `str` (that is, unicode in py3).

I'll look into it tomorrow.

**Comment by anthrotype** [comment]
OK, I realised that there's too much work to do in order to make t1Lib.py and related modules work with python3...

So what I'll do to fix the current Robofont/extractor issue with Type1 fonts is to revert to the old python2-only `StringIO.StringIO` as a base class for the `PSTokenizer`, and explicitly -- but hopefully, only temporarily -- drop support for t1Lib if `sys.version[0] > '2'`.

I'll open a separate issue to track the t1Lib/python3 issues.
