### ISSUE TITLE
Make subsetter.Options non-global

### ISSUE THREAD

**Issue by ruud-v-a** [behdad/fonttools#413]
I admit that I am not very familiar with Python idioms, but the following truly surprised me:

    >>> from fontTools.subset import Options
    >>> x = Options()
    >>> 'dlig' in x.layout_features
    False
    >>> y = Options()
    >>> 'dlig' in y.layout_features
    False
    >>> x.layout_features.append('dlig')
    >>> 'dlig' in y.layout_features
    True

I would expect `x` and `y` to be independent instances of `Options`.

**Comment by behdad** [comment]
That's definitely was not intended.  I'll fix it up.

**Comment by ruud-v-a** [comment]
Thanks!
