### ISSUE TITLE
ERROR: glyf: Decreasing contour index 0 + 1 <= 33

### ISSUE THREAD

**Issue by bihicheng** [behdad/fonttools#418]
hi all,
I have a font with this error, do you know how to fix it ?

**Comment by anthrotype** [comment]
Could you please provide more info as to where you get that error and what you are trying to do?Tthanks.

**Comment by bihicheng** [comment]
The font does not render correctly in chrome broswer, then I use ot-sanitise to check font, It report this error.

I want to use this font.

**Comment by anthrotype** [comment]
what does this have to do with fonttools exactly?

**Comment by bihicheng** [comment]
I want to use fonttools to fix this font, make it render correctly in chrome broswer.

**Comment by anthrotype** [comment]
I see. You should try to be a bit less generic, otherwise we can't help.
What is the name of the font? Where did you get it from?

**Comment by bihicheng** [comment]
I upload this font.

**Comment by anthrotype** [comment]
you can also have a look at the source code of OTS where that error is being raised:
https://github.com/khaledhosny/ots/blob/f77bd1565d239310beb3a16bf8fcb36163ee3838/src/glyf.cc#L96

it looks like in one of your glyphs, the array of last contour points is not sorted by increasing index.

**Comment by bihicheng** [comment]
The font's download address 
http://pan.baidu.com/s/1qXnuT32

**Comment by anthrotype** [comment]
ot-sanitise is telling you that glyph 7085 is corrupt. You need to check that for that glyph, the `endPtsOfContours` array of indices of the last points for each contour is sorted in increasing order.

```
$ ot-sanitise glyf.ttf
ERROR: glyf: Decreasing contour index 0 + 1 <= 33
ERROR: glyf: Failed to parse glyph 7085
ERROR: glyf: failed to parse table
Failed to sanitise file!
```

**Comment by bihicheng** [comment]
thanks :)
