### ISSUE TITLE
travis: switch to container-based infrastructure (sudo: false)

### ISSUE THREAD

**Issue by anthrotype** [behdad/fonttools#429]
currently we use `sudo` to install gcc 4.8 because Brotli used to require C++11 features in order to compile. That is no longer the case, since brotli can now be compiled with old compilers that don't support C++11.

I have opened a PR on https://github.com/google/brotli/pull/278 to disable the option in brotli's `setup.py`. Once that is merged, we will be able to compile brotli with the gcc version pre-installed on Travis, and no longer need `sudo apt-get` it.

We can then add the line `sudo: false` to our `.travis.yml`, and remove the `before_install` part for gcc-4.8.

Our Travis builds will hopefully be faster.

**Comment by addaleax** [comment]
@anthrotype fwiw, you don’t need sudo for installing apt packages; Travis supports specifiying dependencies like this: https://github.com/addaleax/lzma-native/blob/master/.travis.yml#L17

**Comment by anthrotype** [comment]
@addaleax oh, I didn't know that. Thanks!
Anyway, we don't need to install g++ 4.8 now that Brotli can be built without C++11 support, and the Travis build will be a little bit faster with that step.
