### ISSUE TITLE
[feaLib] Feature file parser fails when a 'table' is included in file

### ISSUE THREAD

**Issue by punchcutter** [behdad/fonttools#440]
According to the the OpenType Feature File Specification it is possible to specify or override tables within the feature file: http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#9
Because feaLib.parser.Parser has no 'table' parser it fails with "Expected feature, languagesystem, lookup, markClass, or glyph class definition"

**Comment by behdad** [comment]
Right, that's not implemented yet.  @brawer has plans to work on that.

**Comment by brawer** [comment]
@punchcutter, thanks for the report! The head revision of fontTools now implements `table GDEF`. Do you need any others? Of course, the eventual goal is to implement them all. But if there is some particular table that you need, please do not hesitate to file a bug so we can prioritize it.

**Comment by graphicore** [comment]
:+1: 

@brawer, thanks a lot! This is just in time! It was 2 hours ago when I missed this :grinning:

I'm going to test it later.

**Comment by adrientetar** [comment]
@brawer Is there no way to generically handle any table that comes up?

**Comment by punchcutter** [comment]
At the moment I need any possible table, the main reason being that fea files generated by Glyphs and OTMaster include all kinds of stuff and even if I don't care about those tables I can't get to the GSUB and GPOS using the parser. For now I have to create a temp file with tables stripped out just to parse anything.

**Comment by behdad** [comment]
> At the moment I need any possible table,

Maybe enumerate which tables are those?  I assume head, hhea, post, OS/2, name, what else?

**Comment by brawer** [comment]
Feature files can define/modify BASE, GDEF, head, hhea, name, OS/2, vhea, and vmtx (but not eg. post). GDEF is done; I’ll work on the others as soon as I’m done with `feature aalt` (which needs special treatment). If anyone wants to have something faster, send pull requests. Otherwise, wait a few weeks.
