### ISSUE TITLE
[pyftmerge] merged.ttf fails OTS (Layout tags not alphabetical, cmap missing subtables)

### ISSUE THREAD

**Issue by davelab6** [behdad/fonttools#444]
I got

    git clone http://github.com/googlei18n/noto-fonts.git

for

    hinted/NotoKufiArabic-Regular.ttf
    hinted/NotoSansHebrew-Regular.ttf

And the latest fontTools:

    git clone http://github.com/behdad/fonttools.git
    cd fonttools; sudo python setup.py install; cd ..;

I subset the relevant characters from the files. 

    $ pyftsubset noto-fonts/hinted/NotoKufiArabic-Regular.ttf \
    --unicodes="\U+062A U+0642 U+0645 U+0648 U+064A" \
    --layout-features='*' --glyph-names --symbol-cmap --legacy-cmap \
    --notdef-glyph --notdef-outline --recommended-glyphs \
    --name-IDs='*' --name-legacy --name-languages='*' \
    --verbose --timing --hinting;
    
    Retaining 34 glyphs:
    Input font:  80048 bytes: noto-fonts/hinted/NotoKufiArabic-Regular.ttf
    Subset font:   7944 bytes: noto-fonts/hinted/NotoKufiArabic-Regular.ttf.subset

    $ pyftsubset noto-fonts/hinted/NotoSansHebrew-Regular.ttf --unicodes="\
    U+05D4 U+05D5 U+05D9 U+05DC U+05DE U+05DF U+05E9" \
    --layout-features='*' --glyph-names --symbol-cmap --legacy-cmap \
    --notdef-glyph --notdef-outline --recommended-glyphs \
    --name-IDs='*' --name-legacy --name-languages='*' \
    --verbose --timing --hinting;
    
    Retaining 11 glyphs: 
    Input font:  26372 bytes: noto-fonts/hinted/NotoSansHebrew-Regular.ttf
    Subset font:   5428 bytes: noto-fonts/hinted/NotoSansHebrew-Regular.ttf.subset
    
Then I checked the subsets were valid:

    $ ot-sanitise NotoKufiArabic-Regular.ttf.subset.ttf ;
    $
    
    $ ot-sanitise NotoSansHebrew-Regular.ttf.subset.ttf ;
    $

Then I merged the subsets with a FontForge-created version of ProductSans-Regular scaled up to a UPM of 2048 and subset, but this merging didn't work:

    $ mv noto-fonts/hinted/*subset .;
    $ pyftmerge ProductSans-Regular2048.ttf.subset.ttf NotoKufiArabic-Regular.ttf.subset.ttf;
    $ mv merged.ttf PSArabic.subset.ttf;
    $ ot-sanitise PSArabic.subset.ttf 
    WARNING: Layout: tags aren't arranged alphabetically.
    ERROR: cmap: no supported subtables were found
    ERROR: cmap: failed to serialize table
    Failed to sanitise file!
    
    $ pyftmerge NotoKufiArabic-Regular.ttf.subset.ttf ProductSans-Regular2048.ttf.subset.ttf ;
    $ mv merged.ttf PSArabic.subset.ttf;
    $ ot-sanitise PSArabic-invert.subset.ttf 
    WARNING: Layout: tags aren't arranged alphabetically.
    ERROR: cmap: no supported subtables were found
    ERROR: cmap: failed to serialize table
    Failed to sanitise file!

The 3 subset files used in the above 2 commands are all in this Google Drive folder:

https://drive.google.com/folderview?id=0B4Odx154QIHFUXVBXzg3NWxsSWc

**Comment by graphicore** [comment]
I can produce a very similar ot-sanitize output with a very different setup.

```
$ pyftmerge Generated/Mirza-Regular.ttf.subset  Generated/TTF-Mirza-LATIN/Latin-Mizra-Regular.ttf
$ ot-sanitise merged.ttf 
WARNING: Layout: tags aren't arranged alphabetically.
WARNING: Layout: tags aren't arranged alphabetically.
ERROR: cmap: no supported subtables were found
ERROR: cmap: failed to serialize table
Failed to sanitise file!
```

`merged.ttf`is basically unusable, it segfaults FontForge on my machine, when trying to open it.

I can provide my input files if needed.

**Comment by behdad** [comment]
I'll try to take a look tonight.

**Comment by behdad** [comment]
@graphicore Please provide input files.

**Comment by graphicore** [comment]
I'll have to see if I can still reproduce this first. I don't think these files still exist.

**Comment by graphicore** [comment]
Now I'm not even getting past `pyftmerge`, so I can't try further. fonttools is installed from master:

> Exception: Don't know how to merge key Format of class ClassDef

I took the files straight from the repository:

Mirza-Regular.ttf in https://github.com/Tarobish/Mirza/tree/gh-pages/Sources/Build/Arabic
Latin-Mizra-Medium.ttf: https://github.com/Tarobish/Mirza/tree/gh-pages/Sources/Build/Latin

Here is what I did:

```
commander@ghoul:~/Projekte/fontdev/fonttools444$ ls
Latin-Mizra-Regular.ttf  Mirza-Regular.ttf
commander@ghoul:~/Projekte/fontdev/fonttools444$ pyftsubset Mirza-Regular.ttf  --unicodes="U+0600-FEFE" --layout-features='*' --glyph-names
commander@ghoul:~/Projekte/fontdev/fonttools444$ pyftmerge Mirza-Regular.ttf.subset Latin-Mizra-Regular.ttf 
Traceback (most recent call last):
  File "/usr/local/bin/pyftmerge", line 9, in <module>
    load_entry_point('fonttools==3.0', 'console_scripts', 'pyftmerge')()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 369, in wrapper
    return func(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 909, in main
    font = merger.merge(args)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 779, in merge
    table = clazz(tag).merge(self, tables)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 159, in merge
    return m.mergeObjects(self, self.mergeMap, tables)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 824, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 121, in mergeObjects
    value = mergeLogic(getattr(table, key, NotImplemented) for table in lst)
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 118, in mergeObjects
    (key, clazz.__name__))
Exception: Don't know how to merge key Format of class ClassDef

```

Note also: I don't remember how I produced the `Generated/Mirza-Regular.ttf.subset` from my message in https://github.com/behdad/fonttools/issues/444#issuecomment-169088568 but I could also get the files from that day in the Mirza repository.

**Comment by behdad** [comment]
Ugh.  Right.  I'll take a look.

On Thu, Apr 21, 2016 at 2:03 PM, Lasse Fister <notifications@github.com>
wrote:

> Now I'm not even getting past pyftmerge, so I can't try further.
> fonttools is installed from master:
>
> Exception: Don't know how to merge key Format of class ClassDef
>
> I took the files straight from the repository:
>
> Mirza-Regular.ttf in
> https://github.com/Tarobish/Mirza/tree/gh-pages/Sources/Build/Arabic
> Latin-Mizra-Medium.ttf:
> https://github.com/Tarobish/Mirza/tree/gh-pages/Sources/Build/Latin
>
> Here is what I did:
>
> commander@ghoul:~/Projekte/fontdev/fonttools444$ ls
> Latin-Mizra-Regular.ttf  Mirza-Regular.ttf
> commander@ghoul:~/Projekte/fontdev/fonttools444$ pyftsubset Mirza-Regular.ttf  --unicodes="U+0600-FEFE" --layout-features='*' --glyph-names
> commander@ghoul:~/Projekte/fontdev/fonttools444$ pyftmerge Mirza-Regular.ttf.subset Latin-Mizra-Regular.ttf
> Traceback (most recent call last):
>   File "/usr/local/bin/pyftmerge", line 9, in <module>
>     load_entry_point('fonttools==3.0', 'console_scripts', 'pyftmerge')()
>   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/misc/loggingTools.py", line 369, in wrapper
>     return func(*args, **kwds)
>   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 909, in main
>     font = merger.merge(args)
>   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 779, in merge
>     table = clazz(tag).merge(self, tables)
>   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 159, in merge
>     return m.mergeObjects(self, self.mergeMap, tables)
>   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 824, in mergeObjects
>     value = mergeLogic(getattr(table, key, NotImplemented) for table in tables)
>   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 121, in mergeObjects
>     value = mergeLogic(getattr(table, key, NotImplemented) for table in lst)
>   File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/merge.py", line 118, in mergeObjects
>     (key, clazz.__name__))
> Exception: Don't know how to merge key Format of class ClassDef
>
>
> Note also: I don't remember how I produced the
> Generated/Mirza-Regular.ttf.subset from my message in #444 (comment)
> <https://github.com/behdad/fonttools/issues/444#issuecomment-169088568>
> but I could also get the files from that day in the Mirza repository.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/behdad/fonttools/issues/444#issuecomment-213113549>
>



-- 
behdad
http://behdad.org/

**Comment by yincrash** [comment]
@davelab6's error comes from pyftmerge only outputting one cmap table where 
`cmapTable.platEncID = max(t.platEncID for t,_ in cmapTables)`

Since, `ProductSans-Regular2048.ttf.subset.ttf` has a format 4 subtable with platform/encoding id of 0/3 (Unicode 2.0+ BMP only) in addition to the normal 4/3/1 windows BMP-only table, `pyftmerge` outputs a 4/3/3 subtable only, which then kills `ot-sanitise`. 

I'm making a patch to fix this (TODO)[https://github.com/behdad/fonttools/blob/master/Lib/fontTools/merge.py#L363], so I'll also make sure it handles this cmap merge as well.

**Comment by anthrotype** [comment]
@yincrash that's good. thanks!

**Comment by behdad** [comment]
I fixes the original issue.  cmap issue is separate.  Will take a look as well.
