### ISSUE TITLE
[feaLib] Support multiple single substitutions on the same glyph

### ISSUE THREAD

**Issue by jamesgk** [behdad/fonttools#452]
I can't find anything in the specification about this, but I think multiple single substitution rules for a glyph should be legal within the same feature. For example when the following is compiled:

```
feature aalt {
    sub Eng by Eng.alt1;
    sub Eng by Eng.alt2;
    sub Eng by Eng.alt3;
} aalt;
```

the resulting font should behave as such:

```
$ hb-shape --features=aalt MyFont.ttf "Ŋ"
[Eng.alt1=0+750]
$ hb-shape --features=aalt=1 MyFont.ttf "Ŋ"
[Eng.alt1=0+750]
$ hb-shape --features=aalt=2 MyFont.ttf "Ŋ"
[Eng.alt2=0+750]
$ hb-shape --features=aalt=3 MyFont.ttf "Ŋ"
[Eng.alt3=0+750]
```

**Comment by khaledhosny** [comment]
Isn’t this what `sub … from …;` is for?

**Comment by jamesgk** [comment]
Oh, that does look like the correct way to do this. makeotf will compile my example, so I guess making it illegal is just not backwards compatible at worst. But I'm OK with accepting that `sub ... from ...;` is the correct syntax and my example is invalid.

**Comment by khaledhosny** [comment]
This seems to be the special handling of `aalt` by makeotf kicking it where all substitutions of a glyph are accommodated and turned into alternates substitution, if you use a different feature tag it will raise an error.

**Comment by brawer** [comment]
See https://github.com/adobe-type-tools/afdko/issues/97 for the spec discussion about `aalt`. Closing this bug for now.

**Comment by brawer** [comment]
See https://github.com/behdad/fonttools/issues/502 for relaxing the constraints inside `aalt`. But outside `feature aalt`, I’m not sure what it would mean to support multiple single substitutions on the same glyph.
