### ISSUE TITLE
[feaLib] Allow mark classes in separate lookups to share glyphs

### ISSUE THREAD

**Issue by jamesgk** [behdad/fonttools#453]
At http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#6.d the specification says that mark classes within a single lookup must be disjoint, so I guess it's implied that mark classes in separate lookups can share glyphs. However, makeGDEF() in builder.py checks that all mark classes are disjoint.

I don't really know enough about how the GPOS table is constructed to know if it actually makes sense to share glyphs between mark classes. But I have seen something like this in the wild:

```
feature mark {
    lookup mark1 {
        markClass [acute] <anchor 150 -10> @TOP_MARKS;
        position base [e] <anchor 250 450> mark @TOP_MARKS;
    } mark1;
    lookup mark2 {
        markClass [acute] <anchor 150 -20> @TOP_MARKS_2;
        position base [e] <anchor 250 450> mark @TOP_MARKS_2;
    } mark2;
} mark;
```

**Comment by behdad** [comment]
Correct assessment.

**Comment by graphicore** [comment]
I just ran into this.

Here is a more explicit statement from http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#4.f

> NOTE! The mark classes used within a single lookup must be disjoint: none may include a glyph which is in another mark class that is used within the same lookup.

```
Traceback (most recent call last):
  File "./Tools/mergeFeaIntoFont.py", line 73, in <module>
    main(dropOldGSUB, dropOldGPOS, fea, font)
  File "./Tools/mergeFeaIntoFont.py", line 40, in main
    Builder(fea, feaFont).build()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 61, in build
    gdef = self.buildGDEF()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 162, in buildGDEF
    gdef.GlyphClassDef = self.buildGDEFGlyphClassDef_()
  File "/usr/local/lib/python2.7/dist-packages/fonttools-3.0-py2.7.egg/fontTools/feaLib/builder.py", line 206, in buildGDEFGlyphClassDef_
    (glyph, name1, name2), markClassDef.location)
fontTools.feaLib.error.FeatureLibError: ./Sources/gpos.fea:208:3: Glyph uni064D cannot be both in markClass @Anchor4 and @Anchor6
```

**Comment by brawer** [comment]
Also, the spec says explicitly:
> NOTE! If a GDEF table is not explicitly defined in the feature file, [...] all mark glyph classes must be disjoint, and [...].

See https://github.com/adobe-type-tools/afdko/issues/106 for a proposal to remove this restriction from the spec. But whatever the spec says, makeotf does allow shared markClasses, so I’ll change feaLib accordingly.

**Comment by marekjez86** [comment]
I verified in my tests that this was fixed. Thank you.

**Comment by adrientetar** [comment]
For the record, I got feature file code coming from FontForge which I reduced to this:

```
feature mark {
    markClass [\uni0327 \uni0328 ] <anchor 0 0> @ogonek;
    pos base [a] <anchor 399 0> mark @ogonek;
    markClass [\uni0327 ] <anchor 0 0> @cedilla;
    pos base [a] <anchor 244 0> mark @cedilla;
} mark;
```

The \@cedilla isn't registered as mark class by feaLib because it will skip uni0327 the second time it comes in; this is consistent with the spec, as it's all contained in a single lookup.
