### ISSUE TITLE
time.asctime returns different strings in python 2 and 3

### ISSUE THREAD

**Issue by anthrotype** [behdad/fonttools#455]
`fontTools.misc.timeTools.timestampToString` uses `time.asctime` to transform a time tuple to a default string.

There seems to be differences in the way python 2 and python 3 format this string (e.g. days are padded to two figures with leading zeros in one, but not in the other) 

This affects specifically the `head.created` and `head.modified` attributes, as shown in this Appveyor build log:

https://ci.appveyor.com/project/behdad/fonttools/build/1.0.39/job/2w635jv86nxq419o#L232

/cc @brawer

**Comment by brawer** [comment]
For now I’ll work around it by using a date that doesn’t involve leading zeroes, such as Dec 13 instead of Jan 1.

**Comment by brawer** [comment]
Btw, I appears to be only Python 2.7 on Windows. On UNIX, the strings are identical for all Python versions.

**Comment by brawer** [comment]
The work-around has fixed the Windows tests; closing the bug.

**Comment by anthrotype** [comment]
I'd like to keep this open until we fix this. We should try to make the TTX outputs of Python 2 and 3 identical as much as we can to avoid unwanted diffs.
