### ISSUE TITLE
[feaLib] Allow classnames longer than 30 chars

### ISSUE THREAD

**Issue by adrientetar** [behdad/fonttools#460]
makeotf does allow up to 63 chars since a few years ago, see @readroberts comment: https://github.com/fontforge/fontforge/pull/2500#issuecomment-143263393 and associated AFDKO issue adobe-type-tools/afdko#70.

cc @brawer

**Comment by brawer** [comment]
Pull request with spec change: https://github.com/adobe-type-tools/afdko/pull/99
