### ISSUE TITLE
feaLib.builder_test.py contains non-unit tests

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#465]
As it is right now, a few functions do this:
```py
    def test_GPOS(self): 
        for name in "1 2 2b 3 4 5 6 8".split(): 
            font = makeTTFont() 
            addOpenTypeFeatures(self.getpath("GPOS_%s.fea" % name), font) 
            self.expect_ttx(font, self.getpath("GPOS_%s.ttx" % name)) 
```

This is not good because we now only see one failure if any number of those tests fail.  Please rewrite these to add one function per test.  There are a couple of different ways to do that, for example, building the class dynamically.  I don't know what the best way is, but I'm sure there's a standard way to do that.

Thanks.

**Comment by graphicore** [comment]
I recently used a class decorator for something similar: https://github.com/adrientetar/defcon/blob/python3-ufo3/Lib/defcon/objects/info.py#L49
