### ISSUE TITLE
Automatically add/remove Extension subtables

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#47]
Extension subtable mechanism is a way to work around the 64k limit of Offset types.  So, user shouldn't worry about it and we should just automatically introduce them when compiling GSUB/GPOS tables.

**Comment by brawer** [comment]
This seems to be working fine, so I’m closing this bug. If anyone disagrees, please re-open.

**Comment by behdad** [comment]
There are two parts as I see, where it can be improved:

* Currently Extension lookups are loaded into Extension objects, and written to XML as Extension.  Would be nice to hide either the XML, or both parts, and fully hide Extension lookups from user as they are just an encoding mechanism,

* The exension-introducing code is really slow with many lookups that need to be promoted, as it promotes one lookup to extension and restarts compiling the table, just to fail again and promote the next lookup and restart again...

**Comment by twardoch** [comment]
@behdad I wouldn't like it if fontTools completely obscured the info whether lookups are extension type or not. It would be nice to reform the current structure where extension lookups live in an extra layer of the object tree so converting between simple and extension lookups is a bit tedious. Some easy-to-change attribute would be ideal. But there is still lots of legacy OT engines that don't handle extension lookups well, especially in desktop environments. So an explicit mechanism to control it would be great. I imagine an XML attribute on the Lookup level akin to extensionType="True"|"False"|"Auto" where in case of "Auto" (write-only value), fontTools would automatically pick the most optimal form. A similar mechanism would be great for other structures eg. "cmap" subtables or other such formats. But completely hiding this would be limiting fontTools' usefulness as a roundtripping tool.

**Comment by behdad** [comment]
I kinda agree.  We have have an attribute that defaults to auto.  Then in XML output, we'll write the attribute with True/False depending on what was actually in the font, but comment out the attribute.  This way user knows how to enforce one way or another.  Or, my preference, don't bother writing it out.  In a sense, we allow user explicitly requesting extension=True, but otherwise don't support any control.

Note that fonttools already automatically inserts extension tables as needed.

Also, what apps still don't support those?

For cmap subtable formats, I agree, we should make it **much** simpler to convert formats.  I'll file another issue for that.

**Comment by behdad** [comment]
Filed cmap issue here: https://github.com/behdad/fonttools/issues/384
