### ISSUE TITLE
Crazy number of digits and bloatness in CFF CharString XML

### ISSUE THREAD

**Issue by HinTak** [behdad/fonttools#492]
While comparing the result with Microsoft Font Validator's new CFF table parsing I am working on, I notice that:

---
<CharString name="period">
          107 53.400390625 166.19900512695312 hstem
          174.60000610351562 163.80099487304688 vstem
          338.3999938964844 142.8000030517578 rmoveto
          0 21.600006103515625 -6.29998779296875 18.20001220703125 -12.600006103515625 14.79998779296875 -12.600006103515625 14.800003051757812 -18.
100006103515625 7.4000091552734375 -23.5999755859375 0 -28.400009155273438 0 -22.199996948242188 -8.70001220703125 -16 -17.399993896484375 -16 -17.3
99993896484375 -8 -20.300003051757812 0 -23.199996948242188 0 -21.600006103515625 6.5 -18.599609375 13 -15.6005859375 13 -15.599609375 18.2999877929
6875 -7.7998046875 23.600006103515625 0 rrcurveto
          28 0 21.899993896484375 9 15.800018310546875 18 15.79998779296875 18 7.899993896484375 20.799606323242188 0 23.600006103515625 rrcurveto
          endchar
        </CharString>
---

surely that is

107 53.4 166.2 hstem
174.6 163.8 vstem

etc?

This not only increases the XML dump size a lot (by a factor of 4x to 5x), but also seems to affect memory consumption. Try dumping one of the Adobe CJK otf's :-).

**Comment by anthrotype** [comment]
CFF Type 2 fonts store decimal coordinate values as a Fixed 16.16 number. In `fontTools.misc.fixedTools` module we have a `fixedToFloat` func that converts fixed point numbers (with arbitrary precision) to floats having the shortest decimal representation. However, neither cffLib nor psCharStrings modules seems to be using that function.
@HinTak could you maybe send to me some examples of CFF fonts with decimal coordinates for testing (privately if you like)?

**Comment by HinTak** [comment]
The CharString I showed came from calibreSymbols.otf of calibre ebook viewer 2.49 on fedora 23. It should be public somewhere. I used it for testing because it is the smallest CFF opentype font on fedora.

I started off with one of the CJK otf fonts from the Adobe Reader CJK font pack, which is probably one of the larger you can get. So if you want to test memory consumption and file size, that's perhaps one of the worst cases to test for.
