### ISSUE TITLE
How bad is OTLOffsetOverflowError?

### ISSUE THREAD

**Issue by davelab6** [behdad/fonttools#499]
I discovered a warning from ttx with the last release of Mozilla's Fira - https://github.com/mozilla/Fira/issues/146 - and this is the warning:

```
WARNING: Attempting to fix OTLOffsetOverflowError ('GPOS', 'LookupIndex:', 8, 'SubTableIndex:', None, 'ItemName:', None, 'ItemIndex:', None)
```

Is this a problem? OTS passes.

**Comment by behdad** [comment]
No, this is fonttools working as intended.  We should change that from a warning to an informational log message.
