### ISSUE TITLE
[feaLib] Relax constraints for “sub by” inside “feature aalt”

### ISSUE THREAD

**Issue by brawer** [behdad/fonttools#502]
Glyphs.app can generate the following:
```
feature aalt {
    sub Eng by Eng.alt1;
    sub Eng by Eng.alt2;
    sub Eng by Eng.alt3;
} aalt;
```

Now, feaLib has implemented the special handling for `aalt` features as per [specification section 8.a](http://www.adobe.com/devnet/opentype/afdko/topic_feature_file_syntax.html#8.a). However, beyond what is written in the spec, makeotf also seems to enter some relaxed parsing mode that allows re-definitions of single substitutions when they happen to be placed inside `aalt` features. Although such relaxed parsing is not mentioned in the spec, makeotf seems to have this behavior; because Glyphs.app and perhaps other applications depend on it, we should implement it too.

**Comment by anthrotype** [comment]
if that is the case, shouldn't the spec also be updated accordingly?

**Comment by brawer** [comment]
See https://github.com/adobe-type-tools/afdko/issues/97 for the spec discussion.
