### ISSUE TITLE
[feaLib] ChainContextPos has wrong SequenceIndex

### ISSUE THREAD

**Issue by brawer** [behdad/fonttools#517]
Input (existing test case `spec6h_iii_3d`):
```
feature test {
    position L' quoteright' -150;
} test;
```

Expected:
```xml
    <ChainContextPos index="0" Format="3">
          <PosLookupRecord index="0">
            <SequenceIndex value="1"/>
          </PosLookupRecord>
    </ChainContextPos>
```

Observed:
```xml
    <ChainContextPos index="0" Format="3">
          <PosLookupRecord index="0">
            <SequenceIndex value="0"/>
          </PosLookupRecord>
    </ChainContextPos>
```

**Comment by behdad** [comment]
Right.  That's what baffled me when I was reading your code here:
https://github.com/behdad/fonttools/issues/463#issuecomment-174229374

The fact that sequenceIndex is coming from enumerate() cannot be right unless captured arguments have a lookup applied to them.
