### ISSUE TITLE
[subset] With some shapers, Uniscribe shaper sometimes fails if GSUB is empty

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#518]
In particular, what I've observed so far is: at least for Thai, if GPOS has 'thai' system but GSUB doesn't, then uniscribe fails.

I remember hearing similar stories about other shapers (Aarabic?  Hebrew?).  So, I suggest we keep ScriptRecords in GSUB for those that are in GPOS.

This is also similar to fixing this Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1080739#c15

**Comment by behdad** [comment]
In my limited testing, I cannot reproduce this for Arabic.

**Comment by anthrotype** [comment]
this issue might be related https://github.com/behdad/fonttools/issues/372

**Comment by behdad** [comment]
Fixed...

**Comment by behdad** [comment]
Ugh.  For Thai, looks like Uniscribe also requires that the LookupList not be empty!

**Comment by behdad** [comment]
Maybe not.  Maybe I'm hitting the bug that @anthrotype has had observed before.  It works if at least one of LookupList and FeatureList is not empty.  Fails if both are.  Investigating more.
