### ISSUE TITLE
OS/2 crash

### ISSUE THREAD

**Issue by typefactory** [behdad/fonttools#520]
I am facing a problem in my hinting tool for RoboFont.
We generate a mini temporary font with only a couple of glyphs, including mainly the currentGlyph.
It happens whenever the current glyph has its top (ascent) below the baseline, meaning that the max Y coordinate of the glyph is negative.

Traceback (most recent call last):
  File "lib/fontObjects/doodleFontCompiler/ttfCompiler.pyc", line 589, in compile
  File "ufo2fdk/makeotfParts.pyc", line 66, in compile
  File "ufo2fdk/makeotfParts.pyc", line 81, in setupFile_outlineSource
  File "lib/fontObjects/doodleFontCompiler/ttfCompiler.pyc", line 262, in compile
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 207, in save
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 636, in _writeTable
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/__init__.py", line 649, in getTableData
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/ttLib/tables/O_S_2f_2.py", line 132, in compile
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/fontTools/misc/sstruct.py", line 75, in pack
error: integer out of range for 'H' format code

**Comment by anthrotype** [comment]
WinDescent must be an unsigned short integer. You need to take the absolute value.

**Comment by anthrotype** [comment]
Sorry, I misunderstood. You're saying that in your font there's no glyph ascender above the baseline?
In that case, I'd set usWinDescent to 0.

**Comment by typefactory** [comment]
can we add this to sstruct.py pack function? :
if type(value) == int and value < 0:
	# fix for when value is negative
	value = abs(value)

**Comment by anthrotype** [comment]
I edited the previous comment. I meant `if ascender < 0: usWinAscent = 0`.

**Comment by typefactory** [comment]
or just that then:

if type(value) == int and value < 0:
	# fix for when value is negative
	value = 0

**Comment by anthrotype** [comment]
I guess Robofont should be the one doing the math.

**Comment by horasio** [comment]
Hi there,
The font does contain glyphs with positive ascent. But some glyphs have negative ascent and the compilation of the font seems to fail for those glyphs. It crashed in the OS2 table generation, which is curious indeed. except if the max of the ascents is computed using unsigned short, which would be a bad thing to do imho.

**Comment by moyogo** [comment]
@horasio usWinAscent can only be positive in the binary font as it’s stored as a USHORT https://www.microsoft.com/typography/otspec/os2.htm#wa
Robofont seems to be calculating usWinAscent from yMax which is negative in your mini temporary font.

**Comment by behdad** [comment]
My gut feeling, without checking the code, is that we just need to do man/max with zero to avoid the out-of-range in the OS/2 table.

**Comment by anthrotype** [comment]
just make sure the font you are compiling has font.info.openTypeOS2WinAscent > 0

**Comment by anthrotype** [comment]
I don't think this is a good idea. FontTools is failing (rightly so) because it's getting a wrong input.

**Comment by typemytype** [comment]
can you make a pull request at ufo2fdk 

https://github.com/typesupply/ufo2fdk/blob/master/Lib/ufo2fdk/fontInfoData.py#L138-L148

**Comment by behdad** [comment]
If all glyphs are below baseline, and maxx is unsigned, then setting Zero for ir makes sense, no?

**Comment by horasio** [comment]
Thanks everyone!
Indeed, copying the openTypeOS2WinAscent value from the original UFO to the small one (containing a subset of glyphs) did solve the problem :-)
This means that somewhere in the chain of events, some code computes a bad value for openTypeOS2WinAscent/Descent. Maybe in RF or maybe in FontTools; that I don't know.
Regards,

**Comment by horasio** [comment]
behdad : yes, if the max is negative, then putting 0 is probably the most sane value to store :-)

**Comment by moyogo** [comment]
@behdad min/max or zero is guessing what the user wanted, they might have wanted abs(hhea.ascender) or abs(sTypoAscender) or anything else.

**Comment by anthrotype** [comment]
thanks @typemytype for pointing out where the issue is.

I still thinks that fonttools should just raise when one attempts to compile a OS/2 table with usWinAscent/Descent with a negative value. It is not the job of fonttools to calculate the vertical metrics of the font in this particular case (though we might add an option for that). Here it is simply given a wrong input data, and it is asked to compile. But it cannot, so it raises.

**Comment by typemytype** [comment]
patched, next RoboFont should handle this correctly 

thanks

**Comment by anthrotype** [comment]
thanks!

**Comment by horasio** [comment]
I agree with you, @anthrotype : fonttools must raise because it's not its job to compute this value.
As @moyogo just taught me (at least me) openTypeOS2WinAsc/Desc have some user-choice freedom, but both values must be >= 0. So, a choice has to be made in ufo2sdk.
I see that Frederik goes with 0.
Frederik : I guess it must also be checked that the Descent value is not negative as well.

**Comment by anthrotype** [comment]
for usWinDescent, ufo2fdk takes the abs(yMin) so it should be fine
https://github.com/typesupply/ufo2fdk/blob/master/Lib/ufo2fdk/fontInfoData.py#L162

**Comment by horasio** [comment]
@anthrotype well... it's a user choice so that might be OK, but I would rather write
```
xMin, yMin, xMax, yMax = bounds
if yMin <= 0: return -yMin
else: return 0
```
Otherwise, if all the glyphs have a very large positive bottom (say a font with only accents), then the descent would be very low below the baseline, which is a little strange :-)

**Comment by anthrotype** [comment]
you're right. I'd also go for usWinDescent = 0 if yMin > 0. Pull request to ufo2fdk? ;)

**Comment by typemytype** [comment]
True, return 0 is better then doing an abs of the value

I guess @typesupply wrote those fallbacks in mind with with a proper font with some sort of ascenders and descenders. As no one complained so far :)

I will add it to the pull request

**Comment by typemytype** [comment]
request send

this can be closed

**Comment by adrientetar** [comment]
> I don't think this is a good idea. FontTools is failing (rightly so) because it's getting a wrong input.

+1

**Comment by behdad** [comment]
> I don't think this is a good idea. FontTools is failing (rightly so) because it's getting a wrong input.

Right.  I was under the impression that we were computing a value out of glyph bounds...
