### ISSUE TITLE
[feaLib] Unknown glyph class @MMK_R_period.right

### ISSUE THREAD

**Issue by marekjez86** [behdad/fonttools#522]
This is a new behaviour - not certain if this is correct error reporting (then we have a problem with the glyphs file) or this is an issue/problem in fealib.

When processing NotoSansDisplayItalic-MM.glyphs
[Archive.zip](https://github.com/behdad/fonttools/files/125712/Archive.zip)
 (attached) we get the following error:
 File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 13, in addOpenTypeFeatures
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 50, in build
    self.parseTree = Parser(self.featurefile_path).parse()
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 40, in parse
    statements.append(self.parse_feature_block_())
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 820, in parse_feature_block_
    self.parse_block_(block, vertical)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 867, in parse_block_
    self.parse_position_(enumerated=False, vertical=vertical))
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 448, in parse_position_
    self.parse_glyph_pattern_(vertical)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 246, in parse_glyph_pattern_
    gc = self.parse_glyphclass_(accept_glyphname=True)
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/parser.py", line 181, in parse_glyphclass_
    self.cur_token_location_)
fontTools.feaLib.error.FeatureLibError: /tmp/tmpYZ6X6d:5:24: Unknown glyph class @MMK_R_period.right

tmpYZ6X6d is also attached

**Comment by marekjez86** [comment]
[Archive.zip](https://github.com/behdad/fonttools/files/125713/Archive.zip)

**Comment by marekjez86** [comment]
I assume the following (using different glyphs as input) is related:
 ==== building src/NotoSansHebrew-MM.glyphs ====
[...]
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.
> WARNING: Non-existent glyph class @MMK_R_period.right found in kerning rules.

**Comment by brawer** [comment]
Excerpt from the attachment:
```
feature kern {
    pos B public.kern2.@MMK_R_period.right -10;
} kern;
```

This is invalid syntax, and the compiler is correctly rejecting it. (Also, makeotf rejects it as well). Perhaps the input should have looked like the following? Anyhow, looks like a problem in an earlier stage.
```
feature kern {
    @public.kern2.MMK_R_period.right = [A B C D];
    pos B @public.kern2.MMK_R_period.right -10;
} kern;
```

**Comment by brawer** [comment]
Hm, I wanted to file a bug on fontmake, but `fontmake -g NotoSansDisplayItalic-MM.glyphs` from your attached Archive.zip actually worked just fine. Could not reproduce.

**Comment by brawer** [comment]
However, I ran into the same problem with another font; see https://github.com/googlei18n/fontmake/issues/11.
