### ISSUE TITLE
Release 3.1.0

### ISSUE THREAD

**Issue by davelab6** [behdad/fonttools#528]
When will the 3.1.0 release be made? :)

**Comment by pnemade** [comment]
Good to have new release now as there are many fixes since last release.

**Comment by behdad** [comment]
Remind us in a couple of weeks please?  There are some things broken right
now that we are trying to clean up :).


On Sat, Feb 27, 2016 at 8:01 PM, Parag Nemade <notifications@github.com>
wrote:

> Good to have new release now as there are many fixes since last release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/behdad/fonttools/issues/528#issuecomment-189780493>.
>



-- 
behdad
http://behdad.org/

**Comment by anthrotype** [comment]
I think it's time that we set up Travis to automatically upload the fonttools package to the Python Package Index (PyPI), every time we push a new tag. 

https://docs.travis-ci.com/user/deployment/pypi

This way we make it easier for us to cut releases more often, as well as for users who can then simply `pip install -U fonttools`.

To make this work, I would need the current PyPI credentials for the fonttools project.
The last time it was Dave who uploaded the package?

I would like to take care of setting up Travis for PyPI, but I'm also happy in someone else does it -- as long as we do it.

(and I think it'd be cool if we have a 3.1 release ready for the TypoLabs Berlin)

Please let me know, thanks.

**Comment by davelab6** [comment]
Sure, just let me know the pypi usernames to add to the package

**Comment by anthrotype** [comment]
Thanks. I'm also anthrotype on PyPI.

**Comment by behdad** [comment]
Sounds good.  That put some pressure on us to finalize API of new modules.  So, perhaps do the work at TYPOLabs and release at TYPOBerlin?

**Comment by davelab6** [comment]
Added anthrotype to https://pypi.python.org/pypi/FontTools  :)

**Comment by anthrotype** [comment]
@davelab6 excellent, thanks!
@behdad I didn't mean to put any pressure. We'll do whay we can ;) For now I'll just set up the automatic pypi deployment from Travis upon tags, but you'll be the one to push the --tags trigger when you feel ready.

**Comment by justvanrossum** [comment]
I wouldn't dare to put any pressure on anyone, but I think it would be cool to have a release *before* TypoLabs in Berlin. I'd love for people to play with the latest feaLib etc. there. A "release" would make it sound even stabler than it already is. It would be a pretty cool announcement there, too!

**Comment by twardoch** [comment]
I think it's also fine to let the TYPO Labs crowd grab the git version, tell them to do stresstesting and you can wrap up some loose ends. "Releases" usually get packaged with distributions or end up on pypi or brew. So they are being used by people who don't always have a direct communication channel with the devs. But I think a small part of your talk at TYPO Labs might be Github and community engagement. :)

**Comment by justvanrossum** [comment]
Good points!

**Comment by twardoch** [comment]
Fortunately, with Github, it's trivial to install the git version, so there's very little difference for the user, esp. for Python packages. Particularly since pip supports: 
```
pip install git+https://github.com/behdad/fonttools
```

"Release" is really a cosmetic difference in a way, and I feel is mostly relevant for larger "packagers".

**Comment by twardoch** [comment]
Ps. And for more comprehensive installs of multiple packages one can use
```
pip install -r requirements.txt
```
where requirements.txt is [built like this](https://github.com/googlei18n/fontmake/blob/master/requirements.txt)

That is a really nice way to make "fresh installs".

**Comment by behdad** [comment]
I also see pypi only important insofar as that's what the Linux distros will be stuck with three years from now...

So, I think an announcement of new features, where developers at TYPOLib can immediately test by pip installing github, then a release at the end of the conference, sounds about right.

**Comment by anthrotype** [comment]
it looks like we missed the opportunity to cut a release for TYPO Labs Berlin; maybe we can do it for ATypI Warsaw?

**Comment by anthrotype** [comment]
I just tagged [3.1.0](https://github.com/behdad/fonttools/releases/tag/3.1.0).
The automatic PyPI deployment on tags is also working fine, as you can see here: https://pypi.org/project/FontTools/

I spent more than an hour reading the thousands commit messages since 3.0, and only managed to mention a limited set the changes in the sparse release notes.
Please let me know if I forgot to mention something important.

Ok, we can now tell the world they can finally `pip install fonttools`! :)

**Comment by justvanrossum** [comment]
Awesome, @anthrotype, thanks!

**Comment by behdad** [comment]
Thanks @anthrotype!  To celebrate the occasion, I just transferred the repo to the fonttools org.  Please fix whatever C-I breaks! kthxbye :dancer:

**Comment by justvanrossum** [comment]
Drinks are needed!

**Comment by LettError** [comment]
Congratulations all!
