### ISSUE TITLE
[ttx] Adding glyph list option?

### ISSUE THREAD

**Issue by eosrei** [behdad/fonttools#530]
I just needed to search a directory of fonts to determine which font(s) supplied a specific glyph. Ended up scripting with fonttools, but thought it should be a ttx option like `-l` or maybe a suboption.

I'd implement, but want a yes/no/maybe on the idea first. Something like this:
```
$ ttx -g Roboto-Regular.ttf
Roboto-Regular.ttf: 0x0 .notdef
Roboto-Regular.ttf: 0x41 A
Roboto-Regular.ttf: 0xc6 AE
Roboto-Regular.ttf: 0x1fc AEacute
Roboto-Regular.ttf: 0xc1 Aacute
Roboto-Regular.ttf: 0x102 Abreve
Roboto-Regular.ttf: 0xc2 Acircumflex
Roboto-Regular.ttf: 0xc4 Adieresis
Roboto-Regular.ttf: 0xc0 Agrave
Roboto-Regular.ttf: 0x391 Alpha
Roboto-Regular.ttf: 0x386 Alphatonos
Roboto-Regular.ttf: 0x100 Amacron
Roboto-Regular.ttf: 0x104 Aogonek
Roboto-Regular.ttf: 0xc5 Aring
Roboto-Regular.ttf: 0x1fa Aringacute
Roboto-Regular.ttf: 0xc3 Atilde
Roboto-Regular.ttf: 0x42 B
Roboto-Regular.ttf: 0x392 Beta
```
In this example, I printed the font name on every line to make it simpler to parse the output with grep.

**Comment by davelab6** [comment]
https://github.com/davelab6/pyfontaine provides this: 

```
$ pyfontaine a fonts/apache/roboto/Roboto-Regular.ttf 
Font                U+0061
Roboto-Regular.ttf  True
```

So does coverage.py in https://github.com/googlei18n/nototools

**Comment by eosrei** [comment]
Perfect! That works too
