### ISSUE TITLE
Omit deprecated <colorPalettes> in 'SVG ' table

### ISSUE THREAD

**Issue by RoelN** [behdad/fonttools#531]
Only very early versions of SVG-in-OpenType versions might have this table. It has since been replaced by the CPAL table. But new fonts, when decompiled with ttx/fonttools, still get an empty `<colorPalettes>` table. Is it convention to leave empty nodes for legacy/deprecated functions? If not, maybe leave it out?

([I learned about this here](https://github.com/behdad/fonttools/blob/090fd5f5f012c209c2f479c26948a1bb2485eac0/Lib/fontTools/ttLib/tables/S_V_G_.py))

**Comment by behdad** [comment]
Right.  We should do that.  @readroberts, any chance you can take a look?  I'm not up to date on the SVG table implementation.

**Comment by readroberts** [comment]
Yes, < colorPalettes> is history. Leave it out.

**Comment by behdad** [comment]
If someone can send a Pull Request, would be great.  Otherwise, we'll fix it soonish.
