### ISSUE TITLE
TTX fails to dump CFF table

### ISSUE THREAD

**Issue by babmo12** [behdad/fonttools#532]
I have this problem with TTX, maybe someone here can help me :) 

My TTX can't dump the CFF table from any CFF-OpenType font. Small character set, or large, doesn't matter. Dumping glyf table from TTFs works fine, but with OTF I get this error, no CFF table found: 

    Macintosh-4:~ babmo$ ttx -t CFF /Users/babmo/Downloads/source-sans-pro-2.020R-ro-1.075R-it/source-sans-pro-2.020R-ro-1.075R-it/OTF/SourceSansPro-Regular.otf 
    Dumping "/Users/babmo/Downloads/source-sans-pro-2.020R-ro-1.075R-it/source-sans-pro-2.020R-ro-1.075R-it/OTF/SourceSansPro-Regular.otf" to "/Users/babmo/Downloads/source-sans-pro-2.020R-ro-1.075R-it/source-sans-pro-2.020R-ro-1.075R-it/OTF/SourceSansPro-Regular.ttx"...
    No 'CFF' table found.
    Macintosh-4:~ babmo$ 

To be sure, I tried to list the tables that TTX sees, and the CFF is there: 

    Macintosh-4:~ babmo$ ttx -l /Users/babmo/Downloads/source-sans-pro-2.020R-ro-1.075R-it/source-sans-pro-2.020R-ro-1.075R-it/OTF/SourceSansPro-Regular.otf 
    Listing table info for "/Users/babmo/Downloads/source-sans-pro-2.020R-ro-1.075R-it/source-sans-pro-2.020R-ro-1.075R-it/OTF/SourceSansPro-Regular.otf":
        tag     checksum   length   offset
        ----  ----------  -------  -------
        BASE  0x651E5DBD       70   223092
        CFF   0x854D0C8E   115352    17484
        DSIG  0xFDABBF24     6424   223164
        GDEF  0x81EA867A      962   140604
        GPOS  0xF52C24A7    66070   157020
        GSUB  0x83FA8F2B    15450   141568
        OS/2  0x5DDDD7A4       96      336
        cmap  0x8C3CEC35    13918     3532
        head  0x09D57A77       54      236
        hhea  0x0A840D58       36      292
        hmtx  0x9B6B0E59     7768   132836
        maxp  0x07965000        6      328
        name  0x1C069216     3099      432
        post  0xFFB80032       32    17452

The OTMaster lists the contents of the CFF table without any trouble. Did anyone encounter something like this?

Oh, this is a crosspost from Glyphs forum, hope you don't mind.

**Comment by anthrotype** [comment]
You have to include the space character  for sfnt table tags which are less than 4 character long, like "CFF " or "cvt ".

**Comment by babmo12** [comment]
Thank you very much, it worked with "CFF " (including quotes) :)

**Comment by behdad** [comment]
I thought we fixed ttx to accept the short tag as well...

**Comment by anthrotype** [comment]
That was the subsetter. We shall fix ttx as well.

**Comment by miguelsousa** [comment]
This got fixed in 79c2b8cbc19ec86a19607705613fe206c56cc0b7 (8 Dec 2015)
