### ISSUE TITLE
Subtle difference between FDK and feaLib with enum pos and 0 kern value

### ISSUE THREAD

**Issue by justvanrossum** [behdad/fonttools#535]
The following lookup is compiled to an empty ```<ValueFormat1 value="0"/>``` by feaLib, but to a ```<ValueFormat1 value="4"/>``` with a zero ```XAdvance``` value by FDK:
```
feature kern {
    enum pos [D E] f 0;
} kern;
```
This is no big deal -- it's a pretty stupid edge case after all -- so feel free to just close the issue.

**Comment by brawer** [comment]
Curious, would there be an advantage in changing the current behavior? Both variants are equivalent, but the current version takes a bit less space.

**Comment by justvanrossum** [comment]
I have no idea :) I'm just noting the difference. FT is obviously correct, I am just not sure to what level you guys want to be equivalent with the FDK.

**Comment by brawer** [comment]
The goal is to emit fonts that render the same, but not necessarily to emit bytewise identical tables. (By the way, FDK has actually a fair number of bugs for the corner parts of the feature file format; I’ve reported these to Adobe). Anyhow, in this case it seems that feaLib’s output is fine, so closing the bug. Please re-open if you disagree.

**Comment by twardoch** [comment]
I agree with the objective @brawer (building functionally but not binary-identical tables)

**Comment by justvanrossum** [comment]
Oh, me too. If this were FB I would've liked his comment :+1:
