### ISSUE TITLE
Fonttools unable to read Noto CJK TTC files

### ISSUE THREAD

**Issue by roozbehp** [behdad/fonttools#541]
It seems that ToT fonttools cannot read ToT noto-cjk TTC files.

Here's what I run and what I get:

```
$ PYTHONPATH=$HOME/src/fonttools/Lib python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fontTools import ttLib
>>> ttLib.TTFont('NotoSansSC-Regular.otf')
<fontTools.ttLib.TTFont object at 0x7f06c16a1790>
>>> ttLib.TTFont('NotoSansCJK-Regular.ttc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/ttLib/__init__.py", line 180, in __init__
    self.reader = sfnt.SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/ttLib/sfnt.py", line 62, in __init__
    raise ttLib.TTLibError("specify a font number between 0 and %d (inclusive)" % (self.numFonts - 1))
fontTools.ttLib.TTLibError: specify a font number between 0 and 7 (inclusive)
>>> ttLib.TTFont('NotoSansCJK-Regular.ttc', 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/ttLib/__init__.py", line 180, in __init__
    self.reader = sfnt.SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/ttLib/sfnt.py", line 62, in __init__
    raise ttLib.TTLibError("specify a font number between 0 and %d (inclusive)" % (self.numFonts - 1))
fontTools.ttLib.TTLibError: specify a font number between 0 and 7 (inclusive)
>>> ttLib.TTFont('NotoSansCJK-Regular.ttc', 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/ttLib/__init__.py", line 164, in __init__
    file = macUtils.SFNTResourceReader(file, res_name_or_index)
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/ttLib/macUtils.py", line 42, in __init__
    reader = ResourceReader(path)
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/misc/macRes.py", line 32, in __init__
    self._readFile()
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/misc/macRes.py", line 52, in _readFile
    self._readTypeList()
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/misc/macRes.py", line 93, in _readTypeList
    resources = self._readReferenceList(resType, refListOffset, numRes)
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/misc/macRes.py", line 102, in _readReferenceList
    res.decompile(refData, self)
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/misc/macRes.py", line 186, in decompile
    dataLength, = struct.unpack(">L", reader._read(4, absDataOffset))
  File "/usr/local/google/home/roozbeh/src/fonttools/Lib/fontTools/misc/macRes.py", line 67, in _read
    raise ResourceError('Cannot read resource (not enough data)')
fontTools.misc.macRes.ResourceError: Cannot read resource (not enough data)
>>>
```

fonttools version: 87d13888ce8ed2870dab5ed6ab88e2cd5979dc51
noto-cjk version: https://github.com/googlei18n/noto-cjk/commit/f36eda03dfa5582a6d49abbfb5c83d0209584158
/cc @dougfelt @kenlunde

**Comment by behdad** [comment]
Weird.  I'll try it out.  But to make sure, you're not on a Mac, are you?

**Comment by roozbehp** [comment]
Linux. Python version on top of output.

**Comment by anthrotype** [comment]
Thanks for the report, I'll also have a look.
The `macRes` module is not Mac-only, as we no longer rely on the mac-only `Res` module, but have our own `ResourceReader`.

**Comment by anthrotype** [comment]
@roozbehp is [this](https://github.com/googlei18n/noto-cjk/blob/master/NotoSansCJK-Regular.ttc) the "NotoSansCJK-Regular.ttc" file you used?

**Comment by anthrotype** [comment]
Please have a look at the signature of the TTFont class constructor. The second positional argument is `res_name_or_index` which is used for reading mac sfnt resources (ttx defaults to the first sftn resource at 0 index). For TTC, you want to use `fontNumber` keyword argument.

```python
>>> ttLib.TTFont("/Users/cosimolupo/Downloads/NotoSansCJK-Regular.ttc", fontNumber=0)
```

**Comment by anthrotype** [comment]
when we merge the DFONT/TTC into the sampe API, we shall deprecate `res_name_or_index` argument and only use `fontNumber`. See https://github.com/behdad/fonttools/issues/228

**Comment by behdad** [comment]
> Please have a look at the signature of the TTFont class constructor. The second positional argument is res_name_or_index which is used for reading mac sfnt resources (ttx defaults to the first sftn resource at 0 index). For TTC, you want to use fontNumber keyword argument.

Roozbeh is NOT setting the `res_name_or_index` argument, right?  In that case we expect this exception:
```
raise ttLib.TTLibError("specify a font number between 0 and %d (inclusive)" % (self.numFonts - 1))
```
so if we're getting error from bowels of mac resource stuff, that looks like a regression to me.

**Comment by anthrotype** [comment]
he is calling it like that
```
ttLib.TTFont('NotoSansCJK-Regular.ttc', 0)
```
so he *is* setting `res_name_or_index`.

**Comment by behdad** [comment]
Oh, my bad.

**Comment by anthrotype** [comment]
as the docstring explains, then `res_name_or_index` is set to 0 (default), then TTFont will 
> autodetect whether the file is a flat file or a suitcase. (If it's a suitcase, only the first 'sfnt' resource will be read!)

The TTC font is not a mac resource or data fork font, so the autodetection skips the resource reader, but the ttc reader fails because fontNumber=-1.

When @roozbehp tried with `res_name_or_index=2`, then the resource reader raises an exception since it does not find a resource map.

**Comment by roozbehp** [comment]
Sorry for the false alarm. Late night and overconfidence ;)
