### ISSUE TITLE
[feaLib] apply-feature-file.py snippet is broken

### ISSUE THREAD

**Issue by khaledhosny** [behdad/fonttools#553]
I’m always getting the following error:
````
Traceback (most recent call last):
  File "/fonttools/Snippets/apply-feature-file.py", line 18, in <module>
    feaLibBuilder.addOpenTypeFeatures(inputFeaturePath, font)
  File "/fonttools/Snippets/fontTools/feaLib/builder.py", line 16, in addOpenTypeFeatures
    builder = Builder(font, featurefile_path_data)
  File "/fonttools/Snippets/fontTools/feaLib/builder.py", line 24, in __init__
    self.glyphMap = font.getReverseGlyphMap()
AttributeError: 'str' object has no attribute 'getReverseGlyphMap'
````

**Comment by anthrotype** [comment]
commit 5e64857b975c842acadd0eba859c689a23c81b63 changed the signature of `addOpenTypeFeatures`:

```diff
-addOpenTypeFeatures(featurefile_path, font)
+addOpenTypeFeatures(font, featurefile_path=None, featurefile_data=None)
```

The function call in apply-feature-file.py needs to be changed accordingly. I'll do that.

**Comment by anthrotype** [comment]
Actually, I was thinking of adding `addOpenTypeFeatures` as a method of TTFont, instead of the current function in the feaLib.builder module...
What do you think? @brawer @behdad @adrientetar

**Comment by justvanrossum** [comment]
FWIW, I'd prefer to see the various (new) subpackages of fontTools as applications *of* fontTools, that just happen to live within fontTools. From that standpoint it's wrong to add it as a method to TTFont.

**Comment by anthrotype** [comment]
OK, nevermind then :)

**Comment by behdad** [comment]
> FWIW, I'd prefer to see the various (new) subpackages of fontTools as applications of fontTools, that just happen to live within fontTools. From that standpoint it's wrong to add it as a method to TTFont.

That; and I like to make TTFont API minimal.  See, for example, MockFont in mtiLib...
