### ISSUE TITLE
pyftsubset removes tables even when it shouldn't

### ISSUE THREAD

**Issue by cortopy** [behdad/fonttools#558]
I'm not sure if I'm doing something wrong, but `pyftsubset` is removing some tables that it shouldn't. I'm testing fonttools with volkorn font and the following comand:

```bash
pyftsubset Vollkorn-Regular.otf --text-file=/test/file.txt --layout-features='*' --drop-tables=
```
And a number of subtables are dropped in GDEF and GPOS. I thought by specifying the options above, tables would be kept?

**Comment by behdad** [comment]
drop-tables applies to toplevel SFNT tables.  GDEF/GPOS subtables are dropped when they become empty (because none of their glyphs survived the subsetting).
