### ISSUE TITLE
[Question] Comment ttx dump with Python Find and Replace Tool

### ISSUE THREAD

**Issue by Arno-Enslin** [behdad/fonttools#562]
I would like to comment the ttx dump with the help of a Python find and replace tool. Actually I am using the command line program [SSR (Simple Search & Replace)](http://software.reinhardt.nu/ssr/index.htm) for that purpose. Can anyone recommend a Python find and replace tool, with the help of which I can comment the TTX dump? I would like to integrate such a Python tool into my local version of the AFDKO (that contains the FontTools).

I assume, that I am not the only one, who comments the TTX dump, the name table for example.

Here are a few lines from my batch script, that makes use of SSR:

```
set "L=/SSR_NL/"

for %%f in (DecompileD\*.ttx) do (

ssr 0 "    <macStyle" "%L%<!-- Check also fsSelection in OS2-table. -->%L%<!-- macStyle value=''00000000 00000000''/ for Upright -->%L%<!-- macStyle value=''00000000 00000010''/ for Italic -->%L%<!-- macStyle value=''00000000 00000001''/ for Bold -->%L%<!-- macStyle value=''00000000 00000011''/ for Bold Italic -->%L%    <macStyle" "%%f"
ssr 0 "    <fsSelection" "%L%<!-- Check also macStyle in head-table. -->%L%<!-- fsSelection value=''00000000 00000000''/ for Upright -->%L%<!-- fsSelection value=''00000000 00000001''/ for Italic -->%L%<!-- fsSelection value=''00000000 00100000''/ for Bold -->%L%<!-- fsSelection value=''00000000 00100001'' for Bold Italic/ -->%L%    <fsSelection" "%%f"
```

**Comment by anthrotype** [comment]
Hi Arno,
The github issues is not the best place for this kind of questions. I'd suggest you forward it to the FontTools mailing list: https://groups.google.com/forum/#!forum/fonttools.
Cheers
