### ISSUE TITLE
TTX file format

### ISSUE THREAD

**Issue by bjesus** [behdad/fonttools#577]
Hi,
I couldn't understand whether TTX is some kind of a standard XML representation of font files, or is it something solely made for this project?

I'm looking for a specification of the format, especially for the <namerecord> area, where I have no clue what each `nameID` and `platformID` means.

Any idea where I can find information about it?

(I'm trying to write a font renamer using fonttools)

**Comment by twardoch** [comment]
The `.ttx` XML format has been created specifically for this project, but it is the “de-facto” standard for intermediate representation of OpenType font files in XML. The format cannot be used directly by any font engine, so it’s an intermediate format where the `ttx` tool can convert from `.otf` or `.ttf` into `.ttx` and back. 

The format follows rather closely the TrueType and OpenType font file specifications, with various spec field names being reflected in XML element names. See: 
* https://www.microsoft.com/en-us/Typography/OpenTypeSpecification.aspx
* https://developer.apple.com/fonts/TrueType-Reference-Manual/

For renaming, you need to consult the `name` table spec: 
https://www.microsoft.com/typography/otspec/name.htm

You may also check the `renameFont` function I wrote for
https://github.com/twardoch/fonttools-utils/blob/master/pyftfeatfreeze/pyftfeatfreeze.py

Regards,
Adam

**Comment by bjesus** [comment]
Excellent, thank you so much!
