### ISSUE TITLE
[feaLib] Lexer for double quote strings should not stop at newline?

### ISSUE THREAD

**Issue by punchcutter** [behdad/fonttools#578]
I have fonts and fea files with a name table where some nameid strings have newlines in the string. According to the spec 

> A string is composed of 1-byte ASCII characters enclosed by ASCII double quote characters ("). Newlines embedded within the string are removed from the character sequence to be stored.

Looking at a ttx dump these strings have `&#13;` inserted for the newlines so ttx seems to have no issue, but loading the fea file with feaLib fails because in lexer.py there is `self.scan_until_('"\r\n')`
If I remove  `\r\n` it loads fine, but then test_string fails in lexer_test.py because it doesn't raise an Exception at the embedded newline. Maybe I'm missing something, but I don't see a reason for the `\r\n` in the double quote lexer.

**Comment by brawer** [comment]
Many thanks for the report; sounds like a bug. (I'm traveling next week so it may take a few days until I've a fix ready, sorry about that).

**Comment by anthrotype** [comment]
@brawer FWIW, i'm almost done fixing it. I'll send a PR and you can have a look at it next week.
