### ISSUE TITLE
Error running symfont: global name 'P' is not defined

### ISSUE THREAD

**Issue by n8willis** [behdad/fonttools#595]
Running into an error with the symfont.py in Snippets.  Regardless of the font file or glyph arguments, it dies (AFAICT) right after it enters _glyph.draw(transformer) the first time.  This is on Python 2.7.10, on Ubuntu 15.10.  Though I've now tried it both in a virtual environment and using the normal system Python, on two different machines, with identical results.

Traceback:

> upem 1000
>
>glyph: e
>Traceback (most recent call last):
>  File "symfont.py", line 248, in <module>
>    main(sys.argv[1:])
>  File "symfont.py", line 244, in main
>    test(font.getGlyphSet(), font['head'].unitsPerEm, glyphs)
>  File "symfont.py", line 234, in test
>    print ("%s: %g" % (item, getattr(stats, item)))
>  File "symfont.py", line 151, in _penAttr
>    self._glyph.draw(transformer)
>  File "/home/nate/code/virtualenv/sympy/fonttools/Snippets/fontTools/ttLib/__init__.py", line 748, in draw
>    glyph.draw(pen, glyfTable, offset)
>  File "/home/nate/code/virtualenv/sympy/fonttools/Snippets/fontTools/ttLib/tables/_g_l_y_f.py", line 978, in draw
>    pen.qCurveTo(*contour[:nextOnCurve])
>  File "/home/nate/code/virtualenv/sympy/fonttools/Snippets/fontTools/pens/transformPen.py", line 42, in qCurveTo
>    self._outPen.qCurveTo(*points)
>  File "/home/nate/code/virtualenv/sympy/fonttools/Snippets/fontTools/pens/basePen.py", line 278, in qCurveTo
>    _qCurveToOne(pt1, pt2)
>  File "symfont.py", line 94, in _qCurveToOne
>    self._segment(p0,p1,p2)
>  File "symfont.py", line 83, in _segment
>    self.value += self._funcs[len(P) - 1](P)
>  File "<string>", line 1, in <lambda>
>NameError: global name 'P' is not defined

I'm pretty confident this isn't something totally obvious, since I could reproduce it in a virtualenv, but I don't know.  Any suggestions?

**Comment by behdad** [comment]
Humm.  Any idea why it does not happen for me?

**Comment by behdad** [comment]
Can you try with master and reopen if it's not fixed?

**Comment by anthrotype** [comment]
That also works for me. @behdad Whatever version of sympy are you using?

**Comment by anthrotype** [comment]
Spell checker. i meant "what version", not "whatever"... (from my mobile)

**Comment by behdad** [comment]
python-sympy 0.7.4.1-1 on Ubuntu

**Comment by anthrotype** [comment]
IMO, it's better to install sympy via pip, as Ubuntu packages are not always up to date.
