### ISSUE TITLE
ttx > .otf > .ttf - something is up...

### ISSUE THREAD

**Issue by HKUB** [behdad/fonttools#611]
I have recently started using ttx through Terminal on my Mac. Great script / tool!

I have a version of ttx on my Mac laptop and it outputs my .ttx files nicely through Terminal to .otf

I have installed the exact same package on my desktop computer and now it output all my .ttx files with a .ttf suffix. 

My ttx file is CFF flavoured and does not contain any GLYF tables.

2 computers > same program / script > different output. 

I can't seem to find an explanation / solution to this minor issue (apart from manually changing the suffix to .otf), it looks like the font is indeed a .otf font file but has the 'wrong' suffix applied through conversion.

Can you kindly advise

Many thanks in advance
Henrik

**Comment by miguelsousa** [comment]
Does the header of the `.ttx` files have a `sfntVersion` parameter?
```xml
<ttFont sfntVersion="OTTO">
```

**Comment by HKUB** [comment]
Yes it does:<?xml version="1.0" encoding="utf-8"?><ttFont sfntVersion="OTTO" ttLibVersion="2.4">Should I change this specific code?H.On 27 May 2016 at 17:31 Miguel Sousa <notifications@github.com> wrote:Does the header of the .ttx files have a sfntVersion parameter?<ttFont sfntVersion="OTTO">—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by HKUB** [comment]
Nope. They are matching.

**Comment by anthrotype** [comment]
> ttLibVersion="2.4"

You are using an old version of fonttools. Please uninstall and reinstall the current version.
