### ISSUE TITLE
solveCubic needs fixes (or perhaps its algorithm replaced)

### ISSUE THREAD

**Issue by miguelsousa** [behdad/fonttools#617]
I've been investigating why Robofab's [correctDirection](https://github.com/robofab-developers/robofab/blob/673acdc829b85af6393b64d79e89fb63ae13d312/Lib/robofab/objects/objectsBase.py#L1552) fails to correctly set the direction of some contours, and I think I found one possible cause: the method uses FontTools' [PointInsidePen](https://github.com/behdad/fonttools/blob/c3056bcae52087efadbd976b1d793c8a90fc35ad/Lib/fontTools/pens/pointInsidePen.py#L20) which in turn relies on [solveCubic](https://github.com/behdad/fonttools/blob/c3056bcae52087efadbd976b1d793c8a90fc35ad/Lib/fontTools/misc/bezierTools.py#L289). What I found in my exploration is that in some cases `solveCubic` does not return the correct list roots. Observe these two examples:
```python
from fontTools.misc.bezierTools import solveCubic
print solveCubic(-10.0, -9.0, 48.0, -29.0)     #1
print solveCubic(-9.875, -9.0, 47.625, -28.75) #2
```
**Equation 1: `-10x³ - 9x² + 48x - 29 = 0`**
[This equation has two solutions](http://www.wolframalpha.com/input/?i=solve+-10.0*x**3+-+9.0*x**2+%2B+48*x+-+29+%3D+0), `x = 1` and `x = -29 / 10`.
The output of `solveCubic` is ```[-2.9, 0.9999999999999993, 1.000000000000001]```.

**Equation 2: `-9.875x³ - 9x² + 47.625x - 28.75 = 0`**
[This equation also has two solutions](http://www.wolframalpha.com/input/?i=solve+-9.875*x**3+-+9.0*x**2+%2B+47.625*x+-+28.75+%3D+0), `x = 1` and `x = -230 / 79`.
The output of `solveCubic` is ```[-2.911392405063291]```.

While the rounding error in the results of the first equation is expected, the missing solution(s) in the output of the second equation is a real problem.

There are several [methods for solving cubic functions](https://en.wikipedia.org/wiki/Cubic_function). I've experimented with the method detailed [on this page](http://www.1728.org/cubic2.htm). It yielded several more correct path directions, but wasn't the silver bullet I was hoping for. Perhaps it's still not the best algorithm, or there are possibly other bugs in the code path chain.

It'd be great if you guys could have a look at this. Thanks!

**Comment by behdad** [comment]
Thanks for the report.  Can you share your implementation‌?  Last time I looked at solveCubic(), I couldn't improve it.

**Comment by behdad** [comment]
Please reopen if this is still an issue.

**Comment by anthrotype** [comment]
cool!
BTW, I also found this in the treasure chest of Graphic Gems:
https://github.com/erich666/GraphicsGems/blob/master/gems/Roots3And4.c
Not sure how it compares with fonttools implementation thogh.

**Comment by behdad** [comment]
AFAICS, the fonttools implementation, the Graphic Gems, and the one you linked to before, are all the same algorithm.

**Comment by miguelsousa** [comment]
@behdad you nailed it! Bravo and thank you.
Some of the contours are still not getting the correct direction, but I suspect that the problem is somewhere else. I'll keep digging.

**Comment by behdad** [comment]
> @behdad you nailed it! Bravo and thank you.

Cheers.

Thinking more about the solveCubic(), maybe it should return duplicate roots.  I'll change it to do so.

> Some of the contours are still not getting the correct direction, but I suspect that the problem is somewhere else. I'll keep digging.

Can you add tests?  Is it PointInsidePen that is wrong, or correctDirection()?  In general, correctDirection() is not very well-defined, around intersecting contours.  What are the incorrect cases you are seeing?

I also think the contour direction stuff should move to fontTools.  Feel free to do so.

**Comment by miguelsousa** [comment]
AFAICT, PointInsidePen is working fine. I haven't tested it with the last changes you made to solveCubic() though. I suspect that now a step may have to be introduced between [these two lines](https://github.com/behdad/fonttools/blob/c3056bcae52087efadbd976b1d793c8a90fc35ad/Lib/fontTools/pens/pointInsidePen.py#L125-L126) to filter out the duplicate values.

I think I already found the other cause of the problem. What I'm seeing is that Robofab's [`_get_clockwise`](https://github.com/robofab-developers/robofab/blob/673acdc829b85af6393b64d79e89fb63ae13d312/Lib/robofab/objects/objectsBase.py#L1848) fails in some cases. The algorithm only uses on-curve points. I'm currently testing a patch that will reference off-curve points (in addition to on-curve), and it's looking promising. So far it seems that this new approach works well on many more paths, but it still fails on a few edge cases. These cases have BCPs that crossover or that overlap (see screenshot below).

<img width="753" alt="clockwise" src="https://cloud.githubusercontent.com/assets/2119742/15921785/95f18a82-2dd8-11e6-8cbd-ab35b8b8bb05.png">

**Comment by miguelsousa** [comment]
> What are the incorrect cases you are seeing?

Something simple like the glyph below. The outer contour doesn't get its direction set correctly (with the current **_get_clockwise** that uses only on-curve points). The circle is just there to show that both contours will end up with the same direction.
```xml
<glyph name="myglyph" format="1">
  <advance width="1000"/>
  <outline>
    <contour>
      <point x="771" y="367" type="line"/>
      <point x="800" y="393"/>
      <point x="808" y="399"/>
      <point x="819" y="412" type="curve"/>
      <point x="818" y="388"/>
      <point x="774" y="138"/>
      <point x="489" y="145" type="curve"/>
      <point x="188" y="145"/>
      <point x="200" y="398"/>
      <point x="200" y="421" type="curve"/>
      <point x="209" y="409"/>
      <point x="220" y="394"/>
      <point x="254" y="360" type="curve"/>
    </contour>
    <contour>
      <point x="490" y="215" type="curve" smooth="yes"/>
      <point x="459" y="215"/>
      <point x="434" y="241"/>
      <point x="434" y="271" type="curve" smooth="yes"/>
      <point x="434" y="302"/>
      <point x="459" y="327"/>
      <point x="490" y="327" type="curve" smooth="yes"/>
      <point x="521" y="327"/>
      <point x="546" y="302"/>
      <point x="546" y="271" type="curve" smooth="yes"/>
      <point x="546" y="241"/>
      <point x="521" y="215"/>
    </contour>
  </outline>
</glyph>
```

<img width="834" alt="myglyph" src="https://cloud.githubusercontent.com/assets/2119742/15922276/bbc77fb6-2ddb-11e6-9450-3685fa928127.png">

**Comment by anthrotype** [comment]
I think the whole problem would be greatly simplified if we approximate curves by polygons, the way pyclipper does in booleanOperations. The also have a very robust implementation of the point-inside-polygon algorithm, besides of course function to determine the direction of the paths.
With forward differencing it is fast to evaluate beziers at even t intervals to convert them into polygons.
I don't have the time this week to look into this unfortunately. Anyway, thanks Miguel for rising the issues and for the insights!

**Comment by anthrotype** [comment]
This is the link to the latest pyclipper
https://github.com/greginvm/pyclipper

The one currently embedded in booleanOperations is old and we need to update it to use the latest one, which by the way is also on PyPI (so pip install pyclipper just works)

**Comment by behdad** [comment]
> I think I already found the other cause of the problem. What I'm seeing is that Robofab's _get_clockwise fails in some cases.

In GLyphy I completely remove angle code in favor of area code.  It's rather trivial to calculate the area of a contour.  The sign of that gives us the direction.  You can either calculate the area of the control polygon (cheaper), or area of the actual curves (similar to symfont stuff, but can be hardcoded).  I think that's worth doing.

**Comment by anthrotype** [comment]
Or the area of the polygon approximation of the contour, which should be more precise than the control polygon but easier than the "true" area of the bezier curves, which you don't care about if you just want the direction.

**Comment by behdad** [comment]
> but easier than the "true" area of the bezier curves,

Curve area is really simple.  Here's a standalone area-pen:

```
"""Calculate the area of a glyph."""

import math
from fontTools.pens.basePen import BasePen
from collections import namedtuple

def struct (name, members):
	cls = namedtuple (name, members)
	cls.__repr__ = lambda self: "%s(%s)" % (name, ','.join(str(s) for s in self))
	return cls

class P (struct ('P', ('x', 'y'))):
	pass


def distance(p0, p1):
  return math.hypot(p0.x - p1.x, p0.y - p1.y)

def interpolate(p0, p1, t):
  return P(p0.x * (1 - t) + p1.x * t, p0.y * (1 - t) + p1.y * t)


def polygon_area(p0, p1):
  return (p1.x - p0.x) * (p1.y + p0.y) * 0.5


def quadratic_curve_area(p0, p1, p2):
  new_p2 = interpolate(p2, p1, 2.0 / 3)
  new_p1 = interpolate(p0, p1, 2.0 / 3)
  return cubic_curve_area(p0, new_p1, new_p2, p2)


def cubic_curve_area(p0, p1, p2, p3):
  x0, y0 = p0.x, p0.y
  x1, y1 = p1.x - x0, p1.y - y0
  x2, y2 = p2.x - x0, p2.y - y0
  x3, y3 = p3.x - x0, p3.y - y0
  return (
      x1 * (   -   y2 -   y3) +
      x2 * (y1        - 2*y3) +
      x3 * (y1 + 2*y2       )
  ) * 0.15


class AreaPen(BasePen):

	def __init__(self, glyphset):
		BasePen.__init__(self, glyphset)
		self.value = 0

	def _moveTo(self, p0):
		pass

	def _lineTo(self, p1):
		p0 = self._getCurrentPoint()
		self.value += polygon_area(P(*p0), P(*p1))

	def _curveToOne(self, p1, p2, p3):
		p0 = self._getCurrentPoint()
		self.value += cubic_curve_area(P(*p0), P(*p1), P(*p2), P(*p3))
		self.value += polygon_area(P(*p0), P(*p3))
```

**Comment by anthrotype** [comment]
That's really cool!

**Comment by behdad** [comment]
We should remove the P() abstraction from that and add the pen into fonttools.

**Comment by anthrotype** [comment]
Yeah, let's do that. Although the namedtuple is nice, and I don't think adds much overhead.

The area pen would give you a better contour direction detection. However for checking the "inside-ness" of a point in a contour (for the purpose of correcting the direction, based on which contour is inside which), I believe the polygon approximation idea could still be relevant, and might produce more consistent results. But I'm happy to be proven wrong once more :)

**Comment by adrientetar** [comment]
FWIW, https://github.com/typesupply/defcon/issues/15 discusses this issue. (The thread's title here could be changed now that the issue has changed.)

**Comment by behdad** [comment]
Should be all good now.

**Comment by miguelsousa** [comment]
@behdad I got a `ZeroDivisionError: float division by zero` error from **solveCubic** while using **booleanOperations** to remove contour intersections of a glyph. The traceback and the glyph are below. Any ideas on how to fix it?

```python
Traceback (most recent call last):
  File "booleanOperations/booleanGlyph.pyc", line 257, in removeOverlap
  File "booleanOperations/booleanGlyph.pyc", line 217, in _booleanMath
  File "booleanOperations/booleanOperationManager.pyc", line 58, in union
  File "booleanOperations/booleanOperationManager.pyc", line 47, in _performOperation
  File "booleanOperations/flatten.pyc", line 894, in reCurveSubSegments
  File "booleanOperations/flatten.pyc", line 254, in tValueForPoint
  File "booleanOperations/flatten.pyc", line 1046, in _tValueForPointOnCubicCurve
  File "fontTools/misc/bezierTools.pyc", line 332, in solveCubic
ZeroDivisionError: float division by zero
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="philatin" format="1">
  <advance width="634"/>
  <unicode hex="0278"/>
  <outline>
    <contour>
      <point x="350" y="586" type="line" smooth="yes"/>
      <point x="350" y="634"/>
      <point x="350" y="675"/>
      <point x="350" y="722" type="curve"/>
      <point x="320" y="710"/>
      <point x="262" y="694"/>
      <point x="212" y="688" type="curve"/>
      <point x="212" y="662" type="line"/>
      <point x="278" y="656"/>
      <point x="284" y="650"/>
      <point x="284" y="586" type="curve" smooth="yes"/>
      <point x="284" y="-141" type="line" smooth="yes"/>
      <point x="284" y="-208"/>
      <point x="274" y="-214"/>
      <point x="209" y="-220" type="curve"/>
      <point x="209" y="-246" type="line"/>
      <point x="421" y="-246" type="line"/>
      <point x="421" y="-220" type="line"/>
      <point x="356" y="-214"/>
      <point x="350" y="-208"/>
      <point x="350" y="-141" type="curve" smooth="yes"/>
    </contour>
    <contour>
      <point x="39" y="222" type="curve" smooth="yes"/>
      <point x="39" y="73"/>
      <point x="156" y="-16"/>
      <point x="313" y="-15" type="curve" smooth="yes"/>
      <point x="461" y="-14"/>
      <point x="595" y="72"/>
      <point x="595" y="229" type="curve" smooth="yes"/>
      <point x="595" y="381"/>
      <point x="469" y="454"/>
      <point x="317" y="454" type="curve"/>
      <point x="178" y="454"/>
      <point x="39" y="377"/>
    </contour>
    <contour>
      <point x="510" y="212" type="curve" smooth="yes"/>
      <point x="510" y="89"/>
      <point x="456" y="23"/>
      <point x="323" y="23" type="curve" smooth="yes"/>
      <point x="210" y="23"/>
      <point x="124" y="100"/>
      <point x="124" y="240" type="curve" smooth="yes"/>
      <point x="124" y="392"/>
      <point x="221" y="418"/>
      <point x="316" y="417" type="curve"/>
      <point x="454" y="413"/>
      <point x="510" y="316"/>
    </contour>
  </outline>
</glyph>
```

**Comment by behdad** [comment]
@miguelsousa Can you please give me the exact input to solveCubic that causes this?  Thanks.

**Comment by adrientetar** [comment]
I just added support for pasting GLIF in TruFont. Select a glyph in the font window and paste the XML above. 
I did remove overlap on that contour and didn't get any error (though a curve segment that's nearly a line was dropped from the glyph).

**Comment by adrientetar** [comment]
Take back the nearly, it is a line. Removing segments like this breaks master compatibility, though.

**Comment by behdad** [comment]
> Take back the nearly, it is a line. Removing segments like this breaks master compatibility, though.

Removing overlap in general voids master compatibility.

**Comment by miguelsousa** [comment]
@behdad The input values are `solveCubic(-12.0, 18.0, -9.0, 1.50023651123)`.
And apologies, the glyph causing this error is actually this other one:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="phisupmod" format="1">
  <advance width="386"/>
  <unicode hex="1D60"/>
  <outline>
    <contour>
      <point x="202" y="261" type="curve" smooth="yes"/>
      <point x="289" y="261"/>
      <point x="360" y="334"/>
      <point x="360" y="416" type="curve" smooth="yes"/>
      <point x="360" y="495"/>
      <point x="302" y="543"/>
      <point x="251" y="543" type="curve" smooth="yes"/>
      <point x="213" y="543"/>
      <point x="167" y="521"/>
      <point x="166" y="455" type="curve"/>
      <point x="163" y="323"/>
      <point x="166" y="211"/>
      <point x="163" y="121" type="curve"/>
      <point x="171" y="115"/>
      <point x="191" y="113"/>
      <point x="202" y="113" type="curve" smooth="yes"/>
      <point x="210" y="113"/>
      <point x="216" y="113"/>
      <point x="220" y="114" type="curve"/>
      <point x="219" y="217"/>
      <point x="218" y="323"/>
      <point x="218" y="437" type="curve"/>
      <point x="217" y="492"/>
      <point x="234" y="513"/>
      <point x="259" y="513" type="curve" smooth="yes"/>
      <point x="293" y="513"/>
      <point x="309" y="485"/>
      <point x="309" y="439" type="curve" smooth="yes"/>
      <point x="309" y="358"/>
      <point x="264" y="292"/>
      <point x="187" y="292" type="curve" smooth="yes"/>
      <point x="114" y="292"/>
      <point x="80" y="337"/>
      <point x="80" y="400" type="curve" smooth="yes"/>
      <point x="80" y="477"/>
      <point x="131" y="513"/>
      <point x="177" y="523" type="curve"/>
      <point x="178" y="532" type="line"/>
      <point x="171" y="541"/>
      <point x="149" y="552"/>
      <point x="139" y="554" type="curve"/>
      <point x="85" y="547"/>
      <point x="26" y="493"/>
      <point x="26" y="420" type="curve" smooth="yes"/>
      <point x="26" y="341"/>
      <point x="79" y="261"/>
    </contour>
  </outline>
</glyph>
```

**Comment by adrientetar** [comment]
Traceback with source code:

```
Traceback (most recent call last):
  File "/Users/adrientetar/Downloads/trufont/Lib/trufont/windows/glyphWindow.py", line 302, in _buttonAction
    button.clicked()
  File "/Users/adrientetar/Downloads/trufont/Lib/trufont/drawingTools/removeOverlapButton.py", line 26, in clicked
    removeSelectionOverlap(self._glyph)
  File "/Users/adrientetar/Downloads/trufont/Lib/trufont/drawingTools/removeOverlapButton.py", line 15, in removeSelectionOverlap
    glyph.removeOverlap()
  File "/Users/adrientetar/Downloads/trufont/Lib/trufont/objects/defcon.py", line 325, in removeOverlap
    bGlyph = bGlyph.removeOverlap()
  File "/Users/adrientetar/Downloads/booleanOperations/Lib/booleanOperations/booleanGlyph.py", line 257, in removeOverlap
    return self._booleanMath("union", None)
  File "/Users/adrientetar/Downloads/booleanOperations/Lib/booleanOperations/booleanGlyph.py", line 217, in _booleanMath
    func(contours, destination.getPointPen())
  File "/Users/adrientetar/Downloads/booleanOperations/Lib/booleanOperations/booleanOperationManager.py", line 58, in union
    return _performOperation("union", contours, [], outPen)
  File "/Users/adrientetar/Downloads/booleanOperations/Lib/booleanOperations/booleanOperationManager.py", line 47, in _performOperation
    outputContour.reCurveSubSegments(inputContours)
  File "/Users/adrientetar/Downloads/booleanOperations/Lib/booleanOperations/flatten.py", line 894, in reCurveSubSegments
    tValues = inputSegment.tValueForPoint(previousIntersectionPoint)
  File "/Users/adrientetar/Downloads/booleanOperations/Lib/booleanOperations/flatten.py", line 254, in tValueForPoint
    return _tValueForPointOnCubicCurve(point, (on1, off1, off2, on2))
  File "/Users/adrientetar/Downloads/booleanOperations/Lib/booleanOperations/flatten.py", line 1046, in _tValueForPointOnCubicCurve
    d[isHorizontal] - point[isHorizontal])
  File "/Users/adrientetar/Downloads/fonttools/Lib/fontTools/misc/bezierTools.py", line 340, in solveCubic
    theta = acos(max(min(R/sqrt(Q*Q*Q), 1.0), -1.0))
ZeroDivisionError: float division by zero
```

> Removing overlap in general voids master compatibility.

Right, but I think it's unexpected from boolean ops to do this segment cleanup thing.

**Comment by miguelsousa** [comment]
@behdad Another set of values that fails with division by zero:
```
solveCubic(9.0, 0.0, 0.0, -7.62939453125e-05)
```

**Comment by behdad** [comment]
Should be fixed.  Thanks.
