### ISSUE TITLE
PointInsidePen failure

### ISSUE THREAD

**Issue by miguelsousa** [behdad/fonttools#621]
The test point is clearly outside of the test contour, but the result of `PointInsidePen` is `True`.
```python
from fontTools.pens.pointInsidePen import PointInsidePen

def testContour(pen):
	pen.moveTo( (727.546875, 697.0) )
	pen.curveTo( (722.953125, 697.953125), (718.109375, 698.515625), (712.9375, 698.515625) )
	pen.lineTo( (504.375, 698.515625) )
	pen.curveTo( (487.328125, 719.359375), (507.84375, 783.140625), (555.796875, 783.140625) )
	pen.lineTo( (717.96875, 783.140625) )
	pen.curveTo( (738.890625, 783.140625), (748.796875, 711.5), (727.546875, 697.0) )
	pen.closePath()

testPt = (416.625, 783.140625)

piPen = PointInsidePen(None, testPt)
testContour(piPen)
print piPen.getResult()
```

**Comment by behdad** [comment]
Got a visual? :)

**Comment by adrientetar** [comment]
<img width="1012" alt="screen shot 2016-06-15 at 9 49 49 am" src="https://cloud.githubusercontent.com/assets/1250894/16082225/9e9907cc-32de-11e6-9edd-fd6b15c721c1.png">

**Comment by justvanrossum** [comment]
Tested with a fairly old fontTools (pre-github) and the answer there is correct, so this is unfortunately a regression.

**Comment by typemytype** [comment]
a bug sneaked in somewhere in bezierTools.py 
see history https://github.com/behdad/fonttools/commits/master/Lib/fontTools/misc/bezierTools.py

**Comment by miguelsousa** [comment]
The pen works fine when the coordinates are integers.
```python
from fontTools.pens.pointInsidePen import PointInsidePen

def testContour(pen):
	pen.moveTo( (728, 697) )
	pen.curveTo( (723, 698) , (718, 699) , (713, 699) )
	pen.lineTo( (504, 699) )
	pen.curveTo( (487, 719) , (508, 783) , (556, 783) )
	pen.lineTo( (718, 783) )
	pen.curveTo( (739, 783) , (749, 712) , (728, 697) )
	pen.closePath()

testPt = (416, 783)

piPen = PointInsidePen(None, testPt)
testContour(piPen)
print piPen.getResult()
```

**Comment by behdad** [comment]
Can you try with version before my solveCubic() changes?  Also, add both int and float as tests?

**Comment by miguelsousa** [comment]
Here are the results of `solveCubic()` in chronologic order:
* 78c29bc5a139e0a3b3edeb52414e3bf53d965897 (current version)
integer: False
float: True

* b2bd15d58067c3f8b864e3408f681f0d16c5c12a
Traceback: `theta = acos(min(R/sqrt(Q*Q*Q), 1.0)) ValueError: math domain error`

* d1424e9d5a93eef48d2717993a11127115398eec
Same traceback

* b30e12ae00b30a701b6829951c254d7e44c34057 (Apr 25, 2015)
integer: True
float: False

So a bug already existed before you started making the recent changes, but notice how the results are the opposite.

PR for the additional tests #622.

**Comment by justvanrossum** [comment]
I played around a bit more, too: the old version was certainly not bugfree, but I also found a case with integers that wasn't correct on both versions. Can post details some other time.

**Comment by behdad** [comment]
I've looked into this now.  There are multiple issues going on.  I'll put a fix in, but then we need lots of tests to hash out the bugs.

**Comment by miguelsousa** [comment]
@behdad I've added two more tests, and one of them fails with the latest changes. Here's a visual:
![ptinside](https://cloud.githubusercontent.com/assets/2119742/16969754/172b29ba-4dcc-11e6-823e-66eb6d381cb4.png)

**Comment by behdad** [comment]
Passing again.  Hopefully this one will stick for a while.

**Comment by miguelsousa** [comment]
@behdad you've got it, AFAICT. 👏
I'm still seeing a handful of issues with contour direction in the project I'm working on, but I've confirmed that they're not coming from PointInsidePen.
#617 can probably be closed too.

**Comment by behdad** [comment]
Thanks @miguelsousa .  Feel free to bring them to my attention if they involve code that is on github.  I'm curious to know what else can go wrong with contour direction.  Perhaps a better algorithm can be used...

**Comment by adrientetar** [comment]
> Perhaps a better algorithm can be used...

A better algorithm than calculating the area? What do you have in mind?

**Comment by anthrotype** [comment]
I guess he means a better algorithm to automatically set the recommended direction of the outermost contour given the outline type (PS vs TT). The old robofab one that's used in Robofont has some issues, some of which were caused by fonttools' PointInsidePen.

**Comment by behdad** [comment]
> A better algorithm than calculating the area? What do you have in mind?

Without having seen the code in fault, I don't know what can be done!  That's why I asked to see the code.

From what I understand, given a bunch of contours and discarding their directions, one needs to form a relationship between any two, such that for contours A and B, you want to know whether 1. they are disjoint, 2. one is fully inside the other, or 3. they intersect.  Differentiating case 2 and 3 is key.  Indeed, if contours only intersect in points but not area, there is ambiguity as to which of the three cases it is.

Or maybe I'm completely missing the point here.

**Comment by adrientetar** [comment]
Here's the algorithm in robofab: https://github.com/robofab-developers/robofab/blob/865d1848539d095bf3b9c71acc9f30f68086f9f2/Lib/robofab/objects/objectsBase.py#L1553

**Comment by behdad** [comment]
> Here's the algorithm in robofab: https://github.com/robofab-developers/robofab/blob/865d1848539d095bf3b9c71acc9f30f68086f9f2/Lib/robofab/objects/objectsBase.py#L1553

So that doesn't seem to even try finding intersecting contours.

@miguelsousa, others, can you share examples of glyphs that go wrong?

**Comment by miguelsousa** [comment]
@adrientetar what Cosimo said. With AreaPen one can determine if a contour is clockwise or counterclockwise, but that's not enough to set correct directions of a glyph that contains multiple contours.
I've been tracking down the reason why Robofab's `correctDirection()` was failing in some glyphs and it turned out there were problems in the foundation components it relies on (PointInsidePen, solveCubic, _get_clockwise). I think those are fixed now, and the remaining issues may be all in the current algorithm of correctDirection. (On the RoboFont mailing list Tal mentioned that this was old code likely in need of a rewrite).

@behdad I'll email you what I have.

**Comment by behdad** [comment]
Ok, so assuming that we have good areaPen and pointInsidePen, the rest of the problem is indeed the algorithm to decide direction of each contour.

So, those of you who deal with type: do designers use intersecting contours or not?  Do we need to support that?

My canonical usecase for this is a c-cedilla that does not use components.  Ideally the contour for 'c' and 'cedilla' are separate, but intersect.  In this case, but should be filled.  Whereas if one was fully inside the other, then that one should not be inked.  If we don't have to support this, that makes things a notch easier.

**Comment by miguelsousa** [comment]
I think the focus should be on making the algorithm work correctly on glyphs that do not have intersections. Here's what Cosimo wrote on the RoboFont list, which I very much agree with:

> I believe we should keep the algorithm simple and predictable, as well as robust. The `correctDirection` step is usually needed after the overlaps have been merged, in order to ensure glyphs follow the recommended PS or TT direction; when the designer is still drawing them, and the overlaps such as the ones in zeroslash are still present, the designer normally takes care of manually setting the contours' direction herself.

**Comment by LettError** [comment]
> On 21 Jul 2016, at 09:33, Behdad Esfahbod <notifications@github.com> wrote:
> 
> So, those of you who deal with type: do designers use intersecting contours or not? Do we need to support that?
> 
> 


Designers use overlapping outlines all the time. During the design it helps to create separate shapes that can be edited independently. It helps to localise changes, i.e. a move in one point does not affect the neighbouring segment. It helps to assert continuity in curves that are partially covered by another shape. These can be self-overlapping contours and contours overlapping others.

Many of these constructions are also relevant in interpolation, re: variations. But maybe that is a different discussion.

But the correctDirection  should not guess when there are overlaps. I agree with Miguel, keep it simple. 

E

**Comment by behdad** [comment]
Ok that's good.  So we should document this function working on non-intersecting (but possibly overlapping) contours.

In that case I think the easiest fix is to change the pointInsidePen() test to use a different point than the contour initial point.  The point to use is, to be implemented in a separate function, a point "inside" the current contour.

That function can be implemented by taking the first segment of the contour, evaluate it at t=0.12345 and then moving "inside" (based on curve derivative at that point and the contour direction) by just a bit (~.12345 unit).

That should take care of the co-inciding points.

**Comment by khaledhosny** [comment]
My experience is that doing remove overlap before correcting direction can result in wrong overlap removal e.g. in the case of c-cedilla, instead of merging the two contours one will cut into the other.

**Comment by anthrotype** [comment]
>  doing remove overlap before correcting direction can result in wrong overlap removal

IMO, that would count as a bug in the remove-overlap tool.

If the C and cedilla contour are not already following the same direction before the overlap removal, then the designer would immediately notice that while drawing, and manually fix that. 
Whereas, if they are already set in the same direction, then the overlap-removal tool should do its job and merge them, no?

**Comment by khaledhosny** [comment]
One way for the designer to fix this is to call a “correct direction” method. Well, that is what I do myself.

**Comment by miguelsousa** [comment]
@behdad I'm writing a few more tests to increase code coverage on PointInsidePen and ran into cases which I'm not sure what the correct result is supposed to be. When a point is at the edge of the contour, is it considered inside or outside? The test below passes, but it seems strange that one of the points is reported inside whereas the other is not.
```python
def test_contour_circle(self):
    def draw_contour(pen):
        pen.moveTo( (0, 100) )
        pen.curveTo( (-55, 100) , (-100, 55) , (-100, 0) )
        pen.curveTo( (-100, -55) , (-55, -100) , (0, -100) )
        pen.curveTo( (55, -100) , (100, -55) , (100, 0) )
        pen.curveTo( (100, 55) , (55, 100) , (0, 100) )

    piPen = PointInsidePen(None, (100, 0)) # this point is on the border at 3 o'clock
    draw_contour(piPen)
    self.assertEqual(piPen.intersectionCount, 1)
    self.assertEqual(piPen.getResult(), True)

    piPen = PointInsidePen(None, (0, 100)) # this point is on the border at 12 o'clock
    draw_contour(piPen)
    self.assertEqual(piPen.intersectionCount, 0)
    self.assertEqual(piPen.getResult(), False)
```

**Comment by behdad** [comment]
> When a point is at the edge of the contour, is it considered inside or outside?

Undefined.  Either in or out is ok.  It's extremely hard to implement an algorithm that has a consistent response to this, and more importantly: it's hard to imagine uses of this function that rely on this being consistent.

**Comment by miguelsousa** [comment]
Good to know.
Another question: I've noticed that explicitly closing a contour may have an effect on the value of `intersectionCount`. Is this expected?
_I'm asking because I saw you've changed the test cases from using `piPen.getResult()` to using `piPen.intersectionCount`._
```python
def test_contour_square_closed(self):
	def draw_contour(pen):
		pen.moveTo( (100, 100) )
		pen.lineTo( (-100, 100) )
		pen.lineTo( (-100, -100) )
		pen.lineTo( (100, -100) )
		pen.closePath()

	piPen = PointInsidePen(None, (0, 0)) # this point is inside
	draw_contour(piPen)
	self.assertEqual(piPen.intersectionCount, 1)
	self.assertEqual(piPen.getResult(), True)
```
```python
def test_contour_square_opened(self):
	def draw_contour(pen):
		pen.moveTo( (100, 100) )
		pen.lineTo( (-100, 100) )
		pen.lineTo( (-100, -100) )
		pen.lineTo( (100, -100) )
		# contour not explicitly closed

	piPen = PointInsidePen(None, (0, 0)) # this point is inside
	draw_contour(piPen)
	self.assertEqual(piPen.intersectionCount, 0) # different value
	self.assertEqual(piPen.getResult(), True) # "is inside" still True
```

**Comment by behdad** [comment]
@miguelsousa Should be fixed.  Though, I'd argue that contours without endPath or closePath are incomplete.
