### ISSUE TITLE
setup.py incorrectly claims pyXML dependency

### ISSUE THREAD

**Issue by 0-wiz-0** [behdad/fonttools#626]
setup.py checks for `xml.parsers.expat`, but when it does not find that, it proclaims that it needs pyXML.
This is incorrect, please fix it. (pyXML is a dead project that does not even support python-3.x; this uses the expat support coming with python itself which might however be packaged separately by a distribution.)

**Comment by anthrotype** [comment]
That was removed some month ago with commit https://github.com/behdad/fonttools/commit/bf51c78d72c9253217e3b8c46a5dd5aa5c61349c#diff-2eeaed663bd0d25b7e608891384b7298

If you can, please git pull from the latest `master/HEAD`.
Hopefully we'll tag a new release soon... 😁
