### ISSUE TITLE
[feaLib] Optimization: Remove ScriptRecords when identical to DFLT

### ISSUE THREAD

**Issue by brawer** [behdad/fonttools#628]
When feaLib compiles ScriptLists, it could check for ScriptRecords that are identical to the DFLT record (if present). If a record is identical to DFLT, it can be removed because the layout engine would fall back to DFLT if entry matches. However, this would save only a few bytes of output.

Here’s an example from the GSUB table in an early draft of [NotoSansCherokee-Regular.otf](https://github.com/behdad/fonttools/files/339177/NotoSansCherokee-Regular.otf.zip). This font was generated by [fontmake](https://github.com/googlei18n/fontmake) which calls feaLib. I believe the second ScriptRecord could be removed without any visible change.

@behdad, can you confirm that this optimization would be safe? I’m not saying we should do it anytime soon, just wanted to have it on record for a rainy day.

```xml
    <ScriptList>
      <!-- ScriptCount=2 -->
      <ScriptRecord index="0">
        <ScriptTag value="DFLT"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=2 -->
            <FeatureIndex index="0" value="0"/>
            <FeatureIndex index="1" value="1"/>
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
      <ScriptRecord index="1">
        <ScriptTag value="cher"/>
        <Script>
          <DefaultLangSys>
            <ReqFeatureIndex value="65535"/>
            <!-- FeatureCount=2 -->
            <FeatureIndex index="0" value="0"/>
            <FeatureIndex index="1" value="1"/>
          </DefaultLangSys>
          <!-- LangSysCount=0 -->
        </Script>
      </ScriptRecord>
    </ScriptList>
```

**Comment by behdad** [comment]
> @behdad, can you confirm that this optimization would be safe?

It's totally unsafe.  The script tag is used to choose shaper.

In general I don't think feaLib should perform such optimization during compile.
