### ISSUE TITLE
[feaLib] can't get include(...) to work

### ISSUE THREAD

**Issue by justvanrossum** [behdad/fonttools#641]
I somehow can't get feaLib to handle an `include()`. It gives me this exception:

`fontTools.feaLib.error.FeatureLibError: myfeatures.fea:3:22: Expected feature, languagesystem, lookup, markClass, table, or glyph class definition`

Am I missing something obvious? Run the `addfeatures.py` script in the attached folder.

[feaLibIncludeTest.zip](https://github.com/behdad/fonttools/files/385432/feaLibIncludeTest.zip)

**Comment by anthrotype** [comment]
It's the semicolon.

https://github.com/behdad/fonttools/commit/7eed24725f33c76d033e40888d865e13d47622c2

/cc @brawer

**Comment by anthrotype** [comment]
I found a fix, I'll send a PR shortly. Can I use your test feature files in feaLib tests?

**Comment by justvanrossum** [comment]
Sure!
