### ISSUE TITLE
Documentation Request: PATH for Windows

### ISSUE THREAD

**Issue by apnorton** [behdad/fonttools#644]
When installing ttx for use as a standalone application (e.g. to do "ttx Arial.ttf" or something like that) on Windows, the setup.py file creates a ttx.exe file in a Scripts directory in the computer's Python install location.  However, the PATH environment variable isn't updated to point to this ttx.exe file.

If this were documented, install would be more straightforward.  I'm happy to write up a paragraph or two to point this out, but I don't know where the best place to put it would be.

**Comment by anthrotype** [comment]
Hi @apnorton,
Sorry but is not fonttools' job to configure your Python environment, nor to explain users how to do it.
The official documentation covers all you need to know.
https://docs.python.org/3.5/using/windows.html
Cheers,

Cosimo
