### ISSUE TITLE
'pyftsubset' command occurs encoding error in WINDOWS

### ISSUE THREAD

**Issue by JasonAtGithub** [behdad/fonttools#654]
My windows system preferred encoding is 'cp936' (Chinese, result of python code 'locale.getpreferredencoding()').

when I use command:
pyftsubset myfont.ttf --text-file=myfonttable.txt

'myfonttable.txt' file is encoding as 'utf-8,unix', but the io.open() will open the text file with encoding 'cp936'.

I modified the code in subset/\__init__.py, line 2905 to:
`text += open(g[12:], encoding='utf-8').read().replace('\n', '')`
It works well.

**Comment by anthrotype** [comment]
PR?

**Comment by JasonAtGithub** [comment]
Run command:
`pyftsubset myfont.ttf --text-file=myfonttable.txt`
Occurs ERROR in windows with default codepage 936.
OS:Windows 7 professional sp1
Python Version:2.7.10

Error Traceback:
`Traceback (most recent call last):
  File "D:\Program Files\Python27\Scripts\pyftsubset-script.py", line 9, in <module>
    load_entry_point('fonttools==3.0', 'console_scripts', 'pyftsubset')()
  File "D:\Program Files\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\misc\loggin
n wrapper
    return func(*args, **kwds)
  File "D:\Program Files\Python27\lib\site-packages\fonttools-3.0-py2.7.egg\fontTools\subset\__in
 main
    text += open(g[12:]).read().replace('\n', '')
UnicodeDecodeError: 'gbk' codec can't decode bytes in position 2-3: illegal multibyte sequence`

**Comment by JasonAtGithub** [comment]
'myfonttable.txt' content:
"这是一个测试文本"
file encoding is 'utf-8', line ending is Unix style.

**Comment by JasonAtGithub** [comment]
Do you mean you want me to commit a PR?

**Comment by anthrotype** [comment]
Yes, that would be nice! :)

**Comment by JasonAtGithub** [comment]
OK, The pull request is pass, I will close this issue.

**Comment by brawer** [comment]
Just for cross-referencing, this was the pull request: https://github.com/behdad/fonttools/pull/655
