### ISSUE TITLE
glyf count vs loca count

### ISSUE THREAD

**Issue by m4rc1e** [behdad/fonttools#663]
Hey folks,

I've had a quick skim through the tables and noticed that` len(font['loca']) `is always greater than `len(font['glyf']) `by 1.

I've checked Open Sans, Arial and a few other Google Fonts.

I'm guessing the +1 may be occurring due to the following.

```
>>> font['loca'].locations
array('I', [0L, 72L, 72L, 172L,...]
```

The __len__ method for the loca table is:
```
	def __len__(self):
		return len(self.locations)
```

I guess it's including the first `I`.

Cheers,
Marc

**Comment by anthrotype** [comment]
that's just how loca works

https://www.microsoft.com/typography/otspec/loca.htm

>  In order to compute the length of the last glyph element, there is an extra entry after the last valid index.

**Comment by m4rc1e** [comment]
Thank you
