### ISSUE TITLE
differences in python 2 vs python 3 built-in round()

### ISSUE THREAD

**Issue by anthrotype** [behdad/fonttools#664]
As you know, in Python 3 the built-in round() function behaves differently from Python 2.
The former uses the so-called "Banker's Rounding", which rounds to the nearest even last digit, whereas in the latter rounding is done away from 0:

Python 3:
```python
>>> round(0.5)
0
>>> round(1.5)
2
>>> round(-0.5)
0
```

Python 2:
```python
>>> round(0.5)
1.0
>>> round(1.5)
2.0
>>> round(-0.5)
-1.0
```

I think it's a problem if one gets different results with fonttools depending on whether he uses Python 2 or 3. Think about, for example, converting cubic curves to quadratic with cu2qu package, which defers to fonttools the rounding of the approximated coordinates:
https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/_g_l_y_f.py#L1073
As you can imagine, there are many more examples like that.

The fact is, we run our test suite on each single python version we support, however we don't also test that the output is consistent *across* python versions.

I suggest we look into implementing `round3()` and `round2()` functions to `fontTools.misc.py23` module, and maybe also shadow the `round` built-in with one or the other.

For legacy reasons, one would  be tempted to keep the Python 2 `round` behavior, to prevent things from changing when switching to Python 3. However, perhaps it would be more future-proof if we go for the Python 3 `round` as the default for both Python 2 and 3, possibly giving some time for users to accommodate to the change (next major version?).

The `python-future` project has, among many cool things, a pure python implementation of the new Python 3 `round()`:
https://github.com/PythonCharmers/python-future/blob/master/src/future/builtins/newround.py

The project is widely used, and well maintained. It covers some of the stuff we already have in `py23` module, plus many more. Plus, it's available on PyPI, so it would be simply a matter of adding it to our setup.py `install_requires`.

Personally, I wouldn't like to reinvent the wheel, but I'd like to hear what the others think.

**Comment by benkiel** [comment]
For what it's worth, in fontParts it's currently handled like so: https://github.com/robofab-developers/fontParts/commit/7cb561033929cfb4a723d274672e7257f5e68237. @moyogo kindly pointed me in that direction. I made the decision to keep rounding the Python 2 way as to not break expectations in ported robofab scripts, but if this goes the Python 3 way, perhaps we'll change that.

**Comment by behdad** [comment]
Humm.  I thought we did this already.

**Comment by benkiel** [comment]
It's done in fontMath for sure: https://github.com/moyogo/fontmath/commit/f3f1229dd114415682dbca35d4a863635b1fbe57

**Comment by moyogo** [comment]
I remember looking into it a bit more and noticing it wasn’t working correctly in some cases. I did start something but I wasn’t happy with the Python2 round I had as it still wasn’t working for all my test cases.

**Comment by anthrotype** [comment]
I think we should use the python-future `newround.py`, or use the same approach as theirs, i.e. use the built-in `Decimal` module
https://docs.python.org/3.5/library/decimal.html#rounding-modes
