### ISSUE TITLE
Option to not embed Adobe Glyph List in fonttools and use system-installed version

### ISSUE THREAD

**Issue by behdad** [behdad/fonttools#83]
https://sourceforge.net/p/fonttools/bugs/33/

**Comment by brawer** [comment]
Curious, which problem would this solve? The [Adobe Glyph List](https://github.com/adobe-type-tools/agl-aglfn/blob/master/aglfn.txt) isn’t changing much; the last change was on November 6, 2008.

**Comment by anthrotype** [comment]
I don't understand.. where should the Adobe Glyph List be installed system-wise?

**Comment by twardoch** [comment]
I'd vote to reject this. AGL is highly unlikely to be changed, ever. And the integration of the Unicode standard in Python is highly problematic, and depends on the version of Python it is deployed on. 

Perhaps we might want to provide a lightweight integration to the unicodedata2 module ( https://github.com/mikekap/unicodedata2 ). That module allows users to build their own unicodedata2 module for Python 2.x from the current Unicode.org data files in a way that is compatible with the Python-provided unicodedata module (which is ancient). Something like:  
```
try: 
  import unicodedata2 as unicodedata
except ImportError: 
  import unicodedata
```
But I don't know if it's worth the overhead.

**Comment by davelab6** [comment]
> where should the Adobe Glyph List be installed system-wise?

The original issue text by @pabs referred to system-wide unicode data, which Behdad resolved with https://github.com/behdad/fonttools/commit/fea81ee2b3d820cf6beee40fa8ec95a0cfa99214 .

I agree with Adam that https://github.com/mikekap/unicodedata2 sounds good

If we wanted to expunge the aglfn, and fetch it from a URL at build time instead (such as https://raw.githubusercontent.com/adobe-type-tools/agl-aglfn/master/aglfn.txt) we could do, but I don't see a strong reason to do so; the reason given by @pabs3 was the then non-libre licensing, which has since been resolved as it is now Apache licensed. 

Regarding https://github.com/behdad/fonttools/blob/master/Lib/fontTools/ttLib/tables/otData.py Behdad said on the SF issue that it can't be automatically extracted from the spec. 

I'm not sure if there is a libre licensing concern with that data; I think we can license that code as we do, or claim it isn't subject to copyright due to utilitarian API compatibility fair use, or similar such that distros are unconcerned. If a distro has an actual concern, I am pretty sure it can be resolved.

**Comment by anthrotype** [comment]
Thanks @twardoch and @davelab6 for clarifying the issue.
I like Adam's idea of attempting to import `unicodedata2` backport module for python2, and falling back to built-in unicodedata if that isn't available.
I'll send in a PR.

**Comment by pabs3** [comment]
On Wed, 2015-09-09 at 18:28 -0700, Dave Crossland wrote:

> where should the Adobe Glyph List be installed system-wise?

This depends on the choice of the distro, on Debian we install it here:

/usr/share/aglfn/aglfn.txt

> If we wanted to expunge the aglfn, and fetch it from a URL at build
> time instead (such as https://raw.githubusercontent.com/adobe-type
> -tools/agl-aglfn/master/aglfn.txt) we could do

This would be problematic for distros as they don't usually allow
downloading anything at build time. I'd suggest loading it at runtime
instead, from a build-time configured path. If no path is configured
then you could download it and embed it in fonttools.

> Regarding .../otData.py Behdad said on the SF issue that it can't be
> automatically extracted from the spec.

I was working on this at one point, attached the WIP script I had for
that. In addition to replacing MetaTools/build_otData.py, these files
should be updated/deleted if they are not already:

Lib/fontTools/ttLib/tables/otData.py
MetaTools/doco.diff


> I'm not sure if there is a libre licensing concern with that data; I
> think we can license that code as we do, or claim it isn't subject to
> copyright due to utilitarian API compatibility fair use, or similar
> such that distros are unconcerned. If a distro has an actual concern,
> I am pretty sure it can be resolved.

Personally I think the English text should be stripped from otData.py
as (from memory) it isn't used by the code and is more likely to be
copyrightable (and possibly non-free) than the names and other parts.

-- 
bye,
pabs

http://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
Bah, github doesn't look at email attachments, posted via the web.

**Comment by pabs3** [comment]
Nor the web, hmm.

Here is the code, feel free to use it under whatever license you want:

https://paste.debian.net/312318/

**Comment by brawer** [comment]
Sorry for lacking context of this discussion, but which problem are we trying to solve?

If it’s licensing: Adobe has [released](https://github.com/adobe-type-tools/agl-aglfn/blob/master/aglfn.txt) the data file under the Apache 2.0 license. Not free enough?

If it’s keeping track of upstream changes: Is it an actual problem? The file has last been changed seven years ago, and (as @twardoch pointed out earlier on this bug) it is rather unlikely to ever change again. Should it change, we’ll certainly update fonttools.

**Comment by davelab6** [comment]
> If it’s licensing: Adobe has released the data file under the Apache 2.0 license. Not free enough?

`otData.py` includes data from the OpenType spec, which (afaik) Adobe hasn't liberated. But I expect it would be straightforward to get them to do so if there is a problem.

**Comment by behdad** [comment]
Dave, stay on-topic please.

There's nothing to fix here AFAICS.  otData CAN'T BE AUTO-CREATED.  There's no point in run-time-loading a file that is not expected to ever change again.

**Comment by davelab6** [comment]
I agree

**Comment by pabs3** [comment]
I expect otData actually can be auto-created. The documentation in otData should be removed at least.

I still think keeping a copy of aglfn instead of depending on it is the wrong way to go.
